package cn.koolyun.model;

import java.math.BigDecimal;

public class AgFile {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CHPS.AG_FILE.PLAT_DATE
     *
     * @mbggenerated Wed Oct 19 16:02:52 CST 2016
     */
    private BigDecimal platDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CHPS.AG_FILE.PLAT_TIME
     *
     * @mbggenerated Wed Oct 19 16:02:52 CST 2016
     */
    private String platTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CHPS.AG_FILE.PLAT_TRACE
     *
     * @mbggenerated Wed Oct 19 16:02:52 CST 2016
     */
    private BigDecimal platTrace;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CHPS.AG_FILE.AGENT_NO
     *
     * @mbggenerated Wed Oct 19 16:02:52 CST 2016
     */
    private String agentNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CHPS.AG_FILE.AC_NO
     *
     * @mbggenerated Wed Oct 19 16:02:52 CST 2016
     */
    private String acNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CHPS.AG_FILE.PRDT_NO
     *
     * @mbggenerated Wed Oct 19 16:02:52 CST 2016
     */
    private String prdtNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CHPS.AG_FILE.TX_AMT
     *
     * @mbggenerated Wed Oct 19 16:02:52 CST 2016
     */
    private BigDecimal txAmt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CHPS.AG_FILE.STS
     *
     * @mbggenerated Wed Oct 19 16:02:52 CST 2016
     */
    private String sts;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CHPS.AG_FILE.HOST_STS
     *
     * @mbggenerated Wed Oct 19 16:02:52 CST 2016
     */
    private String hostSts;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CHPS.AG_FILE.BRF
     *
     * @mbggenerated Wed Oct 19 16:02:52 CST 2016
     */
    private String brf;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CHPS.AG_FILE.TX_BR_NO
     *
     * @mbggenerated Wed Oct 19 16:02:52 CST 2016
     */
    private String txBrNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CHPS.AG_FILE.TX_TEL
     *
     * @mbggenerated Wed Oct 19 16:02:52 CST 2016
     */
    private String txTel;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CHPS.AG_FILE.PLAT_DATE
     *
     * @return the value of CHPS.AG_FILE.PLAT_DATE
     *
     * @mbggenerated Wed Oct 19 16:02:52 CST 2016
     */
    public BigDecimal getPlatDate() {
        return platDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CHPS.AG_FILE.PLAT_DATE
     *
     * @param platDate the value for CHPS.AG_FILE.PLAT_DATE
     *
     * @mbggenerated Wed Oct 19 16:02:52 CST 2016
     */
    public void setPlatDate(BigDecimal platDate) {
        this.platDate = platDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CHPS.AG_FILE.PLAT_TIME
     *
     * @return the value of CHPS.AG_FILE.PLAT_TIME
     *
     * @mbggenerated Wed Oct 19 16:02:52 CST 2016
     */
    public String getPlatTime() {
        return platTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CHPS.AG_FILE.PLAT_TIME
     *
     * @param platTime the value for CHPS.AG_FILE.PLAT_TIME
     *
     * @mbggenerated Wed Oct 19 16:02:52 CST 2016
     */
    public void setPlatTime(String platTime) {
        this.platTime = platTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CHPS.AG_FILE.PLAT_TRACE
     *
     * @return the value of CHPS.AG_FILE.PLAT_TRACE
     *
     * @mbggenerated Wed Oct 19 16:02:52 CST 2016
     */
    public BigDecimal getPlatTrace() {
        return platTrace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CHPS.AG_FILE.PLAT_TRACE
     *
     * @param platTrace the value for CHPS.AG_FILE.PLAT_TRACE
     *
     * @mbggenerated Wed Oct 19 16:02:52 CST 2016
     */
    public void setPlatTrace(BigDecimal platTrace) {
        this.platTrace = platTrace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CHPS.AG_FILE.AGENT_NO
     *
     * @return the value of CHPS.AG_FILE.AGENT_NO
     *
     * @mbggenerated Wed Oct 19 16:02:52 CST 2016
     */
    public String getAgentNo() {
        return agentNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CHPS.AG_FILE.AGENT_NO
     *
     * @param agentNo the value for CHPS.AG_FILE.AGENT_NO
     *
     * @mbggenerated Wed Oct 19 16:02:52 CST 2016
     */
    public void setAgentNo(String agentNo) {
        this.agentNo = agentNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CHPS.AG_FILE.AC_NO
     *
     * @return the value of CHPS.AG_FILE.AC_NO
     *
     * @mbggenerated Wed Oct 19 16:02:52 CST 2016
     */
    public String getAcNo() {
        return acNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CHPS.AG_FILE.AC_NO
     *
     * @param acNo the value for CHPS.AG_FILE.AC_NO
     *
     * @mbggenerated Wed Oct 19 16:02:52 CST 2016
     */
    public void setAcNo(String acNo) {
        this.acNo = acNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CHPS.AG_FILE.PRDT_NO
     *
     * @return the value of CHPS.AG_FILE.PRDT_NO
     *
     * @mbggenerated Wed Oct 19 16:02:52 CST 2016
     */
    public String getPrdtNo() {
        return prdtNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CHPS.AG_FILE.PRDT_NO
     *
     * @param prdtNo the value for CHPS.AG_FILE.PRDT_NO
     *
     * @mbggenerated Wed Oct 19 16:02:52 CST 2016
     */
    public void setPrdtNo(String prdtNo) {
        this.prdtNo = prdtNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CHPS.AG_FILE.TX_AMT
     *
     * @return the value of CHPS.AG_FILE.TX_AMT
     *
     * @mbggenerated Wed Oct 19 16:02:52 CST 2016
     */
    public BigDecimal getTxAmt() {
        return txAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CHPS.AG_FILE.TX_AMT
     *
     * @param txAmt the value for CHPS.AG_FILE.TX_AMT
     *
     * @mbggenerated Wed Oct 19 16:02:52 CST 2016
     */
    public void setTxAmt(BigDecimal txAmt) {
        this.txAmt = txAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CHPS.AG_FILE.STS
     *
     * @return the value of CHPS.AG_FILE.STS
     *
     * @mbggenerated Wed Oct 19 16:02:52 CST 2016
     */
    public String getSts() {
        return sts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CHPS.AG_FILE.STS
     *
     * @param sts the value for CHPS.AG_FILE.STS
     *
     * @mbggenerated Wed Oct 19 16:02:52 CST 2016
     */
    public void setSts(String sts) {
        this.sts = sts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CHPS.AG_FILE.HOST_STS
     *
     * @return the value of CHPS.AG_FILE.HOST_STS
     *
     * @mbggenerated Wed Oct 19 16:02:52 CST 2016
     */
    public String getHostSts() {
        return hostSts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CHPS.AG_FILE.HOST_STS
     *
     * @param hostSts the value for CHPS.AG_FILE.HOST_STS
     *
     * @mbggenerated Wed Oct 19 16:02:52 CST 2016
     */
    public void setHostSts(String hostSts) {
        this.hostSts = hostSts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CHPS.AG_FILE.BRF
     *
     * @return the value of CHPS.AG_FILE.BRF
     *
     * @mbggenerated Wed Oct 19 16:02:52 CST 2016
     */
    public String getBrf() {
        return brf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CHPS.AG_FILE.BRF
     *
     * @param brf the value for CHPS.AG_FILE.BRF
     *
     * @mbggenerated Wed Oct 19 16:02:52 CST 2016
     */
    public void setBrf(String brf) {
        this.brf = brf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CHPS.AG_FILE.TX_BR_NO
     *
     * @return the value of CHPS.AG_FILE.TX_BR_NO
     *
     * @mbggenerated Wed Oct 19 16:02:52 CST 2016
     */
    public String getTxBrNo() {
        return txBrNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CHPS.AG_FILE.TX_BR_NO
     *
     * @param txBrNo the value for CHPS.AG_FILE.TX_BR_NO
     *
     * @mbggenerated Wed Oct 19 16:02:52 CST 2016
     */
    public void setTxBrNo(String txBrNo) {
        this.txBrNo = txBrNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CHPS.AG_FILE.TX_TEL
     *
     * @return the value of CHPS.AG_FILE.TX_TEL
     *
     * @mbggenerated Wed Oct 19 16:02:52 CST 2016
     */
    public String getTxTel() {
        return txTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CHPS.AG_FILE.TX_TEL
     *
     * @param txTel the value for CHPS.AG_FILE.TX_TEL
     *
     * @mbggenerated Wed Oct 19 16:02:52 CST 2016
     */
    public void setTxTel(String txTel) {
        this.txTel = txTel;
    }
}