package cn.koolyun.model;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

public class AgFileExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table CHPS.AG_FILE
     *
     * @mbggenerated Wed Oct 19 16:02:52 CST 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table CHPS.AG_FILE
     *
     * @mbggenerated Wed Oct 19 16:02:52 CST 2016
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table CHPS.AG_FILE
     *
     * @mbggenerated Wed Oct 19 16:02:52 CST 2016
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHPS.AG_FILE
     *
     * @mbggenerated Wed Oct 19 16:02:52 CST 2016
     */
    public AgFileExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHPS.AG_FILE
     *
     * @mbggenerated Wed Oct 19 16:02:52 CST 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHPS.AG_FILE
     *
     * @mbggenerated Wed Oct 19 16:02:52 CST 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHPS.AG_FILE
     *
     * @mbggenerated Wed Oct 19 16:02:52 CST 2016
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHPS.AG_FILE
     *
     * @mbggenerated Wed Oct 19 16:02:52 CST 2016
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHPS.AG_FILE
     *
     * @mbggenerated Wed Oct 19 16:02:52 CST 2016
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHPS.AG_FILE
     *
     * @mbggenerated Wed Oct 19 16:02:52 CST 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHPS.AG_FILE
     *
     * @mbggenerated Wed Oct 19 16:02:52 CST 2016
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHPS.AG_FILE
     *
     * @mbggenerated Wed Oct 19 16:02:52 CST 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHPS.AG_FILE
     *
     * @mbggenerated Wed Oct 19 16:02:52 CST 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHPS.AG_FILE
     *
     * @mbggenerated Wed Oct 19 16:02:52 CST 2016
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table CHPS.AG_FILE
     *
     * @mbggenerated Wed Oct 19 16:02:52 CST 2016
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andPlatDateIsNull() {
            addCriterion("PLAT_DATE is null");
            return (Criteria) this;
        }

        public Criteria andPlatDateIsNotNull() {
            addCriterion("PLAT_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andPlatDateEqualTo(BigDecimal value) {
            addCriterion("PLAT_DATE =", value, "platDate");
            return (Criteria) this;
        }

        public Criteria andPlatDateNotEqualTo(BigDecimal value) {
            addCriterion("PLAT_DATE <>", value, "platDate");
            return (Criteria) this;
        }

        public Criteria andPlatDateGreaterThan(BigDecimal value) {
            addCriterion("PLAT_DATE >", value, "platDate");
            return (Criteria) this;
        }

        public Criteria andPlatDateGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("PLAT_DATE >=", value, "platDate");
            return (Criteria) this;
        }

        public Criteria andPlatDateLessThan(BigDecimal value) {
            addCriterion("PLAT_DATE <", value, "platDate");
            return (Criteria) this;
        }

        public Criteria andPlatDateLessThanOrEqualTo(BigDecimal value) {
            addCriterion("PLAT_DATE <=", value, "platDate");
            return (Criteria) this;
        }

        public Criteria andPlatDateIn(List<BigDecimal> values) {
            addCriterion("PLAT_DATE in", values, "platDate");
            return (Criteria) this;
        }

        public Criteria andPlatDateNotIn(List<BigDecimal> values) {
            addCriterion("PLAT_DATE not in", values, "platDate");
            return (Criteria) this;
        }

        public Criteria andPlatDateBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("PLAT_DATE between", value1, value2, "platDate");
            return (Criteria) this;
        }

        public Criteria andPlatDateNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("PLAT_DATE not between", value1, value2, "platDate");
            return (Criteria) this;
        }

        public Criteria andPlatTimeIsNull() {
            addCriterion("PLAT_TIME is null");
            return (Criteria) this;
        }

        public Criteria andPlatTimeIsNotNull() {
            addCriterion("PLAT_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andPlatTimeEqualTo(String value) {
            addCriterion("PLAT_TIME =", value, "platTime");
            return (Criteria) this;
        }

        public Criteria andPlatTimeNotEqualTo(String value) {
            addCriterion("PLAT_TIME <>", value, "platTime");
            return (Criteria) this;
        }

        public Criteria andPlatTimeGreaterThan(String value) {
            addCriterion("PLAT_TIME >", value, "platTime");
            return (Criteria) this;
        }

        public Criteria andPlatTimeGreaterThanOrEqualTo(String value) {
            addCriterion("PLAT_TIME >=", value, "platTime");
            return (Criteria) this;
        }

        public Criteria andPlatTimeLessThan(String value) {
            addCriterion("PLAT_TIME <", value, "platTime");
            return (Criteria) this;
        }

        public Criteria andPlatTimeLessThanOrEqualTo(String value) {
            addCriterion("PLAT_TIME <=", value, "platTime");
            return (Criteria) this;
        }

        public Criteria andPlatTimeLike(String value) {
            addCriterion("PLAT_TIME like", value, "platTime");
            return (Criteria) this;
        }

        public Criteria andPlatTimeNotLike(String value) {
            addCriterion("PLAT_TIME not like", value, "platTime");
            return (Criteria) this;
        }

        public Criteria andPlatTimeIn(List<String> values) {
            addCriterion("PLAT_TIME in", values, "platTime");
            return (Criteria) this;
        }

        public Criteria andPlatTimeNotIn(List<String> values) {
            addCriterion("PLAT_TIME not in", values, "platTime");
            return (Criteria) this;
        }

        public Criteria andPlatTimeBetween(String value1, String value2) {
            addCriterion("PLAT_TIME between", value1, value2, "platTime");
            return (Criteria) this;
        }

        public Criteria andPlatTimeNotBetween(String value1, String value2) {
            addCriterion("PLAT_TIME not between", value1, value2, "platTime");
            return (Criteria) this;
        }

        public Criteria andPlatTraceIsNull() {
            addCriterion("PLAT_TRACE is null");
            return (Criteria) this;
        }

        public Criteria andPlatTraceIsNotNull() {
            addCriterion("PLAT_TRACE is not null");
            return (Criteria) this;
        }

        public Criteria andPlatTraceEqualTo(BigDecimal value) {
            addCriterion("PLAT_TRACE =", value, "platTrace");
            return (Criteria) this;
        }

        public Criteria andPlatTraceNotEqualTo(BigDecimal value) {
            addCriterion("PLAT_TRACE <>", value, "platTrace");
            return (Criteria) this;
        }

        public Criteria andPlatTraceGreaterThan(BigDecimal value) {
            addCriterion("PLAT_TRACE >", value, "platTrace");
            return (Criteria) this;
        }

        public Criteria andPlatTraceGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("PLAT_TRACE >=", value, "platTrace");
            return (Criteria) this;
        }

        public Criteria andPlatTraceLessThan(BigDecimal value) {
            addCriterion("PLAT_TRACE <", value, "platTrace");
            return (Criteria) this;
        }

        public Criteria andPlatTraceLessThanOrEqualTo(BigDecimal value) {
            addCriterion("PLAT_TRACE <=", value, "platTrace");
            return (Criteria) this;
        }

        public Criteria andPlatTraceIn(List<BigDecimal> values) {
            addCriterion("PLAT_TRACE in", values, "platTrace");
            return (Criteria) this;
        }

        public Criteria andPlatTraceNotIn(List<BigDecimal> values) {
            addCriterion("PLAT_TRACE not in", values, "platTrace");
            return (Criteria) this;
        }

        public Criteria andPlatTraceBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("PLAT_TRACE between", value1, value2, "platTrace");
            return (Criteria) this;
        }

        public Criteria andPlatTraceNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("PLAT_TRACE not between", value1, value2, "platTrace");
            return (Criteria) this;
        }

        public Criteria andAgentNoIsNull() {
            addCriterion("AGENT_NO is null");
            return (Criteria) this;
        }

        public Criteria andAgentNoIsNotNull() {
            addCriterion("AGENT_NO is not null");
            return (Criteria) this;
        }

        public Criteria andAgentNoEqualTo(String value) {
            addCriterion("AGENT_NO =", value, "agentNo");
            return (Criteria) this;
        }

        public Criteria andAgentNoNotEqualTo(String value) {
            addCriterion("AGENT_NO <>", value, "agentNo");
            return (Criteria) this;
        }

        public Criteria andAgentNoGreaterThan(String value) {
            addCriterion("AGENT_NO >", value, "agentNo");
            return (Criteria) this;
        }

        public Criteria andAgentNoGreaterThanOrEqualTo(String value) {
            addCriterion("AGENT_NO >=", value, "agentNo");
            return (Criteria) this;
        }

        public Criteria andAgentNoLessThan(String value) {
            addCriterion("AGENT_NO <", value, "agentNo");
            return (Criteria) this;
        }

        public Criteria andAgentNoLessThanOrEqualTo(String value) {
            addCriterion("AGENT_NO <=", value, "agentNo");
            return (Criteria) this;
        }

        public Criteria andAgentNoLike(String value) {
            addCriterion("AGENT_NO like", value, "agentNo");
            return (Criteria) this;
        }

        public Criteria andAgentNoNotLike(String value) {
            addCriterion("AGENT_NO not like", value, "agentNo");
            return (Criteria) this;
        }

        public Criteria andAgentNoIn(List<String> values) {
            addCriterion("AGENT_NO in", values, "agentNo");
            return (Criteria) this;
        }

        public Criteria andAgentNoNotIn(List<String> values) {
            addCriterion("AGENT_NO not in", values, "agentNo");
            return (Criteria) this;
        }

        public Criteria andAgentNoBetween(String value1, String value2) {
            addCriterion("AGENT_NO between", value1, value2, "agentNo");
            return (Criteria) this;
        }

        public Criteria andAgentNoNotBetween(String value1, String value2) {
            addCriterion("AGENT_NO not between", value1, value2, "agentNo");
            return (Criteria) this;
        }

        public Criteria andAcNoIsNull() {
            addCriterion("AC_NO is null");
            return (Criteria) this;
        }

        public Criteria andAcNoIsNotNull() {
            addCriterion("AC_NO is not null");
            return (Criteria) this;
        }

        public Criteria andAcNoEqualTo(String value) {
            addCriterion("AC_NO =", value, "acNo");
            return (Criteria) this;
        }

        public Criteria andAcNoNotEqualTo(String value) {
            addCriterion("AC_NO <>", value, "acNo");
            return (Criteria) this;
        }

        public Criteria andAcNoGreaterThan(String value) {
            addCriterion("AC_NO >", value, "acNo");
            return (Criteria) this;
        }

        public Criteria andAcNoGreaterThanOrEqualTo(String value) {
            addCriterion("AC_NO >=", value, "acNo");
            return (Criteria) this;
        }

        public Criteria andAcNoLessThan(String value) {
            addCriterion("AC_NO <", value, "acNo");
            return (Criteria) this;
        }

        public Criteria andAcNoLessThanOrEqualTo(String value) {
            addCriterion("AC_NO <=", value, "acNo");
            return (Criteria) this;
        }

        public Criteria andAcNoLike(String value) {
            addCriterion("AC_NO like", value, "acNo");
            return (Criteria) this;
        }

        public Criteria andAcNoNotLike(String value) {
            addCriterion("AC_NO not like", value, "acNo");
            return (Criteria) this;
        }

        public Criteria andAcNoIn(List<String> values) {
            addCriterion("AC_NO in", values, "acNo");
            return (Criteria) this;
        }

        public Criteria andAcNoNotIn(List<String> values) {
            addCriterion("AC_NO not in", values, "acNo");
            return (Criteria) this;
        }

        public Criteria andAcNoBetween(String value1, String value2) {
            addCriterion("AC_NO between", value1, value2, "acNo");
            return (Criteria) this;
        }

        public Criteria andAcNoNotBetween(String value1, String value2) {
            addCriterion("AC_NO not between", value1, value2, "acNo");
            return (Criteria) this;
        }

        public Criteria andPrdtNoIsNull() {
            addCriterion("PRDT_NO is null");
            return (Criteria) this;
        }

        public Criteria andPrdtNoIsNotNull() {
            addCriterion("PRDT_NO is not null");
            return (Criteria) this;
        }

        public Criteria andPrdtNoEqualTo(String value) {
            addCriterion("PRDT_NO =", value, "prdtNo");
            return (Criteria) this;
        }

        public Criteria andPrdtNoNotEqualTo(String value) {
            addCriterion("PRDT_NO <>", value, "prdtNo");
            return (Criteria) this;
        }

        public Criteria andPrdtNoGreaterThan(String value) {
            addCriterion("PRDT_NO >", value, "prdtNo");
            return (Criteria) this;
        }

        public Criteria andPrdtNoGreaterThanOrEqualTo(String value) {
            addCriterion("PRDT_NO >=", value, "prdtNo");
            return (Criteria) this;
        }

        public Criteria andPrdtNoLessThan(String value) {
            addCriterion("PRDT_NO <", value, "prdtNo");
            return (Criteria) this;
        }

        public Criteria andPrdtNoLessThanOrEqualTo(String value) {
            addCriterion("PRDT_NO <=", value, "prdtNo");
            return (Criteria) this;
        }

        public Criteria andPrdtNoLike(String value) {
            addCriterion("PRDT_NO like", value, "prdtNo");
            return (Criteria) this;
        }

        public Criteria andPrdtNoNotLike(String value) {
            addCriterion("PRDT_NO not like", value, "prdtNo");
            return (Criteria) this;
        }

        public Criteria andPrdtNoIn(List<String> values) {
            addCriterion("PRDT_NO in", values, "prdtNo");
            return (Criteria) this;
        }

        public Criteria andPrdtNoNotIn(List<String> values) {
            addCriterion("PRDT_NO not in", values, "prdtNo");
            return (Criteria) this;
        }

        public Criteria andPrdtNoBetween(String value1, String value2) {
            addCriterion("PRDT_NO between", value1, value2, "prdtNo");
            return (Criteria) this;
        }

        public Criteria andPrdtNoNotBetween(String value1, String value2) {
            addCriterion("PRDT_NO not between", value1, value2, "prdtNo");
            return (Criteria) this;
        }

        public Criteria andTxAmtIsNull() {
            addCriterion("TX_AMT is null");
            return (Criteria) this;
        }

        public Criteria andTxAmtIsNotNull() {
            addCriterion("TX_AMT is not null");
            return (Criteria) this;
        }

        public Criteria andTxAmtEqualTo(BigDecimal value) {
            addCriterion("TX_AMT =", value, "txAmt");
            return (Criteria) this;
        }

        public Criteria andTxAmtNotEqualTo(BigDecimal value) {
            addCriterion("TX_AMT <>", value, "txAmt");
            return (Criteria) this;
        }

        public Criteria andTxAmtGreaterThan(BigDecimal value) {
            addCriterion("TX_AMT >", value, "txAmt");
            return (Criteria) this;
        }

        public Criteria andTxAmtGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("TX_AMT >=", value, "txAmt");
            return (Criteria) this;
        }

        public Criteria andTxAmtLessThan(BigDecimal value) {
            addCriterion("TX_AMT <", value, "txAmt");
            return (Criteria) this;
        }

        public Criteria andTxAmtLessThanOrEqualTo(BigDecimal value) {
            addCriterion("TX_AMT <=", value, "txAmt");
            return (Criteria) this;
        }

        public Criteria andTxAmtIn(List<BigDecimal> values) {
            addCriterion("TX_AMT in", values, "txAmt");
            return (Criteria) this;
        }

        public Criteria andTxAmtNotIn(List<BigDecimal> values) {
            addCriterion("TX_AMT not in", values, "txAmt");
            return (Criteria) this;
        }

        public Criteria andTxAmtBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("TX_AMT between", value1, value2, "txAmt");
            return (Criteria) this;
        }

        public Criteria andTxAmtNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("TX_AMT not between", value1, value2, "txAmt");
            return (Criteria) this;
        }

        public Criteria andStsIsNull() {
            addCriterion("STS is null");
            return (Criteria) this;
        }

        public Criteria andStsIsNotNull() {
            addCriterion("STS is not null");
            return (Criteria) this;
        }

        public Criteria andStsEqualTo(String value) {
            addCriterion("STS =", value, "sts");
            return (Criteria) this;
        }

        public Criteria andStsNotEqualTo(String value) {
            addCriterion("STS <>", value, "sts");
            return (Criteria) this;
        }

        public Criteria andStsGreaterThan(String value) {
            addCriterion("STS >", value, "sts");
            return (Criteria) this;
        }

        public Criteria andStsGreaterThanOrEqualTo(String value) {
            addCriterion("STS >=", value, "sts");
            return (Criteria) this;
        }

        public Criteria andStsLessThan(String value) {
            addCriterion("STS <", value, "sts");
            return (Criteria) this;
        }

        public Criteria andStsLessThanOrEqualTo(String value) {
            addCriterion("STS <=", value, "sts");
            return (Criteria) this;
        }

        public Criteria andStsLike(String value) {
            addCriterion("STS like", value, "sts");
            return (Criteria) this;
        }

        public Criteria andStsNotLike(String value) {
            addCriterion("STS not like", value, "sts");
            return (Criteria) this;
        }

        public Criteria andStsIn(List<String> values) {
            addCriterion("STS in", values, "sts");
            return (Criteria) this;
        }

        public Criteria andStsNotIn(List<String> values) {
            addCriterion("STS not in", values, "sts");
            return (Criteria) this;
        }

        public Criteria andStsBetween(String value1, String value2) {
            addCriterion("STS between", value1, value2, "sts");
            return (Criteria) this;
        }

        public Criteria andStsNotBetween(String value1, String value2) {
            addCriterion("STS not between", value1, value2, "sts");
            return (Criteria) this;
        }

        public Criteria andHostStsIsNull() {
            addCriterion("HOST_STS is null");
            return (Criteria) this;
        }

        public Criteria andHostStsIsNotNull() {
            addCriterion("HOST_STS is not null");
            return (Criteria) this;
        }

        public Criteria andHostStsEqualTo(String value) {
            addCriterion("HOST_STS =", value, "hostSts");
            return (Criteria) this;
        }

        public Criteria andHostStsNotEqualTo(String value) {
            addCriterion("HOST_STS <>", value, "hostSts");
            return (Criteria) this;
        }

        public Criteria andHostStsGreaterThan(String value) {
            addCriterion("HOST_STS >", value, "hostSts");
            return (Criteria) this;
        }

        public Criteria andHostStsGreaterThanOrEqualTo(String value) {
            addCriterion("HOST_STS >=", value, "hostSts");
            return (Criteria) this;
        }

        public Criteria andHostStsLessThan(String value) {
            addCriterion("HOST_STS <", value, "hostSts");
            return (Criteria) this;
        }

        public Criteria andHostStsLessThanOrEqualTo(String value) {
            addCriterion("HOST_STS <=", value, "hostSts");
            return (Criteria) this;
        }

        public Criteria andHostStsLike(String value) {
            addCriterion("HOST_STS like", value, "hostSts");
            return (Criteria) this;
        }

        public Criteria andHostStsNotLike(String value) {
            addCriterion("HOST_STS not like", value, "hostSts");
            return (Criteria) this;
        }

        public Criteria andHostStsIn(List<String> values) {
            addCriterion("HOST_STS in", values, "hostSts");
            return (Criteria) this;
        }

        public Criteria andHostStsNotIn(List<String> values) {
            addCriterion("HOST_STS not in", values, "hostSts");
            return (Criteria) this;
        }

        public Criteria andHostStsBetween(String value1, String value2) {
            addCriterion("HOST_STS between", value1, value2, "hostSts");
            return (Criteria) this;
        }

        public Criteria andHostStsNotBetween(String value1, String value2) {
            addCriterion("HOST_STS not between", value1, value2, "hostSts");
            return (Criteria) this;
        }

        public Criteria andBrfIsNull() {
            addCriterion("BRF is null");
            return (Criteria) this;
        }

        public Criteria andBrfIsNotNull() {
            addCriterion("BRF is not null");
            return (Criteria) this;
        }

        public Criteria andBrfEqualTo(String value) {
            addCriterion("BRF =", value, "brf");
            return (Criteria) this;
        }

        public Criteria andBrfNotEqualTo(String value) {
            addCriterion("BRF <>", value, "brf");
            return (Criteria) this;
        }

        public Criteria andBrfGreaterThan(String value) {
            addCriterion("BRF >", value, "brf");
            return (Criteria) this;
        }

        public Criteria andBrfGreaterThanOrEqualTo(String value) {
            addCriterion("BRF >=", value, "brf");
            return (Criteria) this;
        }

        public Criteria andBrfLessThan(String value) {
            addCriterion("BRF <", value, "brf");
            return (Criteria) this;
        }

        public Criteria andBrfLessThanOrEqualTo(String value) {
            addCriterion("BRF <=", value, "brf");
            return (Criteria) this;
        }

        public Criteria andBrfLike(String value) {
            addCriterion("BRF like", value, "brf");
            return (Criteria) this;
        }

        public Criteria andBrfNotLike(String value) {
            addCriterion("BRF not like", value, "brf");
            return (Criteria) this;
        }

        public Criteria andBrfIn(List<String> values) {
            addCriterion("BRF in", values, "brf");
            return (Criteria) this;
        }

        public Criteria andBrfNotIn(List<String> values) {
            addCriterion("BRF not in", values, "brf");
            return (Criteria) this;
        }

        public Criteria andBrfBetween(String value1, String value2) {
            addCriterion("BRF between", value1, value2, "brf");
            return (Criteria) this;
        }

        public Criteria andBrfNotBetween(String value1, String value2) {
            addCriterion("BRF not between", value1, value2, "brf");
            return (Criteria) this;
        }

        public Criteria andTxBrNoIsNull() {
            addCriterion("TX_BR_NO is null");
            return (Criteria) this;
        }

        public Criteria andTxBrNoIsNotNull() {
            addCriterion("TX_BR_NO is not null");
            return (Criteria) this;
        }

        public Criteria andTxBrNoEqualTo(String value) {
            addCriterion("TX_BR_NO =", value, "txBrNo");
            return (Criteria) this;
        }

        public Criteria andTxBrNoNotEqualTo(String value) {
            addCriterion("TX_BR_NO <>", value, "txBrNo");
            return (Criteria) this;
        }

        public Criteria andTxBrNoGreaterThan(String value) {
            addCriterion("TX_BR_NO >", value, "txBrNo");
            return (Criteria) this;
        }

        public Criteria andTxBrNoGreaterThanOrEqualTo(String value) {
            addCriterion("TX_BR_NO >=", value, "txBrNo");
            return (Criteria) this;
        }

        public Criteria andTxBrNoLessThan(String value) {
            addCriterion("TX_BR_NO <", value, "txBrNo");
            return (Criteria) this;
        }

        public Criteria andTxBrNoLessThanOrEqualTo(String value) {
            addCriterion("TX_BR_NO <=", value, "txBrNo");
            return (Criteria) this;
        }

        public Criteria andTxBrNoLike(String value) {
            addCriterion("TX_BR_NO like", value, "txBrNo");
            return (Criteria) this;
        }

        public Criteria andTxBrNoNotLike(String value) {
            addCriterion("TX_BR_NO not like", value, "txBrNo");
            return (Criteria) this;
        }

        public Criteria andTxBrNoIn(List<String> values) {
            addCriterion("TX_BR_NO in", values, "txBrNo");
            return (Criteria) this;
        }

        public Criteria andTxBrNoNotIn(List<String> values) {
            addCriterion("TX_BR_NO not in", values, "txBrNo");
            return (Criteria) this;
        }

        public Criteria andTxBrNoBetween(String value1, String value2) {
            addCriterion("TX_BR_NO between", value1, value2, "txBrNo");
            return (Criteria) this;
        }

        public Criteria andTxBrNoNotBetween(String value1, String value2) {
            addCriterion("TX_BR_NO not between", value1, value2, "txBrNo");
            return (Criteria) this;
        }

        public Criteria andTxTelIsNull() {
            addCriterion("TX_TEL is null");
            return (Criteria) this;
        }

        public Criteria andTxTelIsNotNull() {
            addCriterion("TX_TEL is not null");
            return (Criteria) this;
        }

        public Criteria andTxTelEqualTo(String value) {
            addCriterion("TX_TEL =", value, "txTel");
            return (Criteria) this;
        }

        public Criteria andTxTelNotEqualTo(String value) {
            addCriterion("TX_TEL <>", value, "txTel");
            return (Criteria) this;
        }

        public Criteria andTxTelGreaterThan(String value) {
            addCriterion("TX_TEL >", value, "txTel");
            return (Criteria) this;
        }

        public Criteria andTxTelGreaterThanOrEqualTo(String value) {
            addCriterion("TX_TEL >=", value, "txTel");
            return (Criteria) this;
        }

        public Criteria andTxTelLessThan(String value) {
            addCriterion("TX_TEL <", value, "txTel");
            return (Criteria) this;
        }

        public Criteria andTxTelLessThanOrEqualTo(String value) {
            addCriterion("TX_TEL <=", value, "txTel");
            return (Criteria) this;
        }

        public Criteria andTxTelLike(String value) {
            addCriterion("TX_TEL like", value, "txTel");
            return (Criteria) this;
        }

        public Criteria andTxTelNotLike(String value) {
            addCriterion("TX_TEL not like", value, "txTel");
            return (Criteria) this;
        }

        public Criteria andTxTelIn(List<String> values) {
            addCriterion("TX_TEL in", values, "txTel");
            return (Criteria) this;
        }

        public Criteria andTxTelNotIn(List<String> values) {
            addCriterion("TX_TEL not in", values, "txTel");
            return (Criteria) this;
        }

        public Criteria andTxTelBetween(String value1, String value2) {
            addCriterion("TX_TEL between", value1, value2, "txTel");
            return (Criteria) this;
        }

        public Criteria andTxTelNotBetween(String value1, String value2) {
            addCriterion("TX_TEL not between", value1, value2, "txTel");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table CHPS.AG_FILE
     *
     * @mbggenerated do_not_delete_during_merge Wed Oct 19 16:02:52 CST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table CHPS.AG_FILE
     *
     * @mbggenerated Wed Oct 19 16:02:52 CST 2016
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}