package cn.koolyun.model;

import java.math.BigDecimal;
import java.util.Date;

public class GgptTxnInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INTER.GGPT_TXN_INFO.TXN_ID
     *
     * @mbggenerated Wed Oct 19 17:02:46 CST 2016
     */
    private BigDecimal txnId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INTER.GGPT_TXN_INFO.MCHT_CD
     *
     * @mbggenerated Wed Oct 19 17:02:46 CST 2016
     */
    private String mchtCd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INTER.GGPT_TXN_INFO.TERM_ID
     *
     * @mbggenerated Wed Oct 19 17:02:46 CST 2016
     */
    private String termId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INTER.GGPT_TXN_INFO.OPERATOR
     *
     * @mbggenerated Wed Oct 19 17:02:46 CST 2016
     */
    private String operator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INTER.GGPT_TXN_INFO.BATCH_NO
     *
     * @mbggenerated Wed Oct 19 17:02:46 CST 2016
     */
    private String batchNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INTER.GGPT_TXN_INFO.INST_DATE
     *
     * @mbggenerated Wed Oct 19 17:02:46 CST 2016
     */
    private String instDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INTER.GGPT_TXN_INFO.INST_TIME
     *
     * @mbggenerated Wed Oct 19 17:02:46 CST 2016
     */
    private String instTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INTER.GGPT_TXN_INFO.INST_TRACE
     *
     * @mbggenerated Wed Oct 19 17:02:46 CST 2016
     */
    private String instTrace;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INTER.GGPT_TXN_INFO.TXN_NUM
     *
     * @mbggenerated Wed Oct 19 17:02:46 CST 2016
     */
    private String txnNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INTER.GGPT_TXN_INFO.TXN_STAT
     *
     * @mbggenerated Wed Oct 19 17:02:46 CST 2016
     */
    private String txnStat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INTER.GGPT_TXN_INFO.AMOUNT
     *
     * @mbggenerated Wed Oct 19 17:02:46 CST 2016
     */
    private String amount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INTER.GGPT_TXN_INFO.QUANTITY
     *
     * @mbggenerated Wed Oct 19 17:02:46 CST 2016
     */
    private String quantity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INTER.GGPT_TXN_INFO.ISSUER_ID
     *
     * @mbggenerated Wed Oct 19 17:02:46 CST 2016
     */
    private String issuerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INTER.GGPT_TXN_INFO.CARD_NO
     *
     * @mbggenerated Wed Oct 19 17:02:46 CST 2016
     */
    private String cardNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INTER.GGPT_TXN_INFO.DATE_EXPR
     *
     * @mbggenerated Wed Oct 19 17:02:46 CST 2016
     */
    private String dateExpr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INTER.GGPT_TXN_INFO.STLM_DATE
     *
     * @mbggenerated Wed Oct 19 17:02:46 CST 2016
     */
    private String stlmDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INTER.GGPT_TXN_INFO.STLM_FEE
     *
     * @mbggenerated Wed Oct 19 17:02:46 CST 2016
     */
    private BigDecimal stlmFee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INTER.GGPT_TXN_INFO.REF_NO
     *
     * @mbggenerated Wed Oct 19 17:02:46 CST 2016
     */
    private String refNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INTER.GGPT_TXN_INFO.AUTH_NO
     *
     * @mbggenerated Wed Oct 19 17:02:46 CST 2016
     */
    private String authNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INTER.GGPT_TXN_INFO.PAY_ID
     *
     * @mbggenerated Wed Oct 19 17:02:46 CST 2016
     */
    private String payId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INTER.GGPT_TXN_INFO.PAY_BRH_ID
     *
     * @mbggenerated Wed Oct 19 17:02:46 CST 2016
     */
    private String payBrhId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INTER.GGPT_TXN_INFO.PAY_PROD_NO
     *
     * @mbggenerated Wed Oct 19 17:02:46 CST 2016
     */
    private String payProdNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INTER.GGPT_TXN_INFO.PAY_KEY_INDEX
     *
     * @mbggenerated Wed Oct 19 17:02:46 CST 2016
     */
    private String payKeyIndex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INTER.GGPT_TXN_INFO.CHNL_MCHT_CD
     *
     * @mbggenerated Wed Oct 19 17:02:46 CST 2016
     */
    private String chnlMchtCd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INTER.GGPT_TXN_INFO.CHNL_TERM_ID
     *
     * @mbggenerated Wed Oct 19 17:02:46 CST 2016
     */
    private String chnlTermId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INTER.GGPT_TXN_INFO.CHNL_REF_NO
     *
     * @mbggenerated Wed Oct 19 17:02:46 CST 2016
     */
    private String chnlRefNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INTER.GGPT_TXN_INFO.CHNL_BATCH_NO
     *
     * @mbggenerated Wed Oct 19 17:02:46 CST 2016
     */
    private String chnlBatchNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INTER.GGPT_TXN_INFO.CHNL_TRACE_NO
     *
     * @mbggenerated Wed Oct 19 17:02:46 CST 2016
     */
    private String chnlTraceNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INTER.GGPT_TXN_INFO.ORI_BATCH_NO
     *
     * @mbggenerated Wed Oct 19 17:02:46 CST 2016
     */
    private String oriBatchNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INTER.GGPT_TXN_INFO.ORI_INST_DATE
     *
     * @mbggenerated Wed Oct 19 17:02:46 CST 2016
     */
    private String oriInstDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INTER.GGPT_TXN_INFO.ORI_INST_TIME
     *
     * @mbggenerated Wed Oct 19 17:02:46 CST 2016
     */
    private String oriInstTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INTER.GGPT_TXN_INFO.ORI_INST_TRACE
     *
     * @mbggenerated Wed Oct 19 17:02:46 CST 2016
     */
    private String oriInstTrace;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INTER.GGPT_TXN_INFO.ORI_TXN_ID
     *
     * @mbggenerated Wed Oct 19 17:02:46 CST 2016
     */
    private BigDecimal oriTxnId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INTER.GGPT_TXN_INFO.RET_CODE
     *
     * @mbggenerated Wed Oct 19 17:02:46 CST 2016
     */
    private String retCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INTER.GGPT_TXN_INFO.RET_MSG
     *
     * @mbggenerated Wed Oct 19 17:02:46 CST 2016
     */
    private String retMsg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INTER.GGPT_TXN_INFO.RET_TIMESTAMP
     *
     * @mbggenerated Wed Oct 19 17:02:46 CST 2016
     */
    private Date retTimestamp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INTER.GGPT_TXN_INFO.RESP_MSG
     *
     * @mbggenerated Wed Oct 19 17:02:46 CST 2016
     */
    private String respMsg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INTER.GGPT_TXN_INFO.RESP_MSG_EXT
     *
     * @mbggenerated Wed Oct 19 17:02:46 CST 2016
     */
    private String respMsgExt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INTER.GGPT_TXN_INFO.CREATE_TIMESTAMP
     *
     * @mbggenerated Wed Oct 19 17:02:46 CST 2016
     */
    private Date createTimestamp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INTER.GGPT_TXN_INFO.UPDATE_TIMESTAMP
     *
     * @mbggenerated Wed Oct 19 17:02:46 CST 2016
     */
    private Date updateTimestamp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INTER.GGPT_TXN_INFO.TXN_INDEX
     *
     * @mbggenerated Wed Oct 19 17:02:46 CST 2016
     */
    private String txnIndex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INTER.GGPT_TXN_INFO.OD_APK
     *
     * @mbggenerated Wed Oct 19 17:02:46 CST 2016
     */
    private String odApk;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INTER.GGPT_TXN_INFO.OD_NO
     *
     * @mbggenerated Wed Oct 19 17:02:46 CST 2016
     */
    private String odNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INTER.GGPT_TXN_INFO.OD_DESC
     *
     * @mbggenerated Wed Oct 19 17:02:46 CST 2016
     */
    private String odDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INTER.GGPT_TXN_INFO.AMT_FEE
     *
     * @mbggenerated Wed Oct 19 17:02:46 CST 2016
     */
    private String amtFee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INTER.GGPT_TXN_INFO.AMT_PROFIT
     *
     * @mbggenerated Wed Oct 19 17:02:46 CST 2016
     */
    private String amtProfit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INTER.GGPT_TXN_INFO.AMT_FLAG
     *
     * @mbggenerated Wed Oct 19 17:02:46 CST 2016
     */
    private String amtFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INTER.GGPT_TXN_INFO.FML_FEE
     *
     * @mbggenerated Wed Oct 19 17:02:46 CST 2016
     */
    private String fmlFee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INTER.GGPT_TXN_INFO.FML_PROFIT
     *
     * @mbggenerated Wed Oct 19 17:02:46 CST 2016
     */
    private String fmlProfit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INTER.GGPT_TXN_INFO.STAT
     *
     * @mbggenerated Wed Oct 19 17:02:46 CST 2016
     */
    private String stat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INTER.GGPT_TXN_INFO.CURRENCY
     *
     * @mbggenerated Wed Oct 19 17:02:46 CST 2016
     */
    private String currency;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INTER.GGPT_TXN_INFO.OP_ACCT_NAME
     *
     * @mbggenerated Wed Oct 19 17:02:46 CST 2016
     */
    private String opAcctName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INTER.GGPT_TXN_INFO.OP_ACCT_NO
     *
     * @mbggenerated Wed Oct 19 17:02:46 CST 2016
     */
    private String opAcctNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INTER.GGPT_TXN_INFO.OP_IDCARD_TYPE
     *
     * @mbggenerated Wed Oct 19 17:02:46 CST 2016
     */
    private String opIdcardType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INTER.GGPT_TXN_INFO.OP_IDCARD_NO
     *
     * @mbggenerated Wed Oct 19 17:02:46 CST 2016
     */
    private String opIdcardNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INTER.GGPT_TXN_INFO.POINTS_EXCHANGE
     *
     * @mbggenerated Wed Oct 19 17:02:46 CST 2016
     */
    private String pointsExchange;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INTER.GGPT_TXN_INFO.POINTS_LEFT
     *
     * @mbggenerated Wed Oct 19 17:02:46 CST 2016
     */
    private String pointsLeft;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INTER.GGPT_TXN_INFO.ORIG_TRANS_AMOUNT
     *
     * @mbggenerated Wed Oct 19 17:02:46 CST 2016
     */
    private String origTransAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INTER.GGPT_TXN_INFO.ACTU_TRANS_AMOUNT
     *
     * @mbggenerated Wed Oct 19 17:02:46 CST 2016
     */
    private String actuTransAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INTER.GGPT_TXN_INFO.OD_TYPE
     *
     * @mbggenerated Wed Oct 19 17:02:46 CST 2016
     */
    private String odType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INTER.GGPT_TXN_INFO.CARD_TYPE
     *
     * @mbggenerated Wed Oct 19 17:02:46 CST 2016
     */
    private String cardType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INTER.GGPT_TXN_INFO.REFUND_AMOUNT
     *
     * @mbggenerated Wed Oct 19 17:02:46 CST 2016
     */
    private String refundAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INTER.GGPT_TXN_INFO.EXCHANGE_RATE
     *
     * @mbggenerated Wed Oct 19 17:02:46 CST 2016
     */
    private String exchangeRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INTER.GGPT_TXN_INFO.CNY_AMOUNT
     *
     * @mbggenerated Wed Oct 19 17:02:46 CST 2016
     */
    private String cnyAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INTER.GGPT_TXN_INFO.ISSUER_NAME
     *
     * @mbggenerated Wed Oct 19 17:02:46 CST 2016
     */
    private String issuerName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INTER.GGPT_TXN_INFO.ACQUIRER_ID
     *
     * @mbggenerated Wed Oct 19 17:02:46 CST 2016
     */
    private String acquirerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INTER.GGPT_TXN_INFO.ACQUIRER_NAME
     *
     * @mbggenerated Wed Oct 19 17:02:46 CST 2016
     */
    private String acquirerName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INTER.GGPT_TXN_INFO.CHNL_OD_DESC
     *
     * @mbggenerated Wed Oct 19 17:02:46 CST 2016
     */
    private String chnlOdDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INTER.GGPT_TXN_INFO.CNL_TRANS_AMT
     *
     * @mbggenerated Wed Oct 19 17:02:46 CST 2016
     */
    private String cnlTransAmt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INTER.GGPT_TXN_INFO.CNL_TRANS_CUR
     *
     * @mbggenerated Wed Oct 19 17:02:46 CST 2016
     */
    private String cnlTransCur;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INTER.GGPT_TXN_INFO.DCC_FLAG
     *
     * @mbggenerated Wed Oct 19 17:02:46 CST 2016
     */
    private String dccFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INTER.GGPT_TXN_INFO.DCC_EX_RATE
     *
     * @mbggenerated Wed Oct 19 17:02:46 CST 2016
     */
    private String dccExRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INTER.GGPT_TXN_INFO.NOTIFY_URL
     *
     * @mbggenerated Wed Oct 19 17:02:46 CST 2016
     */
    private String notifyUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INTER.GGPT_TXN_INFO.IS_SEND
     *
     * @mbggenerated Wed Oct 19 17:02:46 CST 2016
     */
    private String isSend;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INTER.GGPT_TXN_INFO.MM_MEMBER_ID
     *
     * @mbggenerated Wed Oct 19 17:02:46 CST 2016
     */
    private String mmMemberId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INTER.GGPT_TXN_INFO.WAY_OF_CARD
     *
     * @mbggenerated Wed Oct 19 17:02:46 CST 2016
     */
    private String wayOfCard;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INTER.GGPT_TXN_INFO.TXN_ID
     *
     * @return the value of INTER.GGPT_TXN_INFO.TXN_ID
     *
     * @mbggenerated Wed Oct 19 17:02:46 CST 2016
     */
    public BigDecimal getTxnId() {
        return txnId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INTER.GGPT_TXN_INFO.TXN_ID
     *
     * @param txnId the value for INTER.GGPT_TXN_INFO.TXN_ID
     *
     * @mbggenerated Wed Oct 19 17:02:46 CST 2016
     */
    public void setTxnId(BigDecimal txnId) {
        this.txnId = txnId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INTER.GGPT_TXN_INFO.MCHT_CD
     *
     * @return the value of INTER.GGPT_TXN_INFO.MCHT_CD
     *
     * @mbggenerated Wed Oct 19 17:02:46 CST 2016
     */
    public String getMchtCd() {
        return mchtCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INTER.GGPT_TXN_INFO.MCHT_CD
     *
     * @param mchtCd the value for INTER.GGPT_TXN_INFO.MCHT_CD
     *
     * @mbggenerated Wed Oct 19 17:02:46 CST 2016
     */
    public void setMchtCd(String mchtCd) {
        this.mchtCd = mchtCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INTER.GGPT_TXN_INFO.TERM_ID
     *
     * @return the value of INTER.GGPT_TXN_INFO.TERM_ID
     *
     * @mbggenerated Wed Oct 19 17:02:46 CST 2016
     */
    public String getTermId() {
        return termId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INTER.GGPT_TXN_INFO.TERM_ID
     *
     * @param termId the value for INTER.GGPT_TXN_INFO.TERM_ID
     *
     * @mbggenerated Wed Oct 19 17:02:46 CST 2016
     */
    public void setTermId(String termId) {
        this.termId = termId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INTER.GGPT_TXN_INFO.OPERATOR
     *
     * @return the value of INTER.GGPT_TXN_INFO.OPERATOR
     *
     * @mbggenerated Wed Oct 19 17:02:46 CST 2016
     */
    public String getOperator() {
        return operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INTER.GGPT_TXN_INFO.OPERATOR
     *
     * @param operator the value for INTER.GGPT_TXN_INFO.OPERATOR
     *
     * @mbggenerated Wed Oct 19 17:02:46 CST 2016
     */
    public void setOperator(String operator) {
        this.operator = operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INTER.GGPT_TXN_INFO.BATCH_NO
     *
     * @return the value of INTER.GGPT_TXN_INFO.BATCH_NO
     *
     * @mbggenerated Wed Oct 19 17:02:46 CST 2016
     */
    public String getBatchNo() {
        return batchNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INTER.GGPT_TXN_INFO.BATCH_NO
     *
     * @param batchNo the value for INTER.GGPT_TXN_INFO.BATCH_NO
     *
     * @mbggenerated Wed Oct 19 17:02:46 CST 2016
     */
    public void setBatchNo(String batchNo) {
        this.batchNo = batchNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INTER.GGPT_TXN_INFO.INST_DATE
     *
     * @return the value of INTER.GGPT_TXN_INFO.INST_DATE
     *
     * @mbggenerated Wed Oct 19 17:02:46 CST 2016
     */
    public String getInstDate() {
        return instDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INTER.GGPT_TXN_INFO.INST_DATE
     *
     * @param instDate the value for INTER.GGPT_TXN_INFO.INST_DATE
     *
     * @mbggenerated Wed Oct 19 17:02:46 CST 2016
     */
    public void setInstDate(String instDate) {
        this.instDate = instDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INTER.GGPT_TXN_INFO.INST_TIME
     *
     * @return the value of INTER.GGPT_TXN_INFO.INST_TIME
     *
     * @mbggenerated Wed Oct 19 17:02:46 CST 2016
     */
    public String getInstTime() {
        return instTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INTER.GGPT_TXN_INFO.INST_TIME
     *
     * @param instTime the value for INTER.GGPT_TXN_INFO.INST_TIME
     *
     * @mbggenerated Wed Oct 19 17:02:46 CST 2016
     */
    public void setInstTime(String instTime) {
        this.instTime = instTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INTER.GGPT_TXN_INFO.INST_TRACE
     *
     * @return the value of INTER.GGPT_TXN_INFO.INST_TRACE
     *
     * @mbggenerated Wed Oct 19 17:02:46 CST 2016
     */
    public String getInstTrace() {
        return instTrace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INTER.GGPT_TXN_INFO.INST_TRACE
     *
     * @param instTrace the value for INTER.GGPT_TXN_INFO.INST_TRACE
     *
     * @mbggenerated Wed Oct 19 17:02:46 CST 2016
     */
    public void setInstTrace(String instTrace) {
        this.instTrace = instTrace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INTER.GGPT_TXN_INFO.TXN_NUM
     *
     * @return the value of INTER.GGPT_TXN_INFO.TXN_NUM
     *
     * @mbggenerated Wed Oct 19 17:02:46 CST 2016
     */
    public String getTxnNum() {
        return txnNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INTER.GGPT_TXN_INFO.TXN_NUM
     *
     * @param txnNum the value for INTER.GGPT_TXN_INFO.TXN_NUM
     *
     * @mbggenerated Wed Oct 19 17:02:46 CST 2016
     */
    public void setTxnNum(String txnNum) {
        this.txnNum = txnNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INTER.GGPT_TXN_INFO.TXN_STAT
     *
     * @return the value of INTER.GGPT_TXN_INFO.TXN_STAT
     *
     * @mbggenerated Wed Oct 19 17:02:46 CST 2016
     */
    public String getTxnStat() {
        return txnStat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INTER.GGPT_TXN_INFO.TXN_STAT
     *
     * @param txnStat the value for INTER.GGPT_TXN_INFO.TXN_STAT
     *
     * @mbggenerated Wed Oct 19 17:02:46 CST 2016
     */
    public void setTxnStat(String txnStat) {
        this.txnStat = txnStat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INTER.GGPT_TXN_INFO.AMOUNT
     *
     * @return the value of INTER.GGPT_TXN_INFO.AMOUNT
     *
     * @mbggenerated Wed Oct 19 17:02:46 CST 2016
     */
    public String getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INTER.GGPT_TXN_INFO.AMOUNT
     *
     * @param amount the value for INTER.GGPT_TXN_INFO.AMOUNT
     *
     * @mbggenerated Wed Oct 19 17:02:46 CST 2016
     */
    public void setAmount(String amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INTER.GGPT_TXN_INFO.QUANTITY
     *
     * @return the value of INTER.GGPT_TXN_INFO.QUANTITY
     *
     * @mbggenerated Wed Oct 19 17:02:46 CST 2016
     */
    public String getQuantity() {
        return quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INTER.GGPT_TXN_INFO.QUANTITY
     *
     * @param quantity the value for INTER.GGPT_TXN_INFO.QUANTITY
     *
     * @mbggenerated Wed Oct 19 17:02:46 CST 2016
     */
    public void setQuantity(String quantity) {
        this.quantity = quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INTER.GGPT_TXN_INFO.ISSUER_ID
     *
     * @return the value of INTER.GGPT_TXN_INFO.ISSUER_ID
     *
     * @mbggenerated Wed Oct 19 17:02:46 CST 2016
     */
    public String getIssuerId() {
        return issuerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INTER.GGPT_TXN_INFO.ISSUER_ID
     *
     * @param issuerId the value for INTER.GGPT_TXN_INFO.ISSUER_ID
     *
     * @mbggenerated Wed Oct 19 17:02:46 CST 2016
     */
    public void setIssuerId(String issuerId) {
        this.issuerId = issuerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INTER.GGPT_TXN_INFO.CARD_NO
     *
     * @return the value of INTER.GGPT_TXN_INFO.CARD_NO
     *
     * @mbggenerated Wed Oct 19 17:02:46 CST 2016
     */
    public String getCardNo() {
        return cardNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INTER.GGPT_TXN_INFO.CARD_NO
     *
     * @param cardNo the value for INTER.GGPT_TXN_INFO.CARD_NO
     *
     * @mbggenerated Wed Oct 19 17:02:46 CST 2016
     */
    public void setCardNo(String cardNo) {
        this.cardNo = cardNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INTER.GGPT_TXN_INFO.DATE_EXPR
     *
     * @return the value of INTER.GGPT_TXN_INFO.DATE_EXPR
     *
     * @mbggenerated Wed Oct 19 17:02:46 CST 2016
     */
    public String getDateExpr() {
        return dateExpr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INTER.GGPT_TXN_INFO.DATE_EXPR
     *
     * @param dateExpr the value for INTER.GGPT_TXN_INFO.DATE_EXPR
     *
     * @mbggenerated Wed Oct 19 17:02:46 CST 2016
     */
    public void setDateExpr(String dateExpr) {
        this.dateExpr = dateExpr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INTER.GGPT_TXN_INFO.STLM_DATE
     *
     * @return the value of INTER.GGPT_TXN_INFO.STLM_DATE
     *
     * @mbggenerated Wed Oct 19 17:02:46 CST 2016
     */
    public String getStlmDate() {
        return stlmDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INTER.GGPT_TXN_INFO.STLM_DATE
     *
     * @param stlmDate the value for INTER.GGPT_TXN_INFO.STLM_DATE
     *
     * @mbggenerated Wed Oct 19 17:02:46 CST 2016
     */
    public void setStlmDate(String stlmDate) {
        this.stlmDate = stlmDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INTER.GGPT_TXN_INFO.STLM_FEE
     *
     * @return the value of INTER.GGPT_TXN_INFO.STLM_FEE
     *
     * @mbggenerated Wed Oct 19 17:02:46 CST 2016
     */
    public BigDecimal getStlmFee() {
        return stlmFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INTER.GGPT_TXN_INFO.STLM_FEE
     *
     * @param stlmFee the value for INTER.GGPT_TXN_INFO.STLM_FEE
     *
     * @mbggenerated Wed Oct 19 17:02:46 CST 2016
     */
    public void setStlmFee(BigDecimal stlmFee) {
        this.stlmFee = stlmFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INTER.GGPT_TXN_INFO.REF_NO
     *
     * @return the value of INTER.GGPT_TXN_INFO.REF_NO
     *
     * @mbggenerated Wed Oct 19 17:02:46 CST 2016
     */
    public String getRefNo() {
        return refNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INTER.GGPT_TXN_INFO.REF_NO
     *
     * @param refNo the value for INTER.GGPT_TXN_INFO.REF_NO
     *
     * @mbggenerated Wed Oct 19 17:02:46 CST 2016
     */
    public void setRefNo(String refNo) {
        this.refNo = refNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INTER.GGPT_TXN_INFO.AUTH_NO
     *
     * @return the value of INTER.GGPT_TXN_INFO.AUTH_NO
     *
     * @mbggenerated Wed Oct 19 17:02:46 CST 2016
     */
    public String getAuthNo() {
        return authNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INTER.GGPT_TXN_INFO.AUTH_NO
     *
     * @param authNo the value for INTER.GGPT_TXN_INFO.AUTH_NO
     *
     * @mbggenerated Wed Oct 19 17:02:46 CST 2016
     */
    public void setAuthNo(String authNo) {
        this.authNo = authNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INTER.GGPT_TXN_INFO.PAY_ID
     *
     * @return the value of INTER.GGPT_TXN_INFO.PAY_ID
     *
     * @mbggenerated Wed Oct 19 17:02:46 CST 2016
     */
    public String getPayId() {
        return payId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INTER.GGPT_TXN_INFO.PAY_ID
     *
     * @param payId the value for INTER.GGPT_TXN_INFO.PAY_ID
     *
     * @mbggenerated Wed Oct 19 17:02:46 CST 2016
     */
    public void setPayId(String payId) {
        this.payId = payId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INTER.GGPT_TXN_INFO.PAY_BRH_ID
     *
     * @return the value of INTER.GGPT_TXN_INFO.PAY_BRH_ID
     *
     * @mbggenerated Wed Oct 19 17:02:46 CST 2016
     */
    public String getPayBrhId() {
        return payBrhId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INTER.GGPT_TXN_INFO.PAY_BRH_ID
     *
     * @param payBrhId the value for INTER.GGPT_TXN_INFO.PAY_BRH_ID
     *
     * @mbggenerated Wed Oct 19 17:02:46 CST 2016
     */
    public void setPayBrhId(String payBrhId) {
        this.payBrhId = payBrhId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INTER.GGPT_TXN_INFO.PAY_PROD_NO
     *
     * @return the value of INTER.GGPT_TXN_INFO.PAY_PROD_NO
     *
     * @mbggenerated Wed Oct 19 17:02:46 CST 2016
     */
    public String getPayProdNo() {
        return payProdNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INTER.GGPT_TXN_INFO.PAY_PROD_NO
     *
     * @param payProdNo the value for INTER.GGPT_TXN_INFO.PAY_PROD_NO
     *
     * @mbggenerated Wed Oct 19 17:02:46 CST 2016
     */
    public void setPayProdNo(String payProdNo) {
        this.payProdNo = payProdNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INTER.GGPT_TXN_INFO.PAY_KEY_INDEX
     *
     * @return the value of INTER.GGPT_TXN_INFO.PAY_KEY_INDEX
     *
     * @mbggenerated Wed Oct 19 17:02:46 CST 2016
     */
    public String getPayKeyIndex() {
        return payKeyIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INTER.GGPT_TXN_INFO.PAY_KEY_INDEX
     *
     * @param payKeyIndex the value for INTER.GGPT_TXN_INFO.PAY_KEY_INDEX
     *
     * @mbggenerated Wed Oct 19 17:02:46 CST 2016
     */
    public void setPayKeyIndex(String payKeyIndex) {
        this.payKeyIndex = payKeyIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INTER.GGPT_TXN_INFO.CHNL_MCHT_CD
     *
     * @return the value of INTER.GGPT_TXN_INFO.CHNL_MCHT_CD
     *
     * @mbggenerated Wed Oct 19 17:02:46 CST 2016
     */
    public String getChnlMchtCd() {
        return chnlMchtCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INTER.GGPT_TXN_INFO.CHNL_MCHT_CD
     *
     * @param chnlMchtCd the value for INTER.GGPT_TXN_INFO.CHNL_MCHT_CD
     *
     * @mbggenerated Wed Oct 19 17:02:46 CST 2016
     */
    public void setChnlMchtCd(String chnlMchtCd) {
        this.chnlMchtCd = chnlMchtCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INTER.GGPT_TXN_INFO.CHNL_TERM_ID
     *
     * @return the value of INTER.GGPT_TXN_INFO.CHNL_TERM_ID
     *
     * @mbggenerated Wed Oct 19 17:02:46 CST 2016
     */
    public String getChnlTermId() {
        return chnlTermId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INTER.GGPT_TXN_INFO.CHNL_TERM_ID
     *
     * @param chnlTermId the value for INTER.GGPT_TXN_INFO.CHNL_TERM_ID
     *
     * @mbggenerated Wed Oct 19 17:02:46 CST 2016
     */
    public void setChnlTermId(String chnlTermId) {
        this.chnlTermId = chnlTermId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INTER.GGPT_TXN_INFO.CHNL_REF_NO
     *
     * @return the value of INTER.GGPT_TXN_INFO.CHNL_REF_NO
     *
     * @mbggenerated Wed Oct 19 17:02:46 CST 2016
     */
    public String getChnlRefNo() {
        return chnlRefNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INTER.GGPT_TXN_INFO.CHNL_REF_NO
     *
     * @param chnlRefNo the value for INTER.GGPT_TXN_INFO.CHNL_REF_NO
     *
     * @mbggenerated Wed Oct 19 17:02:46 CST 2016
     */
    public void setChnlRefNo(String chnlRefNo) {
        this.chnlRefNo = chnlRefNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INTER.GGPT_TXN_INFO.CHNL_BATCH_NO
     *
     * @return the value of INTER.GGPT_TXN_INFO.CHNL_BATCH_NO
     *
     * @mbggenerated Wed Oct 19 17:02:46 CST 2016
     */
    public String getChnlBatchNo() {
        return chnlBatchNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INTER.GGPT_TXN_INFO.CHNL_BATCH_NO
     *
     * @param chnlBatchNo the value for INTER.GGPT_TXN_INFO.CHNL_BATCH_NO
     *
     * @mbggenerated Wed Oct 19 17:02:46 CST 2016
     */
    public void setChnlBatchNo(String chnlBatchNo) {
        this.chnlBatchNo = chnlBatchNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INTER.GGPT_TXN_INFO.CHNL_TRACE_NO
     *
     * @return the value of INTER.GGPT_TXN_INFO.CHNL_TRACE_NO
     *
     * @mbggenerated Wed Oct 19 17:02:46 CST 2016
     */
    public String getChnlTraceNo() {
        return chnlTraceNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INTER.GGPT_TXN_INFO.CHNL_TRACE_NO
     *
     * @param chnlTraceNo the value for INTER.GGPT_TXN_INFO.CHNL_TRACE_NO
     *
     * @mbggenerated Wed Oct 19 17:02:46 CST 2016
     */
    public void setChnlTraceNo(String chnlTraceNo) {
        this.chnlTraceNo = chnlTraceNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INTER.GGPT_TXN_INFO.ORI_BATCH_NO
     *
     * @return the value of INTER.GGPT_TXN_INFO.ORI_BATCH_NO
     *
     * @mbggenerated Wed Oct 19 17:02:46 CST 2016
     */
    public String getOriBatchNo() {
        return oriBatchNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INTER.GGPT_TXN_INFO.ORI_BATCH_NO
     *
     * @param oriBatchNo the value for INTER.GGPT_TXN_INFO.ORI_BATCH_NO
     *
     * @mbggenerated Wed Oct 19 17:02:46 CST 2016
     */
    public void setOriBatchNo(String oriBatchNo) {
        this.oriBatchNo = oriBatchNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INTER.GGPT_TXN_INFO.ORI_INST_DATE
     *
     * @return the value of INTER.GGPT_TXN_INFO.ORI_INST_DATE
     *
     * @mbggenerated Wed Oct 19 17:02:46 CST 2016
     */
    public String getOriInstDate() {
        return oriInstDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INTER.GGPT_TXN_INFO.ORI_INST_DATE
     *
     * @param oriInstDate the value for INTER.GGPT_TXN_INFO.ORI_INST_DATE
     *
     * @mbggenerated Wed Oct 19 17:02:46 CST 2016
     */
    public void setOriInstDate(String oriInstDate) {
        this.oriInstDate = oriInstDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INTER.GGPT_TXN_INFO.ORI_INST_TIME
     *
     * @return the value of INTER.GGPT_TXN_INFO.ORI_INST_TIME
     *
     * @mbggenerated Wed Oct 19 17:02:46 CST 2016
     */
    public String getOriInstTime() {
        return oriInstTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INTER.GGPT_TXN_INFO.ORI_INST_TIME
     *
     * @param oriInstTime the value for INTER.GGPT_TXN_INFO.ORI_INST_TIME
     *
     * @mbggenerated Wed Oct 19 17:02:46 CST 2016
     */
    public void setOriInstTime(String oriInstTime) {
        this.oriInstTime = oriInstTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INTER.GGPT_TXN_INFO.ORI_INST_TRACE
     *
     * @return the value of INTER.GGPT_TXN_INFO.ORI_INST_TRACE
     *
     * @mbggenerated Wed Oct 19 17:02:46 CST 2016
     */
    public String getOriInstTrace() {
        return oriInstTrace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INTER.GGPT_TXN_INFO.ORI_INST_TRACE
     *
     * @param oriInstTrace the value for INTER.GGPT_TXN_INFO.ORI_INST_TRACE
     *
     * @mbggenerated Wed Oct 19 17:02:46 CST 2016
     */
    public void setOriInstTrace(String oriInstTrace) {
        this.oriInstTrace = oriInstTrace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INTER.GGPT_TXN_INFO.ORI_TXN_ID
     *
     * @return the value of INTER.GGPT_TXN_INFO.ORI_TXN_ID
     *
     * @mbggenerated Wed Oct 19 17:02:46 CST 2016
     */
    public BigDecimal getOriTxnId() {
        return oriTxnId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INTER.GGPT_TXN_INFO.ORI_TXN_ID
     *
     * @param oriTxnId the value for INTER.GGPT_TXN_INFO.ORI_TXN_ID
     *
     * @mbggenerated Wed Oct 19 17:02:46 CST 2016
     */
    public void setOriTxnId(BigDecimal oriTxnId) {
        this.oriTxnId = oriTxnId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INTER.GGPT_TXN_INFO.RET_CODE
     *
     * @return the value of INTER.GGPT_TXN_INFO.RET_CODE
     *
     * @mbggenerated Wed Oct 19 17:02:46 CST 2016
     */
    public String getRetCode() {
        return retCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INTER.GGPT_TXN_INFO.RET_CODE
     *
     * @param retCode the value for INTER.GGPT_TXN_INFO.RET_CODE
     *
     * @mbggenerated Wed Oct 19 17:02:46 CST 2016
     */
    public void setRetCode(String retCode) {
        this.retCode = retCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INTER.GGPT_TXN_INFO.RET_MSG
     *
     * @return the value of INTER.GGPT_TXN_INFO.RET_MSG
     *
     * @mbggenerated Wed Oct 19 17:02:46 CST 2016
     */
    public String getRetMsg() {
        return retMsg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INTER.GGPT_TXN_INFO.RET_MSG
     *
     * @param retMsg the value for INTER.GGPT_TXN_INFO.RET_MSG
     *
     * @mbggenerated Wed Oct 19 17:02:46 CST 2016
     */
    public void setRetMsg(String retMsg) {
        this.retMsg = retMsg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INTER.GGPT_TXN_INFO.RET_TIMESTAMP
     *
     * @return the value of INTER.GGPT_TXN_INFO.RET_TIMESTAMP
     *
     * @mbggenerated Wed Oct 19 17:02:46 CST 2016
     */
    public Date getRetTimestamp() {
        return retTimestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INTER.GGPT_TXN_INFO.RET_TIMESTAMP
     *
     * @param retTimestamp the value for INTER.GGPT_TXN_INFO.RET_TIMESTAMP
     *
     * @mbggenerated Wed Oct 19 17:02:46 CST 2016
     */
    public void setRetTimestamp(Date retTimestamp) {
        this.retTimestamp = retTimestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INTER.GGPT_TXN_INFO.RESP_MSG
     *
     * @return the value of INTER.GGPT_TXN_INFO.RESP_MSG
     *
     * @mbggenerated Wed Oct 19 17:02:46 CST 2016
     */
    public String getRespMsg() {
        return respMsg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INTER.GGPT_TXN_INFO.RESP_MSG
     *
     * @param respMsg the value for INTER.GGPT_TXN_INFO.RESP_MSG
     *
     * @mbggenerated Wed Oct 19 17:02:46 CST 2016
     */
    public void setRespMsg(String respMsg) {
        this.respMsg = respMsg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INTER.GGPT_TXN_INFO.RESP_MSG_EXT
     *
     * @return the value of INTER.GGPT_TXN_INFO.RESP_MSG_EXT
     *
     * @mbggenerated Wed Oct 19 17:02:46 CST 2016
     */
    public String getRespMsgExt() {
        return respMsgExt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INTER.GGPT_TXN_INFO.RESP_MSG_EXT
     *
     * @param respMsgExt the value for INTER.GGPT_TXN_INFO.RESP_MSG_EXT
     *
     * @mbggenerated Wed Oct 19 17:02:46 CST 2016
     */
    public void setRespMsgExt(String respMsgExt) {
        this.respMsgExt = respMsgExt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INTER.GGPT_TXN_INFO.CREATE_TIMESTAMP
     *
     * @return the value of INTER.GGPT_TXN_INFO.CREATE_TIMESTAMP
     *
     * @mbggenerated Wed Oct 19 17:02:46 CST 2016
     */
    public Date getCreateTimestamp() {
        return createTimestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INTER.GGPT_TXN_INFO.CREATE_TIMESTAMP
     *
     * @param createTimestamp the value for INTER.GGPT_TXN_INFO.CREATE_TIMESTAMP
     *
     * @mbggenerated Wed Oct 19 17:02:46 CST 2016
     */
    public void setCreateTimestamp(Date createTimestamp) {
        this.createTimestamp = createTimestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INTER.GGPT_TXN_INFO.UPDATE_TIMESTAMP
     *
     * @return the value of INTER.GGPT_TXN_INFO.UPDATE_TIMESTAMP
     *
     * @mbggenerated Wed Oct 19 17:02:46 CST 2016
     */
    public Date getUpdateTimestamp() {
        return updateTimestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INTER.GGPT_TXN_INFO.UPDATE_TIMESTAMP
     *
     * @param updateTimestamp the value for INTER.GGPT_TXN_INFO.UPDATE_TIMESTAMP
     *
     * @mbggenerated Wed Oct 19 17:02:46 CST 2016
     */
    public void setUpdateTimestamp(Date updateTimestamp) {
        this.updateTimestamp = updateTimestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INTER.GGPT_TXN_INFO.TXN_INDEX
     *
     * @return the value of INTER.GGPT_TXN_INFO.TXN_INDEX
     *
     * @mbggenerated Wed Oct 19 17:02:46 CST 2016
     */
    public String getTxnIndex() {
        return txnIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INTER.GGPT_TXN_INFO.TXN_INDEX
     *
     * @param txnIndex the value for INTER.GGPT_TXN_INFO.TXN_INDEX
     *
     * @mbggenerated Wed Oct 19 17:02:46 CST 2016
     */
    public void setTxnIndex(String txnIndex) {
        this.txnIndex = txnIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INTER.GGPT_TXN_INFO.OD_APK
     *
     * @return the value of INTER.GGPT_TXN_INFO.OD_APK
     *
     * @mbggenerated Wed Oct 19 17:02:46 CST 2016
     */
    public String getOdApk() {
        return odApk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INTER.GGPT_TXN_INFO.OD_APK
     *
     * @param odApk the value for INTER.GGPT_TXN_INFO.OD_APK
     *
     * @mbggenerated Wed Oct 19 17:02:46 CST 2016
     */
    public void setOdApk(String odApk) {
        this.odApk = odApk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INTER.GGPT_TXN_INFO.OD_NO
     *
     * @return the value of INTER.GGPT_TXN_INFO.OD_NO
     *
     * @mbggenerated Wed Oct 19 17:02:46 CST 2016
     */
    public String getOdNo() {
        return odNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INTER.GGPT_TXN_INFO.OD_NO
     *
     * @param odNo the value for INTER.GGPT_TXN_INFO.OD_NO
     *
     * @mbggenerated Wed Oct 19 17:02:46 CST 2016
     */
    public void setOdNo(String odNo) {
        this.odNo = odNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INTER.GGPT_TXN_INFO.OD_DESC
     *
     * @return the value of INTER.GGPT_TXN_INFO.OD_DESC
     *
     * @mbggenerated Wed Oct 19 17:02:46 CST 2016
     */
    public String getOdDesc() {
        return odDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INTER.GGPT_TXN_INFO.OD_DESC
     *
     * @param odDesc the value for INTER.GGPT_TXN_INFO.OD_DESC
     *
     * @mbggenerated Wed Oct 19 17:02:46 CST 2016
     */
    public void setOdDesc(String odDesc) {
        this.odDesc = odDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INTER.GGPT_TXN_INFO.AMT_FEE
     *
     * @return the value of INTER.GGPT_TXN_INFO.AMT_FEE
     *
     * @mbggenerated Wed Oct 19 17:02:46 CST 2016
     */
    public String getAmtFee() {
        return amtFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INTER.GGPT_TXN_INFO.AMT_FEE
     *
     * @param amtFee the value for INTER.GGPT_TXN_INFO.AMT_FEE
     *
     * @mbggenerated Wed Oct 19 17:02:46 CST 2016
     */
    public void setAmtFee(String amtFee) {
        this.amtFee = amtFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INTER.GGPT_TXN_INFO.AMT_PROFIT
     *
     * @return the value of INTER.GGPT_TXN_INFO.AMT_PROFIT
     *
     * @mbggenerated Wed Oct 19 17:02:46 CST 2016
     */
    public String getAmtProfit() {
        return amtProfit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INTER.GGPT_TXN_INFO.AMT_PROFIT
     *
     * @param amtProfit the value for INTER.GGPT_TXN_INFO.AMT_PROFIT
     *
     * @mbggenerated Wed Oct 19 17:02:46 CST 2016
     */
    public void setAmtProfit(String amtProfit) {
        this.amtProfit = amtProfit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INTER.GGPT_TXN_INFO.AMT_FLAG
     *
     * @return the value of INTER.GGPT_TXN_INFO.AMT_FLAG
     *
     * @mbggenerated Wed Oct 19 17:02:46 CST 2016
     */
    public String getAmtFlag() {
        return amtFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INTER.GGPT_TXN_INFO.AMT_FLAG
     *
     * @param amtFlag the value for INTER.GGPT_TXN_INFO.AMT_FLAG
     *
     * @mbggenerated Wed Oct 19 17:02:46 CST 2016
     */
    public void setAmtFlag(String amtFlag) {
        this.amtFlag = amtFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INTER.GGPT_TXN_INFO.FML_FEE
     *
     * @return the value of INTER.GGPT_TXN_INFO.FML_FEE
     *
     * @mbggenerated Wed Oct 19 17:02:46 CST 2016
     */
    public String getFmlFee() {
        return fmlFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INTER.GGPT_TXN_INFO.FML_FEE
     *
     * @param fmlFee the value for INTER.GGPT_TXN_INFO.FML_FEE
     *
     * @mbggenerated Wed Oct 19 17:02:46 CST 2016
     */
    public void setFmlFee(String fmlFee) {
        this.fmlFee = fmlFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INTER.GGPT_TXN_INFO.FML_PROFIT
     *
     * @return the value of INTER.GGPT_TXN_INFO.FML_PROFIT
     *
     * @mbggenerated Wed Oct 19 17:02:46 CST 2016
     */
    public String getFmlProfit() {
        return fmlProfit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INTER.GGPT_TXN_INFO.FML_PROFIT
     *
     * @param fmlProfit the value for INTER.GGPT_TXN_INFO.FML_PROFIT
     *
     * @mbggenerated Wed Oct 19 17:02:46 CST 2016
     */
    public void setFmlProfit(String fmlProfit) {
        this.fmlProfit = fmlProfit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INTER.GGPT_TXN_INFO.STAT
     *
     * @return the value of INTER.GGPT_TXN_INFO.STAT
     *
     * @mbggenerated Wed Oct 19 17:02:46 CST 2016
     */
    public String getStat() {
        return stat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INTER.GGPT_TXN_INFO.STAT
     *
     * @param stat the value for INTER.GGPT_TXN_INFO.STAT
     *
     * @mbggenerated Wed Oct 19 17:02:46 CST 2016
     */
    public void setStat(String stat) {
        this.stat = stat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INTER.GGPT_TXN_INFO.CURRENCY
     *
     * @return the value of INTER.GGPT_TXN_INFO.CURRENCY
     *
     * @mbggenerated Wed Oct 19 17:02:46 CST 2016
     */
    public String getCurrency() {
        return currency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INTER.GGPT_TXN_INFO.CURRENCY
     *
     * @param currency the value for INTER.GGPT_TXN_INFO.CURRENCY
     *
     * @mbggenerated Wed Oct 19 17:02:46 CST 2016
     */
    public void setCurrency(String currency) {
        this.currency = currency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INTER.GGPT_TXN_INFO.OP_ACCT_NAME
     *
     * @return the value of INTER.GGPT_TXN_INFO.OP_ACCT_NAME
     *
     * @mbggenerated Wed Oct 19 17:02:46 CST 2016
     */
    public String getOpAcctName() {
        return opAcctName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INTER.GGPT_TXN_INFO.OP_ACCT_NAME
     *
     * @param opAcctName the value for INTER.GGPT_TXN_INFO.OP_ACCT_NAME
     *
     * @mbggenerated Wed Oct 19 17:02:46 CST 2016
     */
    public void setOpAcctName(String opAcctName) {
        this.opAcctName = opAcctName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INTER.GGPT_TXN_INFO.OP_ACCT_NO
     *
     * @return the value of INTER.GGPT_TXN_INFO.OP_ACCT_NO
     *
     * @mbggenerated Wed Oct 19 17:02:46 CST 2016
     */
    public String getOpAcctNo() {
        return opAcctNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INTER.GGPT_TXN_INFO.OP_ACCT_NO
     *
     * @param opAcctNo the value for INTER.GGPT_TXN_INFO.OP_ACCT_NO
     *
     * @mbggenerated Wed Oct 19 17:02:46 CST 2016
     */
    public void setOpAcctNo(String opAcctNo) {
        this.opAcctNo = opAcctNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INTER.GGPT_TXN_INFO.OP_IDCARD_TYPE
     *
     * @return the value of INTER.GGPT_TXN_INFO.OP_IDCARD_TYPE
     *
     * @mbggenerated Wed Oct 19 17:02:46 CST 2016
     */
    public String getOpIdcardType() {
        return opIdcardType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INTER.GGPT_TXN_INFO.OP_IDCARD_TYPE
     *
     * @param opIdcardType the value for INTER.GGPT_TXN_INFO.OP_IDCARD_TYPE
     *
     * @mbggenerated Wed Oct 19 17:02:46 CST 2016
     */
    public void setOpIdcardType(String opIdcardType) {
        this.opIdcardType = opIdcardType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INTER.GGPT_TXN_INFO.OP_IDCARD_NO
     *
     * @return the value of INTER.GGPT_TXN_INFO.OP_IDCARD_NO
     *
     * @mbggenerated Wed Oct 19 17:02:46 CST 2016
     */
    public String getOpIdcardNo() {
        return opIdcardNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INTER.GGPT_TXN_INFO.OP_IDCARD_NO
     *
     * @param opIdcardNo the value for INTER.GGPT_TXN_INFO.OP_IDCARD_NO
     *
     * @mbggenerated Wed Oct 19 17:02:46 CST 2016
     */
    public void setOpIdcardNo(String opIdcardNo) {
        this.opIdcardNo = opIdcardNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INTER.GGPT_TXN_INFO.POINTS_EXCHANGE
     *
     * @return the value of INTER.GGPT_TXN_INFO.POINTS_EXCHANGE
     *
     * @mbggenerated Wed Oct 19 17:02:46 CST 2016
     */
    public String getPointsExchange() {
        return pointsExchange;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INTER.GGPT_TXN_INFO.POINTS_EXCHANGE
     *
     * @param pointsExchange the value for INTER.GGPT_TXN_INFO.POINTS_EXCHANGE
     *
     * @mbggenerated Wed Oct 19 17:02:46 CST 2016
     */
    public void setPointsExchange(String pointsExchange) {
        this.pointsExchange = pointsExchange;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INTER.GGPT_TXN_INFO.POINTS_LEFT
     *
     * @return the value of INTER.GGPT_TXN_INFO.POINTS_LEFT
     *
     * @mbggenerated Wed Oct 19 17:02:46 CST 2016
     */
    public String getPointsLeft() {
        return pointsLeft;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INTER.GGPT_TXN_INFO.POINTS_LEFT
     *
     * @param pointsLeft the value for INTER.GGPT_TXN_INFO.POINTS_LEFT
     *
     * @mbggenerated Wed Oct 19 17:02:46 CST 2016
     */
    public void setPointsLeft(String pointsLeft) {
        this.pointsLeft = pointsLeft;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INTER.GGPT_TXN_INFO.ORIG_TRANS_AMOUNT
     *
     * @return the value of INTER.GGPT_TXN_INFO.ORIG_TRANS_AMOUNT
     *
     * @mbggenerated Wed Oct 19 17:02:46 CST 2016
     */
    public String getOrigTransAmount() {
        return origTransAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INTER.GGPT_TXN_INFO.ORIG_TRANS_AMOUNT
     *
     * @param origTransAmount the value for INTER.GGPT_TXN_INFO.ORIG_TRANS_AMOUNT
     *
     * @mbggenerated Wed Oct 19 17:02:46 CST 2016
     */
    public void setOrigTransAmount(String origTransAmount) {
        this.origTransAmount = origTransAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INTER.GGPT_TXN_INFO.ACTU_TRANS_AMOUNT
     *
     * @return the value of INTER.GGPT_TXN_INFO.ACTU_TRANS_AMOUNT
     *
     * @mbggenerated Wed Oct 19 17:02:46 CST 2016
     */
    public String getActuTransAmount() {
        return actuTransAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INTER.GGPT_TXN_INFO.ACTU_TRANS_AMOUNT
     *
     * @param actuTransAmount the value for INTER.GGPT_TXN_INFO.ACTU_TRANS_AMOUNT
     *
     * @mbggenerated Wed Oct 19 17:02:46 CST 2016
     */
    public void setActuTransAmount(String actuTransAmount) {
        this.actuTransAmount = actuTransAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INTER.GGPT_TXN_INFO.OD_TYPE
     *
     * @return the value of INTER.GGPT_TXN_INFO.OD_TYPE
     *
     * @mbggenerated Wed Oct 19 17:02:46 CST 2016
     */
    public String getOdType() {
        return odType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INTER.GGPT_TXN_INFO.OD_TYPE
     *
     * @param odType the value for INTER.GGPT_TXN_INFO.OD_TYPE
     *
     * @mbggenerated Wed Oct 19 17:02:46 CST 2016
     */
    public void setOdType(String odType) {
        this.odType = odType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INTER.GGPT_TXN_INFO.CARD_TYPE
     *
     * @return the value of INTER.GGPT_TXN_INFO.CARD_TYPE
     *
     * @mbggenerated Wed Oct 19 17:02:46 CST 2016
     */
    public String getCardType() {
        return cardType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INTER.GGPT_TXN_INFO.CARD_TYPE
     *
     * @param cardType the value for INTER.GGPT_TXN_INFO.CARD_TYPE
     *
     * @mbggenerated Wed Oct 19 17:02:46 CST 2016
     */
    public void setCardType(String cardType) {
        this.cardType = cardType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INTER.GGPT_TXN_INFO.REFUND_AMOUNT
     *
     * @return the value of INTER.GGPT_TXN_INFO.REFUND_AMOUNT
     *
     * @mbggenerated Wed Oct 19 17:02:46 CST 2016
     */
    public String getRefundAmount() {
        return refundAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INTER.GGPT_TXN_INFO.REFUND_AMOUNT
     *
     * @param refundAmount the value for INTER.GGPT_TXN_INFO.REFUND_AMOUNT
     *
     * @mbggenerated Wed Oct 19 17:02:46 CST 2016
     */
    public void setRefundAmount(String refundAmount) {
        this.refundAmount = refundAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INTER.GGPT_TXN_INFO.EXCHANGE_RATE
     *
     * @return the value of INTER.GGPT_TXN_INFO.EXCHANGE_RATE
     *
     * @mbggenerated Wed Oct 19 17:02:46 CST 2016
     */
    public String getExchangeRate() {
        return exchangeRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INTER.GGPT_TXN_INFO.EXCHANGE_RATE
     *
     * @param exchangeRate the value for INTER.GGPT_TXN_INFO.EXCHANGE_RATE
     *
     * @mbggenerated Wed Oct 19 17:02:46 CST 2016
     */
    public void setExchangeRate(String exchangeRate) {
        this.exchangeRate = exchangeRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INTER.GGPT_TXN_INFO.CNY_AMOUNT
     *
     * @return the value of INTER.GGPT_TXN_INFO.CNY_AMOUNT
     *
     * @mbggenerated Wed Oct 19 17:02:46 CST 2016
     */
    public String getCnyAmount() {
        return cnyAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INTER.GGPT_TXN_INFO.CNY_AMOUNT
     *
     * @param cnyAmount the value for INTER.GGPT_TXN_INFO.CNY_AMOUNT
     *
     * @mbggenerated Wed Oct 19 17:02:46 CST 2016
     */
    public void setCnyAmount(String cnyAmount) {
        this.cnyAmount = cnyAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INTER.GGPT_TXN_INFO.ISSUER_NAME
     *
     * @return the value of INTER.GGPT_TXN_INFO.ISSUER_NAME
     *
     * @mbggenerated Wed Oct 19 17:02:46 CST 2016
     */
    public String getIssuerName() {
        return issuerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INTER.GGPT_TXN_INFO.ISSUER_NAME
     *
     * @param issuerName the value for INTER.GGPT_TXN_INFO.ISSUER_NAME
     *
     * @mbggenerated Wed Oct 19 17:02:46 CST 2016
     */
    public void setIssuerName(String issuerName) {
        this.issuerName = issuerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INTER.GGPT_TXN_INFO.ACQUIRER_ID
     *
     * @return the value of INTER.GGPT_TXN_INFO.ACQUIRER_ID
     *
     * @mbggenerated Wed Oct 19 17:02:46 CST 2016
     */
    public String getAcquirerId() {
        return acquirerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INTER.GGPT_TXN_INFO.ACQUIRER_ID
     *
     * @param acquirerId the value for INTER.GGPT_TXN_INFO.ACQUIRER_ID
     *
     * @mbggenerated Wed Oct 19 17:02:46 CST 2016
     */
    public void setAcquirerId(String acquirerId) {
        this.acquirerId = acquirerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INTER.GGPT_TXN_INFO.ACQUIRER_NAME
     *
     * @return the value of INTER.GGPT_TXN_INFO.ACQUIRER_NAME
     *
     * @mbggenerated Wed Oct 19 17:02:46 CST 2016
     */
    public String getAcquirerName() {
        return acquirerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INTER.GGPT_TXN_INFO.ACQUIRER_NAME
     *
     * @param acquirerName the value for INTER.GGPT_TXN_INFO.ACQUIRER_NAME
     *
     * @mbggenerated Wed Oct 19 17:02:46 CST 2016
     */
    public void setAcquirerName(String acquirerName) {
        this.acquirerName = acquirerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INTER.GGPT_TXN_INFO.CHNL_OD_DESC
     *
     * @return the value of INTER.GGPT_TXN_INFO.CHNL_OD_DESC
     *
     * @mbggenerated Wed Oct 19 17:02:46 CST 2016
     */
    public String getChnlOdDesc() {
        return chnlOdDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INTER.GGPT_TXN_INFO.CHNL_OD_DESC
     *
     * @param chnlOdDesc the value for INTER.GGPT_TXN_INFO.CHNL_OD_DESC
     *
     * @mbggenerated Wed Oct 19 17:02:46 CST 2016
     */
    public void setChnlOdDesc(String chnlOdDesc) {
        this.chnlOdDesc = chnlOdDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INTER.GGPT_TXN_INFO.CNL_TRANS_AMT
     *
     * @return the value of INTER.GGPT_TXN_INFO.CNL_TRANS_AMT
     *
     * @mbggenerated Wed Oct 19 17:02:46 CST 2016
     */
    public String getCnlTransAmt() {
        return cnlTransAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INTER.GGPT_TXN_INFO.CNL_TRANS_AMT
     *
     * @param cnlTransAmt the value for INTER.GGPT_TXN_INFO.CNL_TRANS_AMT
     *
     * @mbggenerated Wed Oct 19 17:02:46 CST 2016
     */
    public void setCnlTransAmt(String cnlTransAmt) {
        this.cnlTransAmt = cnlTransAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INTER.GGPT_TXN_INFO.CNL_TRANS_CUR
     *
     * @return the value of INTER.GGPT_TXN_INFO.CNL_TRANS_CUR
     *
     * @mbggenerated Wed Oct 19 17:02:46 CST 2016
     */
    public String getCnlTransCur() {
        return cnlTransCur;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INTER.GGPT_TXN_INFO.CNL_TRANS_CUR
     *
     * @param cnlTransCur the value for INTER.GGPT_TXN_INFO.CNL_TRANS_CUR
     *
     * @mbggenerated Wed Oct 19 17:02:46 CST 2016
     */
    public void setCnlTransCur(String cnlTransCur) {
        this.cnlTransCur = cnlTransCur;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INTER.GGPT_TXN_INFO.DCC_FLAG
     *
     * @return the value of INTER.GGPT_TXN_INFO.DCC_FLAG
     *
     * @mbggenerated Wed Oct 19 17:02:46 CST 2016
     */
    public String getDccFlag() {
        return dccFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INTER.GGPT_TXN_INFO.DCC_FLAG
     *
     * @param dccFlag the value for INTER.GGPT_TXN_INFO.DCC_FLAG
     *
     * @mbggenerated Wed Oct 19 17:02:46 CST 2016
     */
    public void setDccFlag(String dccFlag) {
        this.dccFlag = dccFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INTER.GGPT_TXN_INFO.DCC_EX_RATE
     *
     * @return the value of INTER.GGPT_TXN_INFO.DCC_EX_RATE
     *
     * @mbggenerated Wed Oct 19 17:02:46 CST 2016
     */
    public String getDccExRate() {
        return dccExRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INTER.GGPT_TXN_INFO.DCC_EX_RATE
     *
     * @param dccExRate the value for INTER.GGPT_TXN_INFO.DCC_EX_RATE
     *
     * @mbggenerated Wed Oct 19 17:02:46 CST 2016
     */
    public void setDccExRate(String dccExRate) {
        this.dccExRate = dccExRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INTER.GGPT_TXN_INFO.NOTIFY_URL
     *
     * @return the value of INTER.GGPT_TXN_INFO.NOTIFY_URL
     *
     * @mbggenerated Wed Oct 19 17:02:46 CST 2016
     */
    public String getNotifyUrl() {
        return notifyUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INTER.GGPT_TXN_INFO.NOTIFY_URL
     *
     * @param notifyUrl the value for INTER.GGPT_TXN_INFO.NOTIFY_URL
     *
     * @mbggenerated Wed Oct 19 17:02:46 CST 2016
     */
    public void setNotifyUrl(String notifyUrl) {
        this.notifyUrl = notifyUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INTER.GGPT_TXN_INFO.IS_SEND
     *
     * @return the value of INTER.GGPT_TXN_INFO.IS_SEND
     *
     * @mbggenerated Wed Oct 19 17:02:46 CST 2016
     */
    public String getIsSend() {
        return isSend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INTER.GGPT_TXN_INFO.IS_SEND
     *
     * @param isSend the value for INTER.GGPT_TXN_INFO.IS_SEND
     *
     * @mbggenerated Wed Oct 19 17:02:46 CST 2016
     */
    public void setIsSend(String isSend) {
        this.isSend = isSend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INTER.GGPT_TXN_INFO.MM_MEMBER_ID
     *
     * @return the value of INTER.GGPT_TXN_INFO.MM_MEMBER_ID
     *
     * @mbggenerated Wed Oct 19 17:02:46 CST 2016
     */
    public String getMmMemberId() {
        return mmMemberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INTER.GGPT_TXN_INFO.MM_MEMBER_ID
     *
     * @param mmMemberId the value for INTER.GGPT_TXN_INFO.MM_MEMBER_ID
     *
     * @mbggenerated Wed Oct 19 17:02:46 CST 2016
     */
    public void setMmMemberId(String mmMemberId) {
        this.mmMemberId = mmMemberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INTER.GGPT_TXN_INFO.WAY_OF_CARD
     *
     * @return the value of INTER.GGPT_TXN_INFO.WAY_OF_CARD
     *
     * @mbggenerated Wed Oct 19 17:02:46 CST 2016
     */
    public String getWayOfCard() {
        return wayOfCard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INTER.GGPT_TXN_INFO.WAY_OF_CARD
     *
     * @param wayOfCard the value for INTER.GGPT_TXN_INFO.WAY_OF_CARD
     *
     * @mbggenerated Wed Oct 19 17:02:46 CST 2016
     */
    public void setWayOfCard(String wayOfCard) {
        this.wayOfCard = wayOfCard;
    }
}