package cn.koolyun.model;

import java.util.ArrayList;
import java.util.List;

public class TdatDictExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table INTER.T_DAT_DICT
     *
     * @mbggenerated Mon Oct 24 16:36:56 CST 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table INTER.T_DAT_DICT
     *
     * @mbggenerated Mon Oct 24 16:36:56 CST 2016
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table INTER.T_DAT_DICT
     *
     * @mbggenerated Mon Oct 24 16:36:56 CST 2016
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INTER.T_DAT_DICT
     *
     * @mbggenerated Mon Oct 24 16:36:56 CST 2016
     */
    public TdatDictExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INTER.T_DAT_DICT
     *
     * @mbggenerated Mon Oct 24 16:36:56 CST 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INTER.T_DAT_DICT
     *
     * @mbggenerated Mon Oct 24 16:36:56 CST 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INTER.T_DAT_DICT
     *
     * @mbggenerated Mon Oct 24 16:36:56 CST 2016
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INTER.T_DAT_DICT
     *
     * @mbggenerated Mon Oct 24 16:36:56 CST 2016
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INTER.T_DAT_DICT
     *
     * @mbggenerated Mon Oct 24 16:36:56 CST 2016
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INTER.T_DAT_DICT
     *
     * @mbggenerated Mon Oct 24 16:36:56 CST 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INTER.T_DAT_DICT
     *
     * @mbggenerated Mon Oct 24 16:36:56 CST 2016
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INTER.T_DAT_DICT
     *
     * @mbggenerated Mon Oct 24 16:36:56 CST 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INTER.T_DAT_DICT
     *
     * @mbggenerated Mon Oct 24 16:36:56 CST 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INTER.T_DAT_DICT
     *
     * @mbggenerated Mon Oct 24 16:36:56 CST 2016
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table INTER.T_DAT_DICT
     *
     * @mbggenerated Mon Oct 24 16:36:56 CST 2016
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andDataKindIsNull() {
            addCriterion("DATA_KIND is null");
            return (Criteria) this;
        }

        public Criteria andDataKindIsNotNull() {
            addCriterion("DATA_KIND is not null");
            return (Criteria) this;
        }

        public Criteria andDataKindEqualTo(String value) {
            addCriterion("DATA_KIND =", value, "dataKind");
            return (Criteria) this;
        }

        public Criteria andDataKindNotEqualTo(String value) {
            addCriterion("DATA_KIND <>", value, "dataKind");
            return (Criteria) this;
        }

        public Criteria andDataKindGreaterThan(String value) {
            addCriterion("DATA_KIND >", value, "dataKind");
            return (Criteria) this;
        }

        public Criteria andDataKindGreaterThanOrEqualTo(String value) {
            addCriterion("DATA_KIND >=", value, "dataKind");
            return (Criteria) this;
        }

        public Criteria andDataKindLessThan(String value) {
            addCriterion("DATA_KIND <", value, "dataKind");
            return (Criteria) this;
        }

        public Criteria andDataKindLessThanOrEqualTo(String value) {
            addCriterion("DATA_KIND <=", value, "dataKind");
            return (Criteria) this;
        }

        public Criteria andDataKindLike(String value) {
            addCriterion("DATA_KIND like", value, "dataKind");
            return (Criteria) this;
        }

        public Criteria andDataKindNotLike(String value) {
            addCriterion("DATA_KIND not like", value, "dataKind");
            return (Criteria) this;
        }

        public Criteria andDataKindIn(List<String> values) {
            addCriterion("DATA_KIND in", values, "dataKind");
            return (Criteria) this;
        }

        public Criteria andDataKindNotIn(List<String> values) {
            addCriterion("DATA_KIND not in", values, "dataKind");
            return (Criteria) this;
        }

        public Criteria andDataKindBetween(String value1, String value2) {
            addCriterion("DATA_KIND between", value1, value2, "dataKind");
            return (Criteria) this;
        }

        public Criteria andDataKindNotBetween(String value1, String value2) {
            addCriterion("DATA_KIND not between", value1, value2, "dataKind");
            return (Criteria) this;
        }

        public Criteria andDataTypeIsNull() {
            addCriterion("DATA_TYPE is null");
            return (Criteria) this;
        }

        public Criteria andDataTypeIsNotNull() {
            addCriterion("DATA_TYPE is not null");
            return (Criteria) this;
        }

        public Criteria andDataTypeEqualTo(String value) {
            addCriterion("DATA_TYPE =", value, "dataType");
            return (Criteria) this;
        }

        public Criteria andDataTypeNotEqualTo(String value) {
            addCriterion("DATA_TYPE <>", value, "dataType");
            return (Criteria) this;
        }

        public Criteria andDataTypeGreaterThan(String value) {
            addCriterion("DATA_TYPE >", value, "dataType");
            return (Criteria) this;
        }

        public Criteria andDataTypeGreaterThanOrEqualTo(String value) {
            addCriterion("DATA_TYPE >=", value, "dataType");
            return (Criteria) this;
        }

        public Criteria andDataTypeLessThan(String value) {
            addCriterion("DATA_TYPE <", value, "dataType");
            return (Criteria) this;
        }

        public Criteria andDataTypeLessThanOrEqualTo(String value) {
            addCriterion("DATA_TYPE <=", value, "dataType");
            return (Criteria) this;
        }

        public Criteria andDataTypeLike(String value) {
            addCriterion("DATA_TYPE like", value, "dataType");
            return (Criteria) this;
        }

        public Criteria andDataTypeNotLike(String value) {
            addCriterion("DATA_TYPE not like", value, "dataType");
            return (Criteria) this;
        }

        public Criteria andDataTypeIn(List<String> values) {
            addCriterion("DATA_TYPE in", values, "dataType");
            return (Criteria) this;
        }

        public Criteria andDataTypeNotIn(List<String> values) {
            addCriterion("DATA_TYPE not in", values, "dataType");
            return (Criteria) this;
        }

        public Criteria andDataTypeBetween(String value1, String value2) {
            addCriterion("DATA_TYPE between", value1, value2, "dataType");
            return (Criteria) this;
        }

        public Criteria andDataTypeNotBetween(String value1, String value2) {
            addCriterion("DATA_TYPE not between", value1, value2, "dataType");
            return (Criteria) this;
        }

        public Criteria andDataCdIsNull() {
            addCriterion("DATA_CD is null");
            return (Criteria) this;
        }

        public Criteria andDataCdIsNotNull() {
            addCriterion("DATA_CD is not null");
            return (Criteria) this;
        }

        public Criteria andDataCdEqualTo(String value) {
            addCriterion("DATA_CD =", value, "dataCd");
            return (Criteria) this;
        }

        public Criteria andDataCdNotEqualTo(String value) {
            addCriterion("DATA_CD <>", value, "dataCd");
            return (Criteria) this;
        }

        public Criteria andDataCdGreaterThan(String value) {
            addCriterion("DATA_CD >", value, "dataCd");
            return (Criteria) this;
        }

        public Criteria andDataCdGreaterThanOrEqualTo(String value) {
            addCriterion("DATA_CD >=", value, "dataCd");
            return (Criteria) this;
        }

        public Criteria andDataCdLessThan(String value) {
            addCriterion("DATA_CD <", value, "dataCd");
            return (Criteria) this;
        }

        public Criteria andDataCdLessThanOrEqualTo(String value) {
            addCriterion("DATA_CD <=", value, "dataCd");
            return (Criteria) this;
        }

        public Criteria andDataCdLike(String value) {
            addCriterion("DATA_CD like", value, "dataCd");
            return (Criteria) this;
        }

        public Criteria andDataCdNotLike(String value) {
            addCriterion("DATA_CD not like", value, "dataCd");
            return (Criteria) this;
        }

        public Criteria andDataCdIn(List<String> values) {
            addCriterion("DATA_CD in", values, "dataCd");
            return (Criteria) this;
        }

        public Criteria andDataCdNotIn(List<String> values) {
            addCriterion("DATA_CD not in", values, "dataCd");
            return (Criteria) this;
        }

        public Criteria andDataCdBetween(String value1, String value2) {
            addCriterion("DATA_CD between", value1, value2, "dataCd");
            return (Criteria) this;
        }

        public Criteria andDataCdNotBetween(String value1, String value2) {
            addCriterion("DATA_CD not between", value1, value2, "dataCd");
            return (Criteria) this;
        }

        public Criteria andDataNmIsNull() {
            addCriterion("DATA_NM is null");
            return (Criteria) this;
        }

        public Criteria andDataNmIsNotNull() {
            addCriterion("DATA_NM is not null");
            return (Criteria) this;
        }

        public Criteria andDataNmEqualTo(String value) {
            addCriterion("DATA_NM =", value, "dataNm");
            return (Criteria) this;
        }

        public Criteria andDataNmNotEqualTo(String value) {
            addCriterion("DATA_NM <>", value, "dataNm");
            return (Criteria) this;
        }

        public Criteria andDataNmGreaterThan(String value) {
            addCriterion("DATA_NM >", value, "dataNm");
            return (Criteria) this;
        }

        public Criteria andDataNmGreaterThanOrEqualTo(String value) {
            addCriterion("DATA_NM >=", value, "dataNm");
            return (Criteria) this;
        }

        public Criteria andDataNmLessThan(String value) {
            addCriterion("DATA_NM <", value, "dataNm");
            return (Criteria) this;
        }

        public Criteria andDataNmLessThanOrEqualTo(String value) {
            addCriterion("DATA_NM <=", value, "dataNm");
            return (Criteria) this;
        }

        public Criteria andDataNmLike(String value) {
            addCriterion("DATA_NM like", value, "dataNm");
            return (Criteria) this;
        }

        public Criteria andDataNmNotLike(String value) {
            addCriterion("DATA_NM not like", value, "dataNm");
            return (Criteria) this;
        }

        public Criteria andDataNmIn(List<String> values) {
            addCriterion("DATA_NM in", values, "dataNm");
            return (Criteria) this;
        }

        public Criteria andDataNmNotIn(List<String> values) {
            addCriterion("DATA_NM not in", values, "dataNm");
            return (Criteria) this;
        }

        public Criteria andDataNmBetween(String value1, String value2) {
            addCriterion("DATA_NM between", value1, value2, "dataNm");
            return (Criteria) this;
        }

        public Criteria andDataNmNotBetween(String value1, String value2) {
            addCriterion("DATA_NM not between", value1, value2, "dataNm");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table INTER.T_DAT_DICT
     *
     * @mbggenerated do_not_delete_during_merge Mon Oct 24 16:36:56 CST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table INTER.T_DAT_DICT
     *
     * @mbggenerated Mon Oct 24 16:36:56 CST 2016
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}