package cn.koolyun.model;

public class TdatDict {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INTER.T_DAT_DICT.DATA_KIND
     *
     * @mbggenerated Mon Oct 24 16:36:56 CST 2016
     */
    private String dataKind;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INTER.T_DAT_DICT.DATA_TYPE
     *
     * @mbggenerated Mon Oct 24 16:36:56 CST 2016
     */
    private String dataType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INTER.T_DAT_DICT.DATA_CD
     *
     * @mbggenerated Mon Oct 24 16:36:56 CST 2016
     */
    private String dataCd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INTER.T_DAT_DICT.DATA_NM
     *
     * @mbggenerated Mon Oct 24 16:36:56 CST 2016
     */
    private String dataNm;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INTER.T_DAT_DICT.DATA_KIND
     *
     * @return the value of INTER.T_DAT_DICT.DATA_KIND
     *
     * @mbggenerated Mon Oct 24 16:36:56 CST 2016
     */
    public String getDataKind() {
        return dataKind;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INTER.T_DAT_DICT.DATA_KIND
     *
     * @param dataKind the value for INTER.T_DAT_DICT.DATA_KIND
     *
     * @mbggenerated Mon Oct 24 16:36:56 CST 2016
     */
    public void setDataKind(String dataKind) {
        this.dataKind = dataKind;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INTER.T_DAT_DICT.DATA_TYPE
     *
     * @return the value of INTER.T_DAT_DICT.DATA_TYPE
     *
     * @mbggenerated Mon Oct 24 16:36:56 CST 2016
     */
    public String getDataType() {
        return dataType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INTER.T_DAT_DICT.DATA_TYPE
     *
     * @param dataType the value for INTER.T_DAT_DICT.DATA_TYPE
     *
     * @mbggenerated Mon Oct 24 16:36:56 CST 2016
     */
    public void setDataType(String dataType) {
        this.dataType = dataType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INTER.T_DAT_DICT.DATA_CD
     *
     * @return the value of INTER.T_DAT_DICT.DATA_CD
     *
     * @mbggenerated Mon Oct 24 16:36:56 CST 2016
     */
    public String getDataCd() {
        return dataCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INTER.T_DAT_DICT.DATA_CD
     *
     * @param dataCd the value for INTER.T_DAT_DICT.DATA_CD
     *
     * @mbggenerated Mon Oct 24 16:36:56 CST 2016
     */
    public void setDataCd(String dataCd) {
        this.dataCd = dataCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INTER.T_DAT_DICT.DATA_NM
     *
     * @return the value of INTER.T_DAT_DICT.DATA_NM
     *
     * @mbggenerated Mon Oct 24 16:36:56 CST 2016
     */
    public String getDataNm() {
        return dataNm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INTER.T_DAT_DICT.DATA_NM
     *
     * @param dataNm the value for INTER.T_DAT_DICT.DATA_NM
     *
     * @mbggenerated Mon Oct 24 16:36:56 CST 2016
     */
    public void setDataNm(String dataNm) {
        this.dataNm = dataNm;
    }
}