package cn.koolyun.model;

public class TidMapper {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INTER.T_ID_MAPPER.ID
     *
     * @mbggenerated Thu Oct 20 18:07:34 CST 2016
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INTER.T_ID_MAPPER.OUTER_ID
     *
     * @mbggenerated Thu Oct 20 18:07:34 CST 2016
     */
    private String outerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INTER.T_ID_MAPPER.INTER_ID
     *
     * @mbggenerated Thu Oct 20 18:07:34 CST 2016
     */
    private String interId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INTER.T_ID_MAPPER.TYPE
     *
     * @mbggenerated Thu Oct 20 18:07:34 CST 2016
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INTER.T_ID_MAPPER.OUTER_SOURCE
     *
     * @mbggenerated Thu Oct 20 18:07:34 CST 2016
     */
    private String outerSource;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INTER.T_ID_MAPPER.ID
     *
     * @return the value of INTER.T_ID_MAPPER.ID
     *
     * @mbggenerated Thu Oct 20 18:07:34 CST 2016
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INTER.T_ID_MAPPER.ID
     *
     * @param id the value for INTER.T_ID_MAPPER.ID
     *
     * @mbggenerated Thu Oct 20 18:07:34 CST 2016
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INTER.T_ID_MAPPER.OUTER_ID
     *
     * @return the value of INTER.T_ID_MAPPER.OUTER_ID
     *
     * @mbggenerated Thu Oct 20 18:07:34 CST 2016
     */
    public String getOuterId() {
        return outerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INTER.T_ID_MAPPER.OUTER_ID
     *
     * @param outerId the value for INTER.T_ID_MAPPER.OUTER_ID
     *
     * @mbggenerated Thu Oct 20 18:07:34 CST 2016
     */
    public void setOuterId(String outerId) {
        this.outerId = outerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INTER.T_ID_MAPPER.INTER_ID
     *
     * @return the value of INTER.T_ID_MAPPER.INTER_ID
     *
     * @mbggenerated Thu Oct 20 18:07:34 CST 2016
     */
    public String getInterId() {
        return interId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INTER.T_ID_MAPPER.INTER_ID
     *
     * @param interId the value for INTER.T_ID_MAPPER.INTER_ID
     *
     * @mbggenerated Thu Oct 20 18:07:34 CST 2016
     */
    public void setInterId(String interId) {
        this.interId = interId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INTER.T_ID_MAPPER.TYPE
     *
     * @return the value of INTER.T_ID_MAPPER.TYPE
     *
     * @mbggenerated Thu Oct 20 18:07:34 CST 2016
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INTER.T_ID_MAPPER.TYPE
     *
     * @param type the value for INTER.T_ID_MAPPER.TYPE
     *
     * @mbggenerated Thu Oct 20 18:07:34 CST 2016
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INTER.T_ID_MAPPER.OUTER_SOURCE
     *
     * @return the value of INTER.T_ID_MAPPER.OUTER_SOURCE
     *
     * @mbggenerated Thu Oct 20 18:07:34 CST 2016
     */
    public String getOuterSource() {
        return outerSource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INTER.T_ID_MAPPER.OUTER_SOURCE
     *
     * @param outerSource the value for INTER.T_ID_MAPPER.OUTER_SOURCE
     *
     * @mbggenerated Thu Oct 20 18:07:34 CST 2016
     */
    public void setOuterSource(String outerSource) {
        this.outerSource = outerSource;
    }
}