package cn.koolyun.model;

import java.math.BigDecimal;
import java.util.Date;

public class TmerInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INTER.T_MER_INFO.MER_ID
     *
     * @mbggenerated Tue Oct 25 14:03:35 CST 2016
     */
    private String merId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INTER.T_MER_INFO.BRH_ID
     *
     * @mbggenerated Tue Oct 25 14:03:35 CST 2016
     */
    private String brhId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INTER.T_MER_INFO.MER_NM
     *
     * @mbggenerated Tue Oct 25 14:03:35 CST 2016
     */
    private String merNm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INTER.T_MER_INFO.MER_SHORT_NM
     *
     * @mbggenerated Tue Oct 25 14:03:35 CST 2016
     */
    private String merShortNm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INTER.T_MER_INFO.ENG_NM
     *
     * @mbggenerated Tue Oct 25 14:03:35 CST 2016
     */
    private String engNm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INTER.T_MER_INFO.REG_NM
     *
     * @mbggenerated Tue Oct 25 14:03:35 CST 2016
     */
    private String regNm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INTER.T_MER_INFO.ID_TYPE
     *
     * @mbggenerated Tue Oct 25 14:03:35 CST 2016
     */
    private String idType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INTER.T_MER_INFO.ID_NO
     *
     * @mbggenerated Tue Oct 25 14:03:35 CST 2016
     */
    private String idNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INTER.T_MER_INFO.ALL_FLG
     *
     * @mbggenerated Tue Oct 25 14:03:35 CST 2016
     */
    private String allFlg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INTER.T_MER_INFO.MER_LEVEL
     *
     * @mbggenerated Tue Oct 25 14:03:35 CST 2016
     */
    private String merLevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INTER.T_MER_INFO.MCC_CD
     *
     * @mbggenerated Tue Oct 25 14:03:35 CST 2016
     */
    private String mccCd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INTER.T_MER_INFO.SUP_MER_ID
     *
     * @mbggenerated Tue Oct 25 14:03:35 CST 2016
     */
    private String supMerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INTER.T_MER_INFO.MGR_BRH_ID
     *
     * @mbggenerated Tue Oct 25 14:03:35 CST 2016
     */
    private String mgrBrhId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INTER.T_MER_INFO.ACQ_BRH_ID
     *
     * @mbggenerated Tue Oct 25 14:03:35 CST 2016
     */
    private String acqBrhId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INTER.T_MER_INFO.LOC_NATION
     *
     * @mbggenerated Tue Oct 25 14:03:35 CST 2016
     */
    private String locNation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INTER.T_MER_INFO.LOC_PROV
     *
     * @mbggenerated Tue Oct 25 14:03:35 CST 2016
     */
    private String locProv;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INTER.T_MER_INFO.LOC_CITY
     *
     * @mbggenerated Tue Oct 25 14:03:35 CST 2016
     */
    private String locCity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INTER.T_MER_INFO.ADDR
     *
     * @mbggenerated Tue Oct 25 14:03:35 CST 2016
     */
    private String addr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INTER.T_MER_INFO.PERSON
     *
     * @mbggenerated Tue Oct 25 14:03:35 CST 2016
     */
    private String person;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INTER.T_MER_INFO.TEL
     *
     * @mbggenerated Tue Oct 25 14:03:35 CST 2016
     */
    private String tel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INTER.T_MER_INFO.FAX
     *
     * @mbggenerated Tue Oct 25 14:03:35 CST 2016
     */
    private String fax;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INTER.T_MER_INFO.EMAIL
     *
     * @mbggenerated Tue Oct 25 14:03:35 CST 2016
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INTER.T_MER_INFO.EM_PERSON_
     *
     * @mbggenerated Tue Oct 25 14:03:35 CST 2016
     */
    private String emPerson;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INTER.T_MER_INFO.EM_TEL
     *
     * @mbggenerated Tue Oct 25 14:03:35 CST 2016
     */
    private String emTel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INTER.T_MER_INFO.CONTRACT_DT
     *
     * @mbggenerated Tue Oct 25 14:03:35 CST 2016
     */
    private String contractDt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INTER.T_MER_INFO.EXPAND_INST
     *
     * @mbggenerated Tue Oct 25 14:03:35 CST 2016
     */
    private String expandInst;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INTER.T_MER_INFO.EXPAND_PERSON
     *
     * @mbggenerated Tue Oct 25 14:03:35 CST 2016
     */
    private String expandPerson;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INTER.T_MER_INFO.CUST_MGR
     *
     * @mbggenerated Tue Oct 25 14:03:35 CST 2016
     */
    private String custMgr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INTER.T_MER_INFO.CUST_MGR_TEL
     *
     * @mbggenerated Tue Oct 25 14:03:35 CST 2016
     */
    private String custMgrTel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INTER.T_MER_INFO.CUST_MGR_MOBILE
     *
     * @mbggenerated Tue Oct 25 14:03:35 CST 2016
     */
    private String custMgrMobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INTER.T_MER_INFO.STLMT_LEV
     *
     * @mbggenerated Tue Oct 25 14:03:35 CST 2016
     */
    private String stlmtLev;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INTER.T_MER_INFO.STLMT_PERIOD
     *
     * @mbggenerated Tue Oct 25 14:03:35 CST 2016
     */
    private Short stlmtPeriod;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INTER.T_MER_INFO.STLMT_PERIOD_UNIT
     *
     * @mbggenerated Tue Oct 25 14:03:35 CST 2016
     */
    private String stlmtPeriodUnit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INTER.T_MER_INFO.FEE_RATE
     *
     * @mbggenerated Tue Oct 25 14:03:35 CST 2016
     */
    private String feeRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INTER.T_MER_INFO.IN_ACCT_ID
     *
     * @mbggenerated Tue Oct 25 14:03:35 CST 2016
     */
    private String inAcctId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INTER.T_MER_INFO.IN_ACCT_NM
     *
     * @mbggenerated Tue Oct 25 14:03:35 CST 2016
     */
    private String inAcctNm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INTER.T_MER_INFO.OPEN_BANK_ID
     *
     * @mbggenerated Tue Oct 25 14:03:35 CST 2016
     */
    private String openBankId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INTER.T_MER_INFO.OPEN_BANK_NM
     *
     * @mbggenerated Tue Oct 25 14:03:35 CST 2016
     */
    private String openBankNm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INTER.T_MER_INFO.OUT_ACCT_ID
     *
     * @mbggenerated Tue Oct 25 14:03:35 CST 2016
     */
    private String outAcctId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INTER.T_MER_INFO.OUT_ACCT_NM
     *
     * @mbggenerated Tue Oct 25 14:03:35 CST 2016
     */
    private String outAcctNm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INTER.T_MER_INFO.SUB_KEY_CD
     *
     * @mbggenerated Tue Oct 25 14:03:35 CST 2016
     */
    private String subKeyCd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INTER.T_MER_INFO.TYPE_CD
     *
     * @mbggenerated Tue Oct 25 14:03:35 CST 2016
     */
    private String typeCd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INTER.T_MER_INFO.RISK_RANK
     *
     * @mbggenerated Tue Oct 25 14:03:35 CST 2016
     */
    private String riskRank;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INTER.T_MER_INFO.MIS_FLG
     *
     * @mbggenerated Tue Oct 25 14:03:35 CST 2016
     */
    private String misFlg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INTER.T_MER_INFO.SYM_STR
     *
     * @mbggenerated Tue Oct 25 14:03:35 CST 2016
     */
    private String symStr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INTER.T_MER_INFO.STA
     *
     * @mbggenerated Tue Oct 25 14:03:35 CST 2016
     */
    private String sta;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INTER.T_MER_INFO.CHK_STA
     *
     * @mbggenerated Tue Oct 25 14:03:35 CST 2016
     */
    private String chkSta;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INTER.T_MER_INFO.SIGN_STA
     *
     * @mbggenerated Tue Oct 25 14:03:35 CST 2016
     */
    private String signSta;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INTER.T_MER_INFO.CRT_DT
     *
     * @mbggenerated Tue Oct 25 14:03:35 CST 2016
     */
    private String crtDt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INTER.T_MER_INFO.MISC_TX
     *
     * @mbggenerated Tue Oct 25 14:03:35 CST 2016
     */
    private String miscTx;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INTER.T_MER_INFO.LAST_UPD_BRH_ID
     *
     * @mbggenerated Tue Oct 25 14:03:35 CST 2016
     */
    private String lastUpdBrhId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INTER.T_MER_INFO.LAST_UPD_OPR_ID
     *
     * @mbggenerated Tue Oct 25 14:03:35 CST 2016
     */
    private String lastUpdOprId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INTER.T_MER_INFO.LAST_UPD_TXN_CD
     *
     * @mbggenerated Tue Oct 25 14:03:35 CST 2016
     */
    private String lastUpdTxnCd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INTER.T_MER_INFO.LAST_UPD_TS
     *
     * @mbggenerated Tue Oct 25 14:03:35 CST 2016
     */
    private Date lastUpdTs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INTER.T_MER_INFO.STL_CUR
     *
     * @mbggenerated Tue Oct 25 14:03:35 CST 2016
     */
    private String stlCur;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INTER.T_MER_INFO.STLMT_MIN
     *
     * @mbggenerated Tue Oct 25 14:03:35 CST 2016
     */
    private String stlmtMin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INTER.T_MER_INFO.LOC_P
     *
     * @mbggenerated Tue Oct 25 14:03:35 CST 2016
     */
    private String locP;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INTER.T_MER_INFO.LOC_C
     *
     * @mbggenerated Tue Oct 25 14:03:35 CST 2016
     */
    private String locC;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INTER.T_MER_INFO.LOC_R
     *
     * @mbggenerated Tue Oct 25 14:03:35 CST 2016
     */
    private String locR;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INTER.T_MER_INFO.LOC_A
     *
     * @mbggenerated Tue Oct 25 14:03:35 CST 2016
     */
    private String locA;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INTER.T_MER_INFO.REJECT_MSG
     *
     * @mbggenerated Tue Oct 25 14:03:35 CST 2016
     */
    private String rejectMsg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INTER.T_MER_INFO.SMS_CHECK
     *
     * @mbggenerated Tue Oct 25 14:03:35 CST 2016
     */
    private String smsCheck;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INTER.T_MER_INFO.COUNTRY_AREA_CD
     *
     * @mbggenerated Tue Oct 25 14:03:35 CST 2016
     */
    private String countryAreaCd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INTER.T_MER_INFO.POS_RECEIPT_NAME
     *
     * @mbggenerated Tue Oct 25 14:03:35 CST 2016
     */
    private String posReceiptName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INTER.T_MER_INFO.FILE_ID
     *
     * @mbggenerated Tue Oct 25 14:03:35 CST 2016
     */
    private BigDecimal fileId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INTER.T_MER_INFO.IDCARD_BACK_FILEID
     *
     * @mbggenerated Tue Oct 25 14:03:35 CST 2016
     */
    private BigDecimal idcardBackFileid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INTER.T_MER_INFO.IDCARD_APPLICATION_FILEID
     *
     * @mbggenerated Tue Oct 25 14:03:35 CST 2016
     */
    private BigDecimal idcardApplicationFileid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INTER.T_MER_INFO.LOGO_FILE_ID
     *
     * @mbggenerated Tue Oct 25 14:03:35 CST 2016
     */
    private BigDecimal logoFileId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INTER.T_MER_INFO.BIND_TIMESTAMP
     *
     * @mbggenerated Tue Oct 25 14:03:35 CST 2016
     */
    private Date bindTimestamp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INTER.T_MER_INFO.LMF_FIXED_AMT
     *
     * @mbggenerated Tue Oct 25 14:03:35 CST 2016
     */
    private String lmfFixedAmt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INTER.T_MER_INFO.LMF_FIXED_AMT_FLG
     *
     * @mbggenerated Tue Oct 25 14:03:35 CST 2016
     */
    private String lmfFixedAmtFlg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INTER.T_MER_INFO.BUSINESS_CATEGORY
     *
     * @mbggenerated Tue Oct 25 14:03:35 CST 2016
     */
    private String businessCategory;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INTER.T_MER_INFO.FEE_RATE_FLAG
     *
     * @mbggenerated Tue Oct 25 14:03:35 CST 2016
     */
    private String feeRateFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INTER.T_MER_INFO.D0_FLAG
     *
     * @mbggenerated Tue Oct 25 14:03:35 CST 2016
     */
    private String d0Flag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INTER.T_MER_INFO.IN_ACCT_TYPE
     *
     * @mbggenerated Tue Oct 25 14:03:35 CST 2016
     */
    private String inAcctType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INTER.T_MER_INFO.CHECK_TIMESTAMP
     *
     * @mbggenerated Tue Oct 25 14:03:35 CST 2016
     */
    private Date checkTimestamp;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INTER.T_MER_INFO.MER_ID
     *
     * @return the value of INTER.T_MER_INFO.MER_ID
     *
     * @mbggenerated Tue Oct 25 14:03:35 CST 2016
     */
    public String getMerId() {
        return merId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INTER.T_MER_INFO.MER_ID
     *
     * @param merId the value for INTER.T_MER_INFO.MER_ID
     *
     * @mbggenerated Tue Oct 25 14:03:35 CST 2016
     */
    public void setMerId(String merId) {
        this.merId = merId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INTER.T_MER_INFO.BRH_ID
     *
     * @return the value of INTER.T_MER_INFO.BRH_ID
     *
     * @mbggenerated Tue Oct 25 14:03:35 CST 2016
     */
    public String getBrhId() {
        return brhId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INTER.T_MER_INFO.BRH_ID
     *
     * @param brhId the value for INTER.T_MER_INFO.BRH_ID
     *
     * @mbggenerated Tue Oct 25 14:03:35 CST 2016
     */
    public void setBrhId(String brhId) {
        this.brhId = brhId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INTER.T_MER_INFO.MER_NM
     *
     * @return the value of INTER.T_MER_INFO.MER_NM
     *
     * @mbggenerated Tue Oct 25 14:03:35 CST 2016
     */
    public String getMerNm() {
        return merNm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INTER.T_MER_INFO.MER_NM
     *
     * @param merNm the value for INTER.T_MER_INFO.MER_NM
     *
     * @mbggenerated Tue Oct 25 14:03:35 CST 2016
     */
    public void setMerNm(String merNm) {
        this.merNm = merNm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INTER.T_MER_INFO.MER_SHORT_NM
     *
     * @return the value of INTER.T_MER_INFO.MER_SHORT_NM
     *
     * @mbggenerated Tue Oct 25 14:03:35 CST 2016
     */
    public String getMerShortNm() {
        return merShortNm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INTER.T_MER_INFO.MER_SHORT_NM
     *
     * @param merShortNm the value for INTER.T_MER_INFO.MER_SHORT_NM
     *
     * @mbggenerated Tue Oct 25 14:03:35 CST 2016
     */
    public void setMerShortNm(String merShortNm) {
        this.merShortNm = merShortNm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INTER.T_MER_INFO.ENG_NM
     *
     * @return the value of INTER.T_MER_INFO.ENG_NM
     *
     * @mbggenerated Tue Oct 25 14:03:35 CST 2016
     */
    public String getEngNm() {
        return engNm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INTER.T_MER_INFO.ENG_NM
     *
     * @param engNm the value for INTER.T_MER_INFO.ENG_NM
     *
     * @mbggenerated Tue Oct 25 14:03:35 CST 2016
     */
    public void setEngNm(String engNm) {
        this.engNm = engNm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INTER.T_MER_INFO.REG_NM
     *
     * @return the value of INTER.T_MER_INFO.REG_NM
     *
     * @mbggenerated Tue Oct 25 14:03:35 CST 2016
     */
    public String getRegNm() {
        return regNm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INTER.T_MER_INFO.REG_NM
     *
     * @param regNm the value for INTER.T_MER_INFO.REG_NM
     *
     * @mbggenerated Tue Oct 25 14:03:35 CST 2016
     */
    public void setRegNm(String regNm) {
        this.regNm = regNm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INTER.T_MER_INFO.ID_TYPE
     *
     * @return the value of INTER.T_MER_INFO.ID_TYPE
     *
     * @mbggenerated Tue Oct 25 14:03:35 CST 2016
     */
    public String getIdType() {
        return idType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INTER.T_MER_INFO.ID_TYPE
     *
     * @param idType the value for INTER.T_MER_INFO.ID_TYPE
     *
     * @mbggenerated Tue Oct 25 14:03:35 CST 2016
     */
    public void setIdType(String idType) {
        this.idType = idType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INTER.T_MER_INFO.ID_NO
     *
     * @return the value of INTER.T_MER_INFO.ID_NO
     *
     * @mbggenerated Tue Oct 25 14:03:35 CST 2016
     */
    public String getIdNo() {
        return idNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INTER.T_MER_INFO.ID_NO
     *
     * @param idNo the value for INTER.T_MER_INFO.ID_NO
     *
     * @mbggenerated Tue Oct 25 14:03:35 CST 2016
     */
    public void setIdNo(String idNo) {
        this.idNo = idNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INTER.T_MER_INFO.ALL_FLG
     *
     * @return the value of INTER.T_MER_INFO.ALL_FLG
     *
     * @mbggenerated Tue Oct 25 14:03:35 CST 2016
     */
    public String getAllFlg() {
        return allFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INTER.T_MER_INFO.ALL_FLG
     *
     * @param allFlg the value for INTER.T_MER_INFO.ALL_FLG
     *
     * @mbggenerated Tue Oct 25 14:03:35 CST 2016
     */
    public void setAllFlg(String allFlg) {
        this.allFlg = allFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INTER.T_MER_INFO.MER_LEVEL
     *
     * @return the value of INTER.T_MER_INFO.MER_LEVEL
     *
     * @mbggenerated Tue Oct 25 14:03:35 CST 2016
     */
    public String getMerLevel() {
        return merLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INTER.T_MER_INFO.MER_LEVEL
     *
     * @param merLevel the value for INTER.T_MER_INFO.MER_LEVEL
     *
     * @mbggenerated Tue Oct 25 14:03:35 CST 2016
     */
    public void setMerLevel(String merLevel) {
        this.merLevel = merLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INTER.T_MER_INFO.MCC_CD
     *
     * @return the value of INTER.T_MER_INFO.MCC_CD
     *
     * @mbggenerated Tue Oct 25 14:03:35 CST 2016
     */
    public String getMccCd() {
        return mccCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INTER.T_MER_INFO.MCC_CD
     *
     * @param mccCd the value for INTER.T_MER_INFO.MCC_CD
     *
     * @mbggenerated Tue Oct 25 14:03:35 CST 2016
     */
    public void setMccCd(String mccCd) {
        this.mccCd = mccCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INTER.T_MER_INFO.SUP_MER_ID
     *
     * @return the value of INTER.T_MER_INFO.SUP_MER_ID
     *
     * @mbggenerated Tue Oct 25 14:03:35 CST 2016
     */
    public String getSupMerId() {
        return supMerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INTER.T_MER_INFO.SUP_MER_ID
     *
     * @param supMerId the value for INTER.T_MER_INFO.SUP_MER_ID
     *
     * @mbggenerated Tue Oct 25 14:03:35 CST 2016
     */
    public void setSupMerId(String supMerId) {
        this.supMerId = supMerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INTER.T_MER_INFO.MGR_BRH_ID
     *
     * @return the value of INTER.T_MER_INFO.MGR_BRH_ID
     *
     * @mbggenerated Tue Oct 25 14:03:35 CST 2016
     */
    public String getMgrBrhId() {
        return mgrBrhId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INTER.T_MER_INFO.MGR_BRH_ID
     *
     * @param mgrBrhId the value for INTER.T_MER_INFO.MGR_BRH_ID
     *
     * @mbggenerated Tue Oct 25 14:03:35 CST 2016
     */
    public void setMgrBrhId(String mgrBrhId) {
        this.mgrBrhId = mgrBrhId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INTER.T_MER_INFO.ACQ_BRH_ID
     *
     * @return the value of INTER.T_MER_INFO.ACQ_BRH_ID
     *
     * @mbggenerated Tue Oct 25 14:03:35 CST 2016
     */
    public String getAcqBrhId() {
        return acqBrhId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INTER.T_MER_INFO.ACQ_BRH_ID
     *
     * @param acqBrhId the value for INTER.T_MER_INFO.ACQ_BRH_ID
     *
     * @mbggenerated Tue Oct 25 14:03:35 CST 2016
     */
    public void setAcqBrhId(String acqBrhId) {
        this.acqBrhId = acqBrhId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INTER.T_MER_INFO.LOC_NATION
     *
     * @return the value of INTER.T_MER_INFO.LOC_NATION
     *
     * @mbggenerated Tue Oct 25 14:03:35 CST 2016
     */
    public String getLocNation() {
        return locNation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INTER.T_MER_INFO.LOC_NATION
     *
     * @param locNation the value for INTER.T_MER_INFO.LOC_NATION
     *
     * @mbggenerated Tue Oct 25 14:03:35 CST 2016
     */
    public void setLocNation(String locNation) {
        this.locNation = locNation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INTER.T_MER_INFO.LOC_PROV
     *
     * @return the value of INTER.T_MER_INFO.LOC_PROV
     *
     * @mbggenerated Tue Oct 25 14:03:35 CST 2016
     */
    public String getLocProv() {
        return locProv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INTER.T_MER_INFO.LOC_PROV
     *
     * @param locProv the value for INTER.T_MER_INFO.LOC_PROV
     *
     * @mbggenerated Tue Oct 25 14:03:35 CST 2016
     */
    public void setLocProv(String locProv) {
        this.locProv = locProv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INTER.T_MER_INFO.LOC_CITY
     *
     * @return the value of INTER.T_MER_INFO.LOC_CITY
     *
     * @mbggenerated Tue Oct 25 14:03:35 CST 2016
     */
    public String getLocCity() {
        return locCity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INTER.T_MER_INFO.LOC_CITY
     *
     * @param locCity the value for INTER.T_MER_INFO.LOC_CITY
     *
     * @mbggenerated Tue Oct 25 14:03:35 CST 2016
     */
    public void setLocCity(String locCity) {
        this.locCity = locCity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INTER.T_MER_INFO.ADDR
     *
     * @return the value of INTER.T_MER_INFO.ADDR
     *
     * @mbggenerated Tue Oct 25 14:03:35 CST 2016
     */
    public String getAddr() {
        return addr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INTER.T_MER_INFO.ADDR
     *
     * @param addr the value for INTER.T_MER_INFO.ADDR
     *
     * @mbggenerated Tue Oct 25 14:03:35 CST 2016
     */
    public void setAddr(String addr) {
        this.addr = addr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INTER.T_MER_INFO.PERSON
     *
     * @return the value of INTER.T_MER_INFO.PERSON
     *
     * @mbggenerated Tue Oct 25 14:03:35 CST 2016
     */
    public String getPerson() {
        return person;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INTER.T_MER_INFO.PERSON
     *
     * @param person the value for INTER.T_MER_INFO.PERSON
     *
     * @mbggenerated Tue Oct 25 14:03:35 CST 2016
     */
    public void setPerson(String person) {
        this.person = person;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INTER.T_MER_INFO.TEL
     *
     * @return the value of INTER.T_MER_INFO.TEL
     *
     * @mbggenerated Tue Oct 25 14:03:35 CST 2016
     */
    public String getTel() {
        return tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INTER.T_MER_INFO.TEL
     *
     * @param tel the value for INTER.T_MER_INFO.TEL
     *
     * @mbggenerated Tue Oct 25 14:03:35 CST 2016
     */
    public void setTel(String tel) {
        this.tel = tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INTER.T_MER_INFO.FAX
     *
     * @return the value of INTER.T_MER_INFO.FAX
     *
     * @mbggenerated Tue Oct 25 14:03:35 CST 2016
     */
    public String getFax() {
        return fax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INTER.T_MER_INFO.FAX
     *
     * @param fax the value for INTER.T_MER_INFO.FAX
     *
     * @mbggenerated Tue Oct 25 14:03:35 CST 2016
     */
    public void setFax(String fax) {
        this.fax = fax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INTER.T_MER_INFO.EMAIL
     *
     * @return the value of INTER.T_MER_INFO.EMAIL
     *
     * @mbggenerated Tue Oct 25 14:03:35 CST 2016
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INTER.T_MER_INFO.EMAIL
     *
     * @param email the value for INTER.T_MER_INFO.EMAIL
     *
     * @mbggenerated Tue Oct 25 14:03:35 CST 2016
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INTER.T_MER_INFO.EM_PERSON_
     *
     * @return the value of INTER.T_MER_INFO.EM_PERSON_
     *
     * @mbggenerated Tue Oct 25 14:03:35 CST 2016
     */
    public String getEmPerson() {
        return emPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INTER.T_MER_INFO.EM_PERSON_
     *
     * @param emPerson the value for INTER.T_MER_INFO.EM_PERSON_
     *
     * @mbggenerated Tue Oct 25 14:03:35 CST 2016
     */
    public void setEmPerson(String emPerson) {
        this.emPerson = emPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INTER.T_MER_INFO.EM_TEL
     *
     * @return the value of INTER.T_MER_INFO.EM_TEL
     *
     * @mbggenerated Tue Oct 25 14:03:35 CST 2016
     */
    public String getEmTel() {
        return emTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INTER.T_MER_INFO.EM_TEL
     *
     * @param emTel the value for INTER.T_MER_INFO.EM_TEL
     *
     * @mbggenerated Tue Oct 25 14:03:35 CST 2016
     */
    public void setEmTel(String emTel) {
        this.emTel = emTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INTER.T_MER_INFO.CONTRACT_DT
     *
     * @return the value of INTER.T_MER_INFO.CONTRACT_DT
     *
     * @mbggenerated Tue Oct 25 14:03:35 CST 2016
     */
    public String getContractDt() {
        return contractDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INTER.T_MER_INFO.CONTRACT_DT
     *
     * @param contractDt the value for INTER.T_MER_INFO.CONTRACT_DT
     *
     * @mbggenerated Tue Oct 25 14:03:35 CST 2016
     */
    public void setContractDt(String contractDt) {
        this.contractDt = contractDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INTER.T_MER_INFO.EXPAND_INST
     *
     * @return the value of INTER.T_MER_INFO.EXPAND_INST
     *
     * @mbggenerated Tue Oct 25 14:03:35 CST 2016
     */
    public String getExpandInst() {
        return expandInst;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INTER.T_MER_INFO.EXPAND_INST
     *
     * @param expandInst the value for INTER.T_MER_INFO.EXPAND_INST
     *
     * @mbggenerated Tue Oct 25 14:03:35 CST 2016
     */
    public void setExpandInst(String expandInst) {
        this.expandInst = expandInst;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INTER.T_MER_INFO.EXPAND_PERSON
     *
     * @return the value of INTER.T_MER_INFO.EXPAND_PERSON
     *
     * @mbggenerated Tue Oct 25 14:03:35 CST 2016
     */
    public String getExpandPerson() {
        return expandPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INTER.T_MER_INFO.EXPAND_PERSON
     *
     * @param expandPerson the value for INTER.T_MER_INFO.EXPAND_PERSON
     *
     * @mbggenerated Tue Oct 25 14:03:35 CST 2016
     */
    public void setExpandPerson(String expandPerson) {
        this.expandPerson = expandPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INTER.T_MER_INFO.CUST_MGR
     *
     * @return the value of INTER.T_MER_INFO.CUST_MGR
     *
     * @mbggenerated Tue Oct 25 14:03:35 CST 2016
     */
    public String getCustMgr() {
        return custMgr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INTER.T_MER_INFO.CUST_MGR
     *
     * @param custMgr the value for INTER.T_MER_INFO.CUST_MGR
     *
     * @mbggenerated Tue Oct 25 14:03:35 CST 2016
     */
    public void setCustMgr(String custMgr) {
        this.custMgr = custMgr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INTER.T_MER_INFO.CUST_MGR_TEL
     *
     * @return the value of INTER.T_MER_INFO.CUST_MGR_TEL
     *
     * @mbggenerated Tue Oct 25 14:03:35 CST 2016
     */
    public String getCustMgrTel() {
        return custMgrTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INTER.T_MER_INFO.CUST_MGR_TEL
     *
     * @param custMgrTel the value for INTER.T_MER_INFO.CUST_MGR_TEL
     *
     * @mbggenerated Tue Oct 25 14:03:35 CST 2016
     */
    public void setCustMgrTel(String custMgrTel) {
        this.custMgrTel = custMgrTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INTER.T_MER_INFO.CUST_MGR_MOBILE
     *
     * @return the value of INTER.T_MER_INFO.CUST_MGR_MOBILE
     *
     * @mbggenerated Tue Oct 25 14:03:35 CST 2016
     */
    public String getCustMgrMobile() {
        return custMgrMobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INTER.T_MER_INFO.CUST_MGR_MOBILE
     *
     * @param custMgrMobile the value for INTER.T_MER_INFO.CUST_MGR_MOBILE
     *
     * @mbggenerated Tue Oct 25 14:03:35 CST 2016
     */
    public void setCustMgrMobile(String custMgrMobile) {
        this.custMgrMobile = custMgrMobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INTER.T_MER_INFO.STLMT_LEV
     *
     * @return the value of INTER.T_MER_INFO.STLMT_LEV
     *
     * @mbggenerated Tue Oct 25 14:03:35 CST 2016
     */
    public String getStlmtLev() {
        return stlmtLev;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INTER.T_MER_INFO.STLMT_LEV
     *
     * @param stlmtLev the value for INTER.T_MER_INFO.STLMT_LEV
     *
     * @mbggenerated Tue Oct 25 14:03:35 CST 2016
     */
    public void setStlmtLev(String stlmtLev) {
        this.stlmtLev = stlmtLev;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INTER.T_MER_INFO.STLMT_PERIOD
     *
     * @return the value of INTER.T_MER_INFO.STLMT_PERIOD
     *
     * @mbggenerated Tue Oct 25 14:03:35 CST 2016
     */
    public Short getStlmtPeriod() {
        return stlmtPeriod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INTER.T_MER_INFO.STLMT_PERIOD
     *
     * @param stlmtPeriod the value for INTER.T_MER_INFO.STLMT_PERIOD
     *
     * @mbggenerated Tue Oct 25 14:03:35 CST 2016
     */
    public void setStlmtPeriod(Short stlmtPeriod) {
        this.stlmtPeriod = stlmtPeriod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INTER.T_MER_INFO.STLMT_PERIOD_UNIT
     *
     * @return the value of INTER.T_MER_INFO.STLMT_PERIOD_UNIT
     *
     * @mbggenerated Tue Oct 25 14:03:35 CST 2016
     */
    public String getStlmtPeriodUnit() {
        return stlmtPeriodUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INTER.T_MER_INFO.STLMT_PERIOD_UNIT
     *
     * @param stlmtPeriodUnit the value for INTER.T_MER_INFO.STLMT_PERIOD_UNIT
     *
     * @mbggenerated Tue Oct 25 14:03:35 CST 2016
     */
    public void setStlmtPeriodUnit(String stlmtPeriodUnit) {
        this.stlmtPeriodUnit = stlmtPeriodUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INTER.T_MER_INFO.FEE_RATE
     *
     * @return the value of INTER.T_MER_INFO.FEE_RATE
     *
     * @mbggenerated Tue Oct 25 14:03:35 CST 2016
     */
    public String getFeeRate() {
        return feeRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INTER.T_MER_INFO.FEE_RATE
     *
     * @param feeRate the value for INTER.T_MER_INFO.FEE_RATE
     *
     * @mbggenerated Tue Oct 25 14:03:35 CST 2016
     */
    public void setFeeRate(String feeRate) {
        this.feeRate = feeRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INTER.T_MER_INFO.IN_ACCT_ID
     *
     * @return the value of INTER.T_MER_INFO.IN_ACCT_ID
     *
     * @mbggenerated Tue Oct 25 14:03:35 CST 2016
     */
    public String getInAcctId() {
        return inAcctId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INTER.T_MER_INFO.IN_ACCT_ID
     *
     * @param inAcctId the value for INTER.T_MER_INFO.IN_ACCT_ID
     *
     * @mbggenerated Tue Oct 25 14:03:35 CST 2016
     */
    public void setInAcctId(String inAcctId) {
        this.inAcctId = inAcctId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INTER.T_MER_INFO.IN_ACCT_NM
     *
     * @return the value of INTER.T_MER_INFO.IN_ACCT_NM
     *
     * @mbggenerated Tue Oct 25 14:03:35 CST 2016
     */
    public String getInAcctNm() {
        return inAcctNm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INTER.T_MER_INFO.IN_ACCT_NM
     *
     * @param inAcctNm the value for INTER.T_MER_INFO.IN_ACCT_NM
     *
     * @mbggenerated Tue Oct 25 14:03:35 CST 2016
     */
    public void setInAcctNm(String inAcctNm) {
        this.inAcctNm = inAcctNm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INTER.T_MER_INFO.OPEN_BANK_ID
     *
     * @return the value of INTER.T_MER_INFO.OPEN_BANK_ID
     *
     * @mbggenerated Tue Oct 25 14:03:35 CST 2016
     */
    public String getOpenBankId() {
        return openBankId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INTER.T_MER_INFO.OPEN_BANK_ID
     *
     * @param openBankId the value for INTER.T_MER_INFO.OPEN_BANK_ID
     *
     * @mbggenerated Tue Oct 25 14:03:35 CST 2016
     */
    public void setOpenBankId(String openBankId) {
        this.openBankId = openBankId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INTER.T_MER_INFO.OPEN_BANK_NM
     *
     * @return the value of INTER.T_MER_INFO.OPEN_BANK_NM
     *
     * @mbggenerated Tue Oct 25 14:03:35 CST 2016
     */
    public String getOpenBankNm() {
        return openBankNm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INTER.T_MER_INFO.OPEN_BANK_NM
     *
     * @param openBankNm the value for INTER.T_MER_INFO.OPEN_BANK_NM
     *
     * @mbggenerated Tue Oct 25 14:03:35 CST 2016
     */
    public void setOpenBankNm(String openBankNm) {
        this.openBankNm = openBankNm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INTER.T_MER_INFO.OUT_ACCT_ID
     *
     * @return the value of INTER.T_MER_INFO.OUT_ACCT_ID
     *
     * @mbggenerated Tue Oct 25 14:03:35 CST 2016
     */
    public String getOutAcctId() {
        return outAcctId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INTER.T_MER_INFO.OUT_ACCT_ID
     *
     * @param outAcctId the value for INTER.T_MER_INFO.OUT_ACCT_ID
     *
     * @mbggenerated Tue Oct 25 14:03:35 CST 2016
     */
    public void setOutAcctId(String outAcctId) {
        this.outAcctId = outAcctId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INTER.T_MER_INFO.OUT_ACCT_NM
     *
     * @return the value of INTER.T_MER_INFO.OUT_ACCT_NM
     *
     * @mbggenerated Tue Oct 25 14:03:35 CST 2016
     */
    public String getOutAcctNm() {
        return outAcctNm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INTER.T_MER_INFO.OUT_ACCT_NM
     *
     * @param outAcctNm the value for INTER.T_MER_INFO.OUT_ACCT_NM
     *
     * @mbggenerated Tue Oct 25 14:03:35 CST 2016
     */
    public void setOutAcctNm(String outAcctNm) {
        this.outAcctNm = outAcctNm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INTER.T_MER_INFO.SUB_KEY_CD
     *
     * @return the value of INTER.T_MER_INFO.SUB_KEY_CD
     *
     * @mbggenerated Tue Oct 25 14:03:35 CST 2016
     */
    public String getSubKeyCd() {
        return subKeyCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INTER.T_MER_INFO.SUB_KEY_CD
     *
     * @param subKeyCd the value for INTER.T_MER_INFO.SUB_KEY_CD
     *
     * @mbggenerated Tue Oct 25 14:03:35 CST 2016
     */
    public void setSubKeyCd(String subKeyCd) {
        this.subKeyCd = subKeyCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INTER.T_MER_INFO.TYPE_CD
     *
     * @return the value of INTER.T_MER_INFO.TYPE_CD
     *
     * @mbggenerated Tue Oct 25 14:03:35 CST 2016
     */
    public String getTypeCd() {
        return typeCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INTER.T_MER_INFO.TYPE_CD
     *
     * @param typeCd the value for INTER.T_MER_INFO.TYPE_CD
     *
     * @mbggenerated Tue Oct 25 14:03:35 CST 2016
     */
    public void setTypeCd(String typeCd) {
        this.typeCd = typeCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INTER.T_MER_INFO.RISK_RANK
     *
     * @return the value of INTER.T_MER_INFO.RISK_RANK
     *
     * @mbggenerated Tue Oct 25 14:03:35 CST 2016
     */
    public String getRiskRank() {
        return riskRank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INTER.T_MER_INFO.RISK_RANK
     *
     * @param riskRank the value for INTER.T_MER_INFO.RISK_RANK
     *
     * @mbggenerated Tue Oct 25 14:03:35 CST 2016
     */
    public void setRiskRank(String riskRank) {
        this.riskRank = riskRank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INTER.T_MER_INFO.MIS_FLG
     *
     * @return the value of INTER.T_MER_INFO.MIS_FLG
     *
     * @mbggenerated Tue Oct 25 14:03:35 CST 2016
     */
    public String getMisFlg() {
        return misFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INTER.T_MER_INFO.MIS_FLG
     *
     * @param misFlg the value for INTER.T_MER_INFO.MIS_FLG
     *
     * @mbggenerated Tue Oct 25 14:03:35 CST 2016
     */
    public void setMisFlg(String misFlg) {
        this.misFlg = misFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INTER.T_MER_INFO.SYM_STR
     *
     * @return the value of INTER.T_MER_INFO.SYM_STR
     *
     * @mbggenerated Tue Oct 25 14:03:35 CST 2016
     */
    public String getSymStr() {
        return symStr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INTER.T_MER_INFO.SYM_STR
     *
     * @param symStr the value for INTER.T_MER_INFO.SYM_STR
     *
     * @mbggenerated Tue Oct 25 14:03:35 CST 2016
     */
    public void setSymStr(String symStr) {
        this.symStr = symStr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INTER.T_MER_INFO.STA
     *
     * @return the value of INTER.T_MER_INFO.STA
     *
     * @mbggenerated Tue Oct 25 14:03:35 CST 2016
     */
    public String getSta() {
        return sta;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INTER.T_MER_INFO.STA
     *
     * @param sta the value for INTER.T_MER_INFO.STA
     *
     * @mbggenerated Tue Oct 25 14:03:35 CST 2016
     */
    public void setSta(String sta) {
        this.sta = sta;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INTER.T_MER_INFO.CHK_STA
     *
     * @return the value of INTER.T_MER_INFO.CHK_STA
     *
     * @mbggenerated Tue Oct 25 14:03:35 CST 2016
     */
    public String getChkSta() {
        return chkSta;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INTER.T_MER_INFO.CHK_STA
     *
     * @param chkSta the value for INTER.T_MER_INFO.CHK_STA
     *
     * @mbggenerated Tue Oct 25 14:03:35 CST 2016
     */
    public void setChkSta(String chkSta) {
        this.chkSta = chkSta;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INTER.T_MER_INFO.SIGN_STA
     *
     * @return the value of INTER.T_MER_INFO.SIGN_STA
     *
     * @mbggenerated Tue Oct 25 14:03:35 CST 2016
     */
    public String getSignSta() {
        return signSta;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INTER.T_MER_INFO.SIGN_STA
     *
     * @param signSta the value for INTER.T_MER_INFO.SIGN_STA
     *
     * @mbggenerated Tue Oct 25 14:03:35 CST 2016
     */
    public void setSignSta(String signSta) {
        this.signSta = signSta;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INTER.T_MER_INFO.CRT_DT
     *
     * @return the value of INTER.T_MER_INFO.CRT_DT
     *
     * @mbggenerated Tue Oct 25 14:03:35 CST 2016
     */
    public String getCrtDt() {
        return crtDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INTER.T_MER_INFO.CRT_DT
     *
     * @param crtDt the value for INTER.T_MER_INFO.CRT_DT
     *
     * @mbggenerated Tue Oct 25 14:03:35 CST 2016
     */
    public void setCrtDt(String crtDt) {
        this.crtDt = crtDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INTER.T_MER_INFO.MISC_TX
     *
     * @return the value of INTER.T_MER_INFO.MISC_TX
     *
     * @mbggenerated Tue Oct 25 14:03:35 CST 2016
     */
    public String getMiscTx() {
        return miscTx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INTER.T_MER_INFO.MISC_TX
     *
     * @param miscTx the value for INTER.T_MER_INFO.MISC_TX
     *
     * @mbggenerated Tue Oct 25 14:03:35 CST 2016
     */
    public void setMiscTx(String miscTx) {
        this.miscTx = miscTx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INTER.T_MER_INFO.LAST_UPD_BRH_ID
     *
     * @return the value of INTER.T_MER_INFO.LAST_UPD_BRH_ID
     *
     * @mbggenerated Tue Oct 25 14:03:35 CST 2016
     */
    public String getLastUpdBrhId() {
        return lastUpdBrhId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INTER.T_MER_INFO.LAST_UPD_BRH_ID
     *
     * @param lastUpdBrhId the value for INTER.T_MER_INFO.LAST_UPD_BRH_ID
     *
     * @mbggenerated Tue Oct 25 14:03:35 CST 2016
     */
    public void setLastUpdBrhId(String lastUpdBrhId) {
        this.lastUpdBrhId = lastUpdBrhId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INTER.T_MER_INFO.LAST_UPD_OPR_ID
     *
     * @return the value of INTER.T_MER_INFO.LAST_UPD_OPR_ID
     *
     * @mbggenerated Tue Oct 25 14:03:35 CST 2016
     */
    public String getLastUpdOprId() {
        return lastUpdOprId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INTER.T_MER_INFO.LAST_UPD_OPR_ID
     *
     * @param lastUpdOprId the value for INTER.T_MER_INFO.LAST_UPD_OPR_ID
     *
     * @mbggenerated Tue Oct 25 14:03:35 CST 2016
     */
    public void setLastUpdOprId(String lastUpdOprId) {
        this.lastUpdOprId = lastUpdOprId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INTER.T_MER_INFO.LAST_UPD_TXN_CD
     *
     * @return the value of INTER.T_MER_INFO.LAST_UPD_TXN_CD
     *
     * @mbggenerated Tue Oct 25 14:03:35 CST 2016
     */
    public String getLastUpdTxnCd() {
        return lastUpdTxnCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INTER.T_MER_INFO.LAST_UPD_TXN_CD
     *
     * @param lastUpdTxnCd the value for INTER.T_MER_INFO.LAST_UPD_TXN_CD
     *
     * @mbggenerated Tue Oct 25 14:03:35 CST 2016
     */
    public void setLastUpdTxnCd(String lastUpdTxnCd) {
        this.lastUpdTxnCd = lastUpdTxnCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INTER.T_MER_INFO.LAST_UPD_TS
     *
     * @return the value of INTER.T_MER_INFO.LAST_UPD_TS
     *
     * @mbggenerated Tue Oct 25 14:03:35 CST 2016
     */
    public Date getLastUpdTs() {
        return lastUpdTs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INTER.T_MER_INFO.LAST_UPD_TS
     *
     * @param lastUpdTs the value for INTER.T_MER_INFO.LAST_UPD_TS
     *
     * @mbggenerated Tue Oct 25 14:03:35 CST 2016
     */
    public void setLastUpdTs(Date lastUpdTs) {
        this.lastUpdTs = lastUpdTs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INTER.T_MER_INFO.STL_CUR
     *
     * @return the value of INTER.T_MER_INFO.STL_CUR
     *
     * @mbggenerated Tue Oct 25 14:03:35 CST 2016
     */
    public String getStlCur() {
        return stlCur;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INTER.T_MER_INFO.STL_CUR
     *
     * @param stlCur the value for INTER.T_MER_INFO.STL_CUR
     *
     * @mbggenerated Tue Oct 25 14:03:35 CST 2016
     */
    public void setStlCur(String stlCur) {
        this.stlCur = stlCur;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INTER.T_MER_INFO.STLMT_MIN
     *
     * @return the value of INTER.T_MER_INFO.STLMT_MIN
     *
     * @mbggenerated Tue Oct 25 14:03:35 CST 2016
     */
    public String getStlmtMin() {
        return stlmtMin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INTER.T_MER_INFO.STLMT_MIN
     *
     * @param stlmtMin the value for INTER.T_MER_INFO.STLMT_MIN
     *
     * @mbggenerated Tue Oct 25 14:03:35 CST 2016
     */
    public void setStlmtMin(String stlmtMin) {
        this.stlmtMin = stlmtMin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INTER.T_MER_INFO.LOC_P
     *
     * @return the value of INTER.T_MER_INFO.LOC_P
     *
     * @mbggenerated Tue Oct 25 14:03:35 CST 2016
     */
    public String getLocP() {
        return locP;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INTER.T_MER_INFO.LOC_P
     *
     * @param locP the value for INTER.T_MER_INFO.LOC_P
     *
     * @mbggenerated Tue Oct 25 14:03:35 CST 2016
     */
    public void setLocP(String locP) {
        this.locP = locP;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INTER.T_MER_INFO.LOC_C
     *
     * @return the value of INTER.T_MER_INFO.LOC_C
     *
     * @mbggenerated Tue Oct 25 14:03:35 CST 2016
     */
    public String getLocC() {
        return locC;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INTER.T_MER_INFO.LOC_C
     *
     * @param locC the value for INTER.T_MER_INFO.LOC_C
     *
     * @mbggenerated Tue Oct 25 14:03:35 CST 2016
     */
    public void setLocC(String locC) {
        this.locC = locC;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INTER.T_MER_INFO.LOC_R
     *
     * @return the value of INTER.T_MER_INFO.LOC_R
     *
     * @mbggenerated Tue Oct 25 14:03:35 CST 2016
     */
    public String getLocR() {
        return locR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INTER.T_MER_INFO.LOC_R
     *
     * @param locR the value for INTER.T_MER_INFO.LOC_R
     *
     * @mbggenerated Tue Oct 25 14:03:35 CST 2016
     */
    public void setLocR(String locR) {
        this.locR = locR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INTER.T_MER_INFO.LOC_A
     *
     * @return the value of INTER.T_MER_INFO.LOC_A
     *
     * @mbggenerated Tue Oct 25 14:03:35 CST 2016
     */
    public String getLocA() {
        return locA;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INTER.T_MER_INFO.LOC_A
     *
     * @param locA the value for INTER.T_MER_INFO.LOC_A
     *
     * @mbggenerated Tue Oct 25 14:03:35 CST 2016
     */
    public void setLocA(String locA) {
        this.locA = locA;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INTER.T_MER_INFO.REJECT_MSG
     *
     * @return the value of INTER.T_MER_INFO.REJECT_MSG
     *
     * @mbggenerated Tue Oct 25 14:03:35 CST 2016
     */
    public String getRejectMsg() {
        return rejectMsg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INTER.T_MER_INFO.REJECT_MSG
     *
     * @param rejectMsg the value for INTER.T_MER_INFO.REJECT_MSG
     *
     * @mbggenerated Tue Oct 25 14:03:35 CST 2016
     */
    public void setRejectMsg(String rejectMsg) {
        this.rejectMsg = rejectMsg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INTER.T_MER_INFO.SMS_CHECK
     *
     * @return the value of INTER.T_MER_INFO.SMS_CHECK
     *
     * @mbggenerated Tue Oct 25 14:03:35 CST 2016
     */
    public String getSmsCheck() {
        return smsCheck;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INTER.T_MER_INFO.SMS_CHECK
     *
     * @param smsCheck the value for INTER.T_MER_INFO.SMS_CHECK
     *
     * @mbggenerated Tue Oct 25 14:03:35 CST 2016
     */
    public void setSmsCheck(String smsCheck) {
        this.smsCheck = smsCheck;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INTER.T_MER_INFO.COUNTRY_AREA_CD
     *
     * @return the value of INTER.T_MER_INFO.COUNTRY_AREA_CD
     *
     * @mbggenerated Tue Oct 25 14:03:35 CST 2016
     */
    public String getCountryAreaCd() {
        return countryAreaCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INTER.T_MER_INFO.COUNTRY_AREA_CD
     *
     * @param countryAreaCd the value for INTER.T_MER_INFO.COUNTRY_AREA_CD
     *
     * @mbggenerated Tue Oct 25 14:03:35 CST 2016
     */
    public void setCountryAreaCd(String countryAreaCd) {
        this.countryAreaCd = countryAreaCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INTER.T_MER_INFO.POS_RECEIPT_NAME
     *
     * @return the value of INTER.T_MER_INFO.POS_RECEIPT_NAME
     *
     * @mbggenerated Tue Oct 25 14:03:35 CST 2016
     */
    public String getPosReceiptName() {
        return posReceiptName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INTER.T_MER_INFO.POS_RECEIPT_NAME
     *
     * @param posReceiptName the value for INTER.T_MER_INFO.POS_RECEIPT_NAME
     *
     * @mbggenerated Tue Oct 25 14:03:35 CST 2016
     */
    public void setPosReceiptName(String posReceiptName) {
        this.posReceiptName = posReceiptName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INTER.T_MER_INFO.FILE_ID
     *
     * @return the value of INTER.T_MER_INFO.FILE_ID
     *
     * @mbggenerated Tue Oct 25 14:03:35 CST 2016
     */
    public BigDecimal getFileId() {
        return fileId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INTER.T_MER_INFO.FILE_ID
     *
     * @param fileId the value for INTER.T_MER_INFO.FILE_ID
     *
     * @mbggenerated Tue Oct 25 14:03:35 CST 2016
     */
    public void setFileId(BigDecimal fileId) {
        this.fileId = fileId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INTER.T_MER_INFO.IDCARD_BACK_FILEID
     *
     * @return the value of INTER.T_MER_INFO.IDCARD_BACK_FILEID
     *
     * @mbggenerated Tue Oct 25 14:03:35 CST 2016
     */
    public BigDecimal getIdcardBackFileid() {
        return idcardBackFileid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INTER.T_MER_INFO.IDCARD_BACK_FILEID
     *
     * @param idcardBackFileid the value for INTER.T_MER_INFO.IDCARD_BACK_FILEID
     *
     * @mbggenerated Tue Oct 25 14:03:35 CST 2016
     */
    public void setIdcardBackFileid(BigDecimal idcardBackFileid) {
        this.idcardBackFileid = idcardBackFileid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INTER.T_MER_INFO.IDCARD_APPLICATION_FILEID
     *
     * @return the value of INTER.T_MER_INFO.IDCARD_APPLICATION_FILEID
     *
     * @mbggenerated Tue Oct 25 14:03:35 CST 2016
     */
    public BigDecimal getIdcardApplicationFileid() {
        return idcardApplicationFileid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INTER.T_MER_INFO.IDCARD_APPLICATION_FILEID
     *
     * @param idcardApplicationFileid the value for INTER.T_MER_INFO.IDCARD_APPLICATION_FILEID
     *
     * @mbggenerated Tue Oct 25 14:03:35 CST 2016
     */
    public void setIdcardApplicationFileid(BigDecimal idcardApplicationFileid) {
        this.idcardApplicationFileid = idcardApplicationFileid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INTER.T_MER_INFO.LOGO_FILE_ID
     *
     * @return the value of INTER.T_MER_INFO.LOGO_FILE_ID
     *
     * @mbggenerated Tue Oct 25 14:03:35 CST 2016
     */
    public BigDecimal getLogoFileId() {
        return logoFileId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INTER.T_MER_INFO.LOGO_FILE_ID
     *
     * @param logoFileId the value for INTER.T_MER_INFO.LOGO_FILE_ID
     *
     * @mbggenerated Tue Oct 25 14:03:35 CST 2016
     */
    public void setLogoFileId(BigDecimal logoFileId) {
        this.logoFileId = logoFileId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INTER.T_MER_INFO.BIND_TIMESTAMP
     *
     * @return the value of INTER.T_MER_INFO.BIND_TIMESTAMP
     *
     * @mbggenerated Tue Oct 25 14:03:35 CST 2016
     */
    public Date getBindTimestamp() {
        return bindTimestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INTER.T_MER_INFO.BIND_TIMESTAMP
     *
     * @param bindTimestamp the value for INTER.T_MER_INFO.BIND_TIMESTAMP
     *
     * @mbggenerated Tue Oct 25 14:03:35 CST 2016
     */
    public void setBindTimestamp(Date bindTimestamp) {
        this.bindTimestamp = bindTimestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INTER.T_MER_INFO.LMF_FIXED_AMT
     *
     * @return the value of INTER.T_MER_INFO.LMF_FIXED_AMT
     *
     * @mbggenerated Tue Oct 25 14:03:35 CST 2016
     */
    public String getLmfFixedAmt() {
        return lmfFixedAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INTER.T_MER_INFO.LMF_FIXED_AMT
     *
     * @param lmfFixedAmt the value for INTER.T_MER_INFO.LMF_FIXED_AMT
     *
     * @mbggenerated Tue Oct 25 14:03:35 CST 2016
     */
    public void setLmfFixedAmt(String lmfFixedAmt) {
        this.lmfFixedAmt = lmfFixedAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INTER.T_MER_INFO.LMF_FIXED_AMT_FLG
     *
     * @return the value of INTER.T_MER_INFO.LMF_FIXED_AMT_FLG
     *
     * @mbggenerated Tue Oct 25 14:03:35 CST 2016
     */
    public String getLmfFixedAmtFlg() {
        return lmfFixedAmtFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INTER.T_MER_INFO.LMF_FIXED_AMT_FLG
     *
     * @param lmfFixedAmtFlg the value for INTER.T_MER_INFO.LMF_FIXED_AMT_FLG
     *
     * @mbggenerated Tue Oct 25 14:03:35 CST 2016
     */
    public void setLmfFixedAmtFlg(String lmfFixedAmtFlg) {
        this.lmfFixedAmtFlg = lmfFixedAmtFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INTER.T_MER_INFO.BUSINESS_CATEGORY
     *
     * @return the value of INTER.T_MER_INFO.BUSINESS_CATEGORY
     *
     * @mbggenerated Tue Oct 25 14:03:35 CST 2016
     */
    public String getBusinessCategory() {
        return businessCategory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INTER.T_MER_INFO.BUSINESS_CATEGORY
     *
     * @param businessCategory the value for INTER.T_MER_INFO.BUSINESS_CATEGORY
     *
     * @mbggenerated Tue Oct 25 14:03:35 CST 2016
     */
    public void setBusinessCategory(String businessCategory) {
        this.businessCategory = businessCategory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INTER.T_MER_INFO.FEE_RATE_FLAG
     *
     * @return the value of INTER.T_MER_INFO.FEE_RATE_FLAG
     *
     * @mbggenerated Tue Oct 25 14:03:35 CST 2016
     */
    public String getFeeRateFlag() {
        return feeRateFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INTER.T_MER_INFO.FEE_RATE_FLAG
     *
     * @param feeRateFlag the value for INTER.T_MER_INFO.FEE_RATE_FLAG
     *
     * @mbggenerated Tue Oct 25 14:03:35 CST 2016
     */
    public void setFeeRateFlag(String feeRateFlag) {
        this.feeRateFlag = feeRateFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INTER.T_MER_INFO.D0_FLAG
     *
     * @return the value of INTER.T_MER_INFO.D0_FLAG
     *
     * @mbggenerated Tue Oct 25 14:03:35 CST 2016
     */
    public String getD0Flag() {
        return d0Flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INTER.T_MER_INFO.D0_FLAG
     *
     * @param d0Flag the value for INTER.T_MER_INFO.D0_FLAG
     *
     * @mbggenerated Tue Oct 25 14:03:35 CST 2016
     */
    public void setD0Flag(String d0Flag) {
        this.d0Flag = d0Flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INTER.T_MER_INFO.IN_ACCT_TYPE
     *
     * @return the value of INTER.T_MER_INFO.IN_ACCT_TYPE
     *
     * @mbggenerated Tue Oct 25 14:03:35 CST 2016
     */
    public String getInAcctType() {
        return inAcctType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INTER.T_MER_INFO.IN_ACCT_TYPE
     *
     * @param inAcctType the value for INTER.T_MER_INFO.IN_ACCT_TYPE
     *
     * @mbggenerated Tue Oct 25 14:03:35 CST 2016
     */
    public void setInAcctType(String inAcctType) {
        this.inAcctType = inAcctType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INTER.T_MER_INFO.CHECK_TIMESTAMP
     *
     * @return the value of INTER.T_MER_INFO.CHECK_TIMESTAMP
     *
     * @mbggenerated Tue Oct 25 14:03:35 CST 2016
     */
    public Date getCheckTimestamp() {
        return checkTimestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INTER.T_MER_INFO.CHECK_TIMESTAMP
     *
     * @param checkTimestamp the value for INTER.T_MER_INFO.CHECK_TIMESTAMP
     *
     * @mbggenerated Tue Oct 25 14:03:35 CST 2016
     */
    public void setCheckTimestamp(Date checkTimestamp) {
        this.checkTimestamp = checkTimestamp;
    }
}