package cn.koolyun.model;

import java.util.Date;

public class Tpayment {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INTER.T_PAYMENT.PAY_ID
     *
     * @mbggenerated Mon Oct 24 16:36:56 CST 2016
     */
    private String payId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INTER.T_PAYMENT.BRH_ID
     *
     * @mbggenerated Mon Oct 24 16:36:56 CST 2016
     */
    private String brhId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INTER.T_PAYMENT.PROD_NO
     *
     * @mbggenerated Mon Oct 24 16:36:56 CST 2016
     */
    private String prodNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INTER.T_PAYMENT.PAY_TYPE
     *
     * @mbggenerated Mon Oct 24 16:36:56 CST 2016
     */
    private String payType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INTER.T_PAYMENT.PAY_STAT
     *
     * @mbggenerated Mon Oct 24 16:36:56 CST 2016
     */
    private String payStat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INTER.T_PAYMENT.PAY_NAME
     *
     * @mbggenerated Mon Oct 24 16:36:56 CST 2016
     */
    private String payName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INTER.T_PAYMENT.DL_NAME
     *
     * @mbggenerated Mon Oct 24 16:36:56 CST 2016
     */
    private String dlName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INTER.T_PAYMENT.ENG_NAME
     *
     * @mbggenerated Mon Oct 24 16:36:56 CST 2016
     */
    private String engName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INTER.T_PAYMENT.PGL_FLAG
     *
     * @mbggenerated Mon Oct 24 16:36:56 CST 2016
     */
    private String pglFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INTER.T_PAYMENT.ALL_FLAG
     *
     * @mbggenerated Mon Oct 24 16:36:56 CST 2016
     */
    private String allFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INTER.T_PAYMENT.PAY_AREA
     *
     * @mbggenerated Mon Oct 24 16:36:56 CST 2016
     */
    private String payArea;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INTER.T_PAYMENT.PAY_MNG_INST
     *
     * @mbggenerated Mon Oct 24 16:36:56 CST 2016
     */
    private String payMngInst;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INTER.T_PAYMENT.PAY_CR_TIME
     *
     * @mbggenerated Mon Oct 24 16:36:56 CST 2016
     */
    private Date payCrTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INTER.T_PAYMENT.PAY_CR_TEL
     *
     * @mbggenerated Mon Oct 24 16:36:56 CST 2016
     */
    private String payCrTel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INTER.T_PAYMENT.BEGIN_DATE
     *
     * @mbggenerated Mon Oct 24 16:36:56 CST 2016
     */
    private String beginDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INTER.T_PAYMENT.END_DATE
     *
     * @mbggenerated Mon Oct 24 16:36:56 CST 2016
     */
    private String endDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INTER.T_PAYMENT.MIN_AMT
     *
     * @mbggenerated Mon Oct 24 16:36:56 CST 2016
     */
    private String minAmt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INTER.T_PAYMENT.MAX_AMT
     *
     * @mbggenerated Mon Oct 24 16:36:56 CST 2016
     */
    private String maxAmt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INTER.T_PAYMENT.MIN_BAL
     *
     * @mbggenerated Mon Oct 24 16:36:56 CST 2016
     */
    private String minBal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INTER.T_PAYMENT.MAX_BAL
     *
     * @mbggenerated Mon Oct 24 16:36:56 CST 2016
     */
    private String maxBal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INTER.T_PAYMENT.PM_RULE_INDEX
     *
     * @mbggenerated Mon Oct 24 16:36:56 CST 2016
     */
    private String pmRuleIndex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INTER.T_PAYMENT.KEY_INDEX
     *
     * @mbggenerated Mon Oct 24 16:36:56 CST 2016
     */
    private String keyIndex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INTER.T_PAYMENT.MSG_TYPE
     *
     * @mbggenerated Mon Oct 24 16:36:56 CST 2016
     */
    private String msgType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INTER.T_PAYMENT.CLASSES
     *
     * @mbggenerated Mon Oct 24 16:36:56 CST 2016
     */
    private String classes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INTER.T_PAYMENT.CONTENT
     *
     * @mbggenerated Mon Oct 24 16:36:56 CST 2016
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INTER.T_PAYMENT.PAYMENT_ICON
     *
     * @mbggenerated Mon Oct 24 16:36:56 CST 2016
     */
    private String paymentIcon;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INTER.T_PAYMENT.TXN_TEMPLATE
     *
     * @mbggenerated Mon Oct 24 16:36:56 CST 2016
     */
    private String txnTemplate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INTER.T_PAYMENT.MISC
     *
     * @mbggenerated Mon Oct 24 16:36:56 CST 2016
     */
    private String misc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INTER.T_PAYMENT.BAK1
     *
     * @mbggenerated Mon Oct 24 16:36:56 CST 2016
     */
    private String bak1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INTER.T_PAYMENT.BAK2
     *
     * @mbggenerated Mon Oct 24 16:36:56 CST 2016
     */
    private String bak2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INTER.T_PAYMENT.LAST_UPD_BRH_ID
     *
     * @mbggenerated Mon Oct 24 16:36:56 CST 2016
     */
    private String lastUpdBrhId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INTER.T_PAYMENT.LAST_UPD_OPR_ID
     *
     * @mbggenerated Mon Oct 24 16:36:56 CST 2016
     */
    private String lastUpdOprId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INTER.T_PAYMENT.LAST_UPD_TXN_CD
     *
     * @mbggenerated Mon Oct 24 16:36:56 CST 2016
     */
    private String lastUpdTxnCd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INTER.T_PAYMENT.LAST_UPD_TS
     *
     * @mbggenerated Mon Oct 24 16:36:56 CST 2016
     */
    private Date lastUpdTs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INTER.T_PAYMENT.PRINT_TYPE
     *
     * @mbggenerated Mon Oct 24 16:36:56 CST 2016
     */
    private String printType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INTER.T_PAYMENT.CHNL_CLASS
     *
     * @mbggenerated Mon Oct 24 16:36:56 CST 2016
     */
    private String chnlClass;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INTER.T_PAYMENT.ORDER_NUM
     *
     * @mbggenerated Mon Oct 24 16:36:56 CST 2016
     */
    private Integer orderNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INTER.T_PAYMENT.MSG_DESTINATION
     *
     * @mbggenerated Mon Oct 24 16:36:56 CST 2016
     */
    private String msgDestination;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INTER.T_PAYMENT.MSG_SEND_TYPE
     *
     * @mbggenerated Mon Oct 24 16:36:56 CST 2016
     */
    private String msgSendType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INTER.T_PAYMENT.UPDATE_AMT_FLAG
     *
     * @mbggenerated Mon Oct 24 16:36:56 CST 2016
     */
    private String updateAmtFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INTER.T_PAYMENT.RECEIPT_PAY_CHNL
     *
     * @mbggenerated Mon Oct 24 16:36:56 CST 2016
     */
    private String receiptPayChnl;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INTER.T_PAYMENT.PAY_ID
     *
     * @return the value of INTER.T_PAYMENT.PAY_ID
     *
     * @mbggenerated Mon Oct 24 16:36:56 CST 2016
     */
    public String getPayId() {
        return payId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INTER.T_PAYMENT.PAY_ID
     *
     * @param payId the value for INTER.T_PAYMENT.PAY_ID
     *
     * @mbggenerated Mon Oct 24 16:36:56 CST 2016
     */
    public void setPayId(String payId) {
        this.payId = payId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INTER.T_PAYMENT.BRH_ID
     *
     * @return the value of INTER.T_PAYMENT.BRH_ID
     *
     * @mbggenerated Mon Oct 24 16:36:56 CST 2016
     */
    public String getBrhId() {
        return brhId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INTER.T_PAYMENT.BRH_ID
     *
     * @param brhId the value for INTER.T_PAYMENT.BRH_ID
     *
     * @mbggenerated Mon Oct 24 16:36:56 CST 2016
     */
    public void setBrhId(String brhId) {
        this.brhId = brhId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INTER.T_PAYMENT.PROD_NO
     *
     * @return the value of INTER.T_PAYMENT.PROD_NO
     *
     * @mbggenerated Mon Oct 24 16:36:56 CST 2016
     */
    public String getProdNo() {
        return prodNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INTER.T_PAYMENT.PROD_NO
     *
     * @param prodNo the value for INTER.T_PAYMENT.PROD_NO
     *
     * @mbggenerated Mon Oct 24 16:36:56 CST 2016
     */
    public void setProdNo(String prodNo) {
        this.prodNo = prodNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INTER.T_PAYMENT.PAY_TYPE
     *
     * @return the value of INTER.T_PAYMENT.PAY_TYPE
     *
     * @mbggenerated Mon Oct 24 16:36:56 CST 2016
     */
    public String getPayType() {
        return payType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INTER.T_PAYMENT.PAY_TYPE
     *
     * @param payType the value for INTER.T_PAYMENT.PAY_TYPE
     *
     * @mbggenerated Mon Oct 24 16:36:56 CST 2016
     */
    public void setPayType(String payType) {
        this.payType = payType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INTER.T_PAYMENT.PAY_STAT
     *
     * @return the value of INTER.T_PAYMENT.PAY_STAT
     *
     * @mbggenerated Mon Oct 24 16:36:56 CST 2016
     */
    public String getPayStat() {
        return payStat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INTER.T_PAYMENT.PAY_STAT
     *
     * @param payStat the value for INTER.T_PAYMENT.PAY_STAT
     *
     * @mbggenerated Mon Oct 24 16:36:56 CST 2016
     */
    public void setPayStat(String payStat) {
        this.payStat = payStat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INTER.T_PAYMENT.PAY_NAME
     *
     * @return the value of INTER.T_PAYMENT.PAY_NAME
     *
     * @mbggenerated Mon Oct 24 16:36:56 CST 2016
     */
    public String getPayName() {
        return payName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INTER.T_PAYMENT.PAY_NAME
     *
     * @param payName the value for INTER.T_PAYMENT.PAY_NAME
     *
     * @mbggenerated Mon Oct 24 16:36:56 CST 2016
     */
    public void setPayName(String payName) {
        this.payName = payName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INTER.T_PAYMENT.DL_NAME
     *
     * @return the value of INTER.T_PAYMENT.DL_NAME
     *
     * @mbggenerated Mon Oct 24 16:36:56 CST 2016
     */
    public String getDlName() {
        return dlName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INTER.T_PAYMENT.DL_NAME
     *
     * @param dlName the value for INTER.T_PAYMENT.DL_NAME
     *
     * @mbggenerated Mon Oct 24 16:36:56 CST 2016
     */
    public void setDlName(String dlName) {
        this.dlName = dlName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INTER.T_PAYMENT.ENG_NAME
     *
     * @return the value of INTER.T_PAYMENT.ENG_NAME
     *
     * @mbggenerated Mon Oct 24 16:36:56 CST 2016
     */
    public String getEngName() {
        return engName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INTER.T_PAYMENT.ENG_NAME
     *
     * @param engName the value for INTER.T_PAYMENT.ENG_NAME
     *
     * @mbggenerated Mon Oct 24 16:36:56 CST 2016
     */
    public void setEngName(String engName) {
        this.engName = engName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INTER.T_PAYMENT.PGL_FLAG
     *
     * @return the value of INTER.T_PAYMENT.PGL_FLAG
     *
     * @mbggenerated Mon Oct 24 16:36:56 CST 2016
     */
    public String getPglFlag() {
        return pglFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INTER.T_PAYMENT.PGL_FLAG
     *
     * @param pglFlag the value for INTER.T_PAYMENT.PGL_FLAG
     *
     * @mbggenerated Mon Oct 24 16:36:56 CST 2016
     */
    public void setPglFlag(String pglFlag) {
        this.pglFlag = pglFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INTER.T_PAYMENT.ALL_FLAG
     *
     * @return the value of INTER.T_PAYMENT.ALL_FLAG
     *
     * @mbggenerated Mon Oct 24 16:36:56 CST 2016
     */
    public String getAllFlag() {
        return allFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INTER.T_PAYMENT.ALL_FLAG
     *
     * @param allFlag the value for INTER.T_PAYMENT.ALL_FLAG
     *
     * @mbggenerated Mon Oct 24 16:36:56 CST 2016
     */
    public void setAllFlag(String allFlag) {
        this.allFlag = allFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INTER.T_PAYMENT.PAY_AREA
     *
     * @return the value of INTER.T_PAYMENT.PAY_AREA
     *
     * @mbggenerated Mon Oct 24 16:36:56 CST 2016
     */
    public String getPayArea() {
        return payArea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INTER.T_PAYMENT.PAY_AREA
     *
     * @param payArea the value for INTER.T_PAYMENT.PAY_AREA
     *
     * @mbggenerated Mon Oct 24 16:36:56 CST 2016
     */
    public void setPayArea(String payArea) {
        this.payArea = payArea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INTER.T_PAYMENT.PAY_MNG_INST
     *
     * @return the value of INTER.T_PAYMENT.PAY_MNG_INST
     *
     * @mbggenerated Mon Oct 24 16:36:56 CST 2016
     */
    public String getPayMngInst() {
        return payMngInst;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INTER.T_PAYMENT.PAY_MNG_INST
     *
     * @param payMngInst the value for INTER.T_PAYMENT.PAY_MNG_INST
     *
     * @mbggenerated Mon Oct 24 16:36:56 CST 2016
     */
    public void setPayMngInst(String payMngInst) {
        this.payMngInst = payMngInst;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INTER.T_PAYMENT.PAY_CR_TIME
     *
     * @return the value of INTER.T_PAYMENT.PAY_CR_TIME
     *
     * @mbggenerated Mon Oct 24 16:36:56 CST 2016
     */
    public Date getPayCrTime() {
        return payCrTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INTER.T_PAYMENT.PAY_CR_TIME
     *
     * @param payCrTime the value for INTER.T_PAYMENT.PAY_CR_TIME
     *
     * @mbggenerated Mon Oct 24 16:36:56 CST 2016
     */
    public void setPayCrTime(Date payCrTime) {
        this.payCrTime = payCrTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INTER.T_PAYMENT.PAY_CR_TEL
     *
     * @return the value of INTER.T_PAYMENT.PAY_CR_TEL
     *
     * @mbggenerated Mon Oct 24 16:36:56 CST 2016
     */
    public String getPayCrTel() {
        return payCrTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INTER.T_PAYMENT.PAY_CR_TEL
     *
     * @param payCrTel the value for INTER.T_PAYMENT.PAY_CR_TEL
     *
     * @mbggenerated Mon Oct 24 16:36:56 CST 2016
     */
    public void setPayCrTel(String payCrTel) {
        this.payCrTel = payCrTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INTER.T_PAYMENT.BEGIN_DATE
     *
     * @return the value of INTER.T_PAYMENT.BEGIN_DATE
     *
     * @mbggenerated Mon Oct 24 16:36:56 CST 2016
     */
    public String getBeginDate() {
        return beginDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INTER.T_PAYMENT.BEGIN_DATE
     *
     * @param beginDate the value for INTER.T_PAYMENT.BEGIN_DATE
     *
     * @mbggenerated Mon Oct 24 16:36:56 CST 2016
     */
    public void setBeginDate(String beginDate) {
        this.beginDate = beginDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INTER.T_PAYMENT.END_DATE
     *
     * @return the value of INTER.T_PAYMENT.END_DATE
     *
     * @mbggenerated Mon Oct 24 16:36:56 CST 2016
     */
    public String getEndDate() {
        return endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INTER.T_PAYMENT.END_DATE
     *
     * @param endDate the value for INTER.T_PAYMENT.END_DATE
     *
     * @mbggenerated Mon Oct 24 16:36:56 CST 2016
     */
    public void setEndDate(String endDate) {
        this.endDate = endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INTER.T_PAYMENT.MIN_AMT
     *
     * @return the value of INTER.T_PAYMENT.MIN_AMT
     *
     * @mbggenerated Mon Oct 24 16:36:56 CST 2016
     */
    public String getMinAmt() {
        return minAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INTER.T_PAYMENT.MIN_AMT
     *
     * @param minAmt the value for INTER.T_PAYMENT.MIN_AMT
     *
     * @mbggenerated Mon Oct 24 16:36:56 CST 2016
     */
    public void setMinAmt(String minAmt) {
        this.minAmt = minAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INTER.T_PAYMENT.MAX_AMT
     *
     * @return the value of INTER.T_PAYMENT.MAX_AMT
     *
     * @mbggenerated Mon Oct 24 16:36:56 CST 2016
     */
    public String getMaxAmt() {
        return maxAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INTER.T_PAYMENT.MAX_AMT
     *
     * @param maxAmt the value for INTER.T_PAYMENT.MAX_AMT
     *
     * @mbggenerated Mon Oct 24 16:36:56 CST 2016
     */
    public void setMaxAmt(String maxAmt) {
        this.maxAmt = maxAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INTER.T_PAYMENT.MIN_BAL
     *
     * @return the value of INTER.T_PAYMENT.MIN_BAL
     *
     * @mbggenerated Mon Oct 24 16:36:56 CST 2016
     */
    public String getMinBal() {
        return minBal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INTER.T_PAYMENT.MIN_BAL
     *
     * @param minBal the value for INTER.T_PAYMENT.MIN_BAL
     *
     * @mbggenerated Mon Oct 24 16:36:56 CST 2016
     */
    public void setMinBal(String minBal) {
        this.minBal = minBal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INTER.T_PAYMENT.MAX_BAL
     *
     * @return the value of INTER.T_PAYMENT.MAX_BAL
     *
     * @mbggenerated Mon Oct 24 16:36:56 CST 2016
     */
    public String getMaxBal() {
        return maxBal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INTER.T_PAYMENT.MAX_BAL
     *
     * @param maxBal the value for INTER.T_PAYMENT.MAX_BAL
     *
     * @mbggenerated Mon Oct 24 16:36:56 CST 2016
     */
    public void setMaxBal(String maxBal) {
        this.maxBal = maxBal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INTER.T_PAYMENT.PM_RULE_INDEX
     *
     * @return the value of INTER.T_PAYMENT.PM_RULE_INDEX
     *
     * @mbggenerated Mon Oct 24 16:36:56 CST 2016
     */
    public String getPmRuleIndex() {
        return pmRuleIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INTER.T_PAYMENT.PM_RULE_INDEX
     *
     * @param pmRuleIndex the value for INTER.T_PAYMENT.PM_RULE_INDEX
     *
     * @mbggenerated Mon Oct 24 16:36:56 CST 2016
     */
    public void setPmRuleIndex(String pmRuleIndex) {
        this.pmRuleIndex = pmRuleIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INTER.T_PAYMENT.KEY_INDEX
     *
     * @return the value of INTER.T_PAYMENT.KEY_INDEX
     *
     * @mbggenerated Mon Oct 24 16:36:56 CST 2016
     */
    public String getKeyIndex() {
        return keyIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INTER.T_PAYMENT.KEY_INDEX
     *
     * @param keyIndex the value for INTER.T_PAYMENT.KEY_INDEX
     *
     * @mbggenerated Mon Oct 24 16:36:56 CST 2016
     */
    public void setKeyIndex(String keyIndex) {
        this.keyIndex = keyIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INTER.T_PAYMENT.MSG_TYPE
     *
     * @return the value of INTER.T_PAYMENT.MSG_TYPE
     *
     * @mbggenerated Mon Oct 24 16:36:56 CST 2016
     */
    public String getMsgType() {
        return msgType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INTER.T_PAYMENT.MSG_TYPE
     *
     * @param msgType the value for INTER.T_PAYMENT.MSG_TYPE
     *
     * @mbggenerated Mon Oct 24 16:36:56 CST 2016
     */
    public void setMsgType(String msgType) {
        this.msgType = msgType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INTER.T_PAYMENT.CLASSES
     *
     * @return the value of INTER.T_PAYMENT.CLASSES
     *
     * @mbggenerated Mon Oct 24 16:36:56 CST 2016
     */
    public String getClasses() {
        return classes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INTER.T_PAYMENT.CLASSES
     *
     * @param classes the value for INTER.T_PAYMENT.CLASSES
     *
     * @mbggenerated Mon Oct 24 16:36:56 CST 2016
     */
    public void setClasses(String classes) {
        this.classes = classes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INTER.T_PAYMENT.CONTENT
     *
     * @return the value of INTER.T_PAYMENT.CONTENT
     *
     * @mbggenerated Mon Oct 24 16:36:56 CST 2016
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INTER.T_PAYMENT.CONTENT
     *
     * @param content the value for INTER.T_PAYMENT.CONTENT
     *
     * @mbggenerated Mon Oct 24 16:36:56 CST 2016
     */
    public void setContent(String content) {
        this.content = content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INTER.T_PAYMENT.PAYMENT_ICON
     *
     * @return the value of INTER.T_PAYMENT.PAYMENT_ICON
     *
     * @mbggenerated Mon Oct 24 16:36:56 CST 2016
     */
    public String getPaymentIcon() {
        return paymentIcon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INTER.T_PAYMENT.PAYMENT_ICON
     *
     * @param paymentIcon the value for INTER.T_PAYMENT.PAYMENT_ICON
     *
     * @mbggenerated Mon Oct 24 16:36:56 CST 2016
     */
    public void setPaymentIcon(String paymentIcon) {
        this.paymentIcon = paymentIcon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INTER.T_PAYMENT.TXN_TEMPLATE
     *
     * @return the value of INTER.T_PAYMENT.TXN_TEMPLATE
     *
     * @mbggenerated Mon Oct 24 16:36:56 CST 2016
     */
    public String getTxnTemplate() {
        return txnTemplate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INTER.T_PAYMENT.TXN_TEMPLATE
     *
     * @param txnTemplate the value for INTER.T_PAYMENT.TXN_TEMPLATE
     *
     * @mbggenerated Mon Oct 24 16:36:56 CST 2016
     */
    public void setTxnTemplate(String txnTemplate) {
        this.txnTemplate = txnTemplate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INTER.T_PAYMENT.MISC
     *
     * @return the value of INTER.T_PAYMENT.MISC
     *
     * @mbggenerated Mon Oct 24 16:36:56 CST 2016
     */
    public String getMisc() {
        return misc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INTER.T_PAYMENT.MISC
     *
     * @param misc the value for INTER.T_PAYMENT.MISC
     *
     * @mbggenerated Mon Oct 24 16:36:56 CST 2016
     */
    public void setMisc(String misc) {
        this.misc = misc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INTER.T_PAYMENT.BAK1
     *
     * @return the value of INTER.T_PAYMENT.BAK1
     *
     * @mbggenerated Mon Oct 24 16:36:56 CST 2016
     */
    public String getBak1() {
        return bak1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INTER.T_PAYMENT.BAK1
     *
     * @param bak1 the value for INTER.T_PAYMENT.BAK1
     *
     * @mbggenerated Mon Oct 24 16:36:56 CST 2016
     */
    public void setBak1(String bak1) {
        this.bak1 = bak1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INTER.T_PAYMENT.BAK2
     *
     * @return the value of INTER.T_PAYMENT.BAK2
     *
     * @mbggenerated Mon Oct 24 16:36:56 CST 2016
     */
    public String getBak2() {
        return bak2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INTER.T_PAYMENT.BAK2
     *
     * @param bak2 the value for INTER.T_PAYMENT.BAK2
     *
     * @mbggenerated Mon Oct 24 16:36:56 CST 2016
     */
    public void setBak2(String bak2) {
        this.bak2 = bak2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INTER.T_PAYMENT.LAST_UPD_BRH_ID
     *
     * @return the value of INTER.T_PAYMENT.LAST_UPD_BRH_ID
     *
     * @mbggenerated Mon Oct 24 16:36:56 CST 2016
     */
    public String getLastUpdBrhId() {
        return lastUpdBrhId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INTER.T_PAYMENT.LAST_UPD_BRH_ID
     *
     * @param lastUpdBrhId the value for INTER.T_PAYMENT.LAST_UPD_BRH_ID
     *
     * @mbggenerated Mon Oct 24 16:36:56 CST 2016
     */
    public void setLastUpdBrhId(String lastUpdBrhId) {
        this.lastUpdBrhId = lastUpdBrhId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INTER.T_PAYMENT.LAST_UPD_OPR_ID
     *
     * @return the value of INTER.T_PAYMENT.LAST_UPD_OPR_ID
     *
     * @mbggenerated Mon Oct 24 16:36:56 CST 2016
     */
    public String getLastUpdOprId() {
        return lastUpdOprId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INTER.T_PAYMENT.LAST_UPD_OPR_ID
     *
     * @param lastUpdOprId the value for INTER.T_PAYMENT.LAST_UPD_OPR_ID
     *
     * @mbggenerated Mon Oct 24 16:36:56 CST 2016
     */
    public void setLastUpdOprId(String lastUpdOprId) {
        this.lastUpdOprId = lastUpdOprId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INTER.T_PAYMENT.LAST_UPD_TXN_CD
     *
     * @return the value of INTER.T_PAYMENT.LAST_UPD_TXN_CD
     *
     * @mbggenerated Mon Oct 24 16:36:56 CST 2016
     */
    public String getLastUpdTxnCd() {
        return lastUpdTxnCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INTER.T_PAYMENT.LAST_UPD_TXN_CD
     *
     * @param lastUpdTxnCd the value for INTER.T_PAYMENT.LAST_UPD_TXN_CD
     *
     * @mbggenerated Mon Oct 24 16:36:56 CST 2016
     */
    public void setLastUpdTxnCd(String lastUpdTxnCd) {
        this.lastUpdTxnCd = lastUpdTxnCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INTER.T_PAYMENT.LAST_UPD_TS
     *
     * @return the value of INTER.T_PAYMENT.LAST_UPD_TS
     *
     * @mbggenerated Mon Oct 24 16:36:56 CST 2016
     */
    public Date getLastUpdTs() {
        return lastUpdTs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INTER.T_PAYMENT.LAST_UPD_TS
     *
     * @param lastUpdTs the value for INTER.T_PAYMENT.LAST_UPD_TS
     *
     * @mbggenerated Mon Oct 24 16:36:56 CST 2016
     */
    public void setLastUpdTs(Date lastUpdTs) {
        this.lastUpdTs = lastUpdTs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INTER.T_PAYMENT.PRINT_TYPE
     *
     * @return the value of INTER.T_PAYMENT.PRINT_TYPE
     *
     * @mbggenerated Mon Oct 24 16:36:56 CST 2016
     */
    public String getPrintType() {
        return printType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INTER.T_PAYMENT.PRINT_TYPE
     *
     * @param printType the value for INTER.T_PAYMENT.PRINT_TYPE
     *
     * @mbggenerated Mon Oct 24 16:36:56 CST 2016
     */
    public void setPrintType(String printType) {
        this.printType = printType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INTER.T_PAYMENT.CHNL_CLASS
     *
     * @return the value of INTER.T_PAYMENT.CHNL_CLASS
     *
     * @mbggenerated Mon Oct 24 16:36:56 CST 2016
     */
    public String getChnlClass() {
        return chnlClass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INTER.T_PAYMENT.CHNL_CLASS
     *
     * @param chnlClass the value for INTER.T_PAYMENT.CHNL_CLASS
     *
     * @mbggenerated Mon Oct 24 16:36:56 CST 2016
     */
    public void setChnlClass(String chnlClass) {
        this.chnlClass = chnlClass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INTER.T_PAYMENT.ORDER_NUM
     *
     * @return the value of INTER.T_PAYMENT.ORDER_NUM
     *
     * @mbggenerated Mon Oct 24 16:36:56 CST 2016
     */
    public Integer getOrderNum() {
        return orderNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INTER.T_PAYMENT.ORDER_NUM
     *
     * @param orderNum the value for INTER.T_PAYMENT.ORDER_NUM
     *
     * @mbggenerated Mon Oct 24 16:36:56 CST 2016
     */
    public void setOrderNum(Integer orderNum) {
        this.orderNum = orderNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INTER.T_PAYMENT.MSG_DESTINATION
     *
     * @return the value of INTER.T_PAYMENT.MSG_DESTINATION
     *
     * @mbggenerated Mon Oct 24 16:36:56 CST 2016
     */
    public String getMsgDestination() {
        return msgDestination;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INTER.T_PAYMENT.MSG_DESTINATION
     *
     * @param msgDestination the value for INTER.T_PAYMENT.MSG_DESTINATION
     *
     * @mbggenerated Mon Oct 24 16:36:56 CST 2016
     */
    public void setMsgDestination(String msgDestination) {
        this.msgDestination = msgDestination;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INTER.T_PAYMENT.MSG_SEND_TYPE
     *
     * @return the value of INTER.T_PAYMENT.MSG_SEND_TYPE
     *
     * @mbggenerated Mon Oct 24 16:36:56 CST 2016
     */
    public String getMsgSendType() {
        return msgSendType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INTER.T_PAYMENT.MSG_SEND_TYPE
     *
     * @param msgSendType the value for INTER.T_PAYMENT.MSG_SEND_TYPE
     *
     * @mbggenerated Mon Oct 24 16:36:56 CST 2016
     */
    public void setMsgSendType(String msgSendType) {
        this.msgSendType = msgSendType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INTER.T_PAYMENT.UPDATE_AMT_FLAG
     *
     * @return the value of INTER.T_PAYMENT.UPDATE_AMT_FLAG
     *
     * @mbggenerated Mon Oct 24 16:36:56 CST 2016
     */
    public String getUpdateAmtFlag() {
        return updateAmtFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INTER.T_PAYMENT.UPDATE_AMT_FLAG
     *
     * @param updateAmtFlag the value for INTER.T_PAYMENT.UPDATE_AMT_FLAG
     *
     * @mbggenerated Mon Oct 24 16:36:56 CST 2016
     */
    public void setUpdateAmtFlag(String updateAmtFlag) {
        this.updateAmtFlag = updateAmtFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INTER.T_PAYMENT.RECEIPT_PAY_CHNL
     *
     * @return the value of INTER.T_PAYMENT.RECEIPT_PAY_CHNL
     *
     * @mbggenerated Mon Oct 24 16:36:56 CST 2016
     */
    public String getReceiptPayChnl() {
        return receiptPayChnl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INTER.T_PAYMENT.RECEIPT_PAY_CHNL
     *
     * @param receiptPayChnl the value for INTER.T_PAYMENT.RECEIPT_PAY_CHNL
     *
     * @mbggenerated Mon Oct 24 16:36:56 CST 2016
     */
    public void setReceiptPayChnl(String receiptPayChnl) {
        this.receiptPayChnl = receiptPayChnl;
    }
}