package cn.koolyun.dao.inter;

import java.math.BigDecimal;
import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

import cn.koolyun.model.GgptTxnInfo;
import cn.koolyun.model.GgptTxnInfoExample;

public interface GgptTxnInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INTER.GGPT_TXN_INFO
     *
     * @mbggenerated Wed Oct 19 17:02:46 CST 2016
     */
    int countByExample(GgptTxnInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INTER.GGPT_TXN_INFO
     *
     * @mbggenerated Wed Oct 19 17:02:46 CST 2016
     */
    int deleteByExample(GgptTxnInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INTER.GGPT_TXN_INFO
     *
     * @mbggenerated Wed Oct 19 17:02:46 CST 2016
     */
    int deleteByPrimaryKey(BigDecimal txnId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INTER.GGPT_TXN_INFO
     *
     * @mbggenerated Wed Oct 19 17:02:46 CST 2016
     */
    int insert(GgptTxnInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INTER.GGPT_TXN_INFO
     *
     * @mbggenerated Wed Oct 19 17:02:46 CST 2016
     */
    int insertSelective(GgptTxnInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INTER.GGPT_TXN_INFO
     *
     * @mbggenerated Wed Oct 19 17:02:46 CST 2016
     */
    List<GgptTxnInfo> selectByExample(GgptTxnInfoExample example);
    
    
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INTER.GGPT_TXN_INFO
     *
     * @mbggenerated Wed Oct 19 17:02:46 CST 2016
     */
    List<GgptTxnInfo> selectByExampleWithBounds(GgptTxnInfoExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INTER.GGPT_TXN_INFO
     *
     * @mbggenerated Wed Oct 19 17:02:46 CST 2016
     */
    GgptTxnInfo selectByPrimaryKey(BigDecimal txnId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INTER.GGPT_TXN_INFO
     *
     * @mbggenerated Wed Oct 19 17:02:46 CST 2016
     */
    int updateByExampleSelective(@Param("record") GgptTxnInfo record, @Param("example") GgptTxnInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INTER.GGPT_TXN_INFO
     *
     * @mbggenerated Wed Oct 19 17:02:46 CST 2016
     */
    int updateByExample(@Param("record") GgptTxnInfo record, @Param("example") GgptTxnInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INTER.GGPT_TXN_INFO
     *
     * @mbggenerated Wed Oct 19 17:02:46 CST 2016
     */
    int updateByPrimaryKeySelective(GgptTxnInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INTER.GGPT_TXN_INFO
     *
     * @mbggenerated Wed Oct 19 17:02:46 CST 2016
     */
    int updateByPrimaryKey(GgptTxnInfo record);
}