package cn.koolyun.dao.inter;

import cn.koolyun.model.TdatDict;
import cn.koolyun.model.TdatDictExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TdatDictMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INTER.T_DAT_DICT
     *
     * @mbggenerated Mon Oct 24 16:36:56 CST 2016
     */
    int countByExample(TdatDictExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INTER.T_DAT_DICT
     *
     * @mbggenerated Mon Oct 24 16:36:56 CST 2016
     */
    int deleteByExample(TdatDictExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INTER.T_DAT_DICT
     *
     * @mbggenerated Mon Oct 24 16:36:56 CST 2016
     */
    int insert(TdatDict record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INTER.T_DAT_DICT
     *
     * @mbggenerated Mon Oct 24 16:36:56 CST 2016
     */
    int insertSelective(TdatDict record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INTER.T_DAT_DICT
     *
     * @mbggenerated Mon Oct 24 16:36:56 CST 2016
     */
    List<TdatDict> selectByExample(TdatDictExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INTER.T_DAT_DICT
     *
     * @mbggenerated Mon Oct 24 16:36:56 CST 2016
     */
    int updateByExampleSelective(@Param("record") TdatDict record, @Param("example") TdatDictExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INTER.T_DAT_DICT
     *
     * @mbggenerated Mon Oct 24 16:36:56 CST 2016
     */
    int updateByExample(@Param("record") TdatDict record, @Param("example") TdatDictExample example);
}