package cn.koolyun.dao.inter;

import cn.koolyun.model.TidMapper;
import cn.koolyun.model.TidMapperExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TidMapperMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INTER.T_ID_MAPPER
     *
     * @mbggenerated Thu Oct 20 18:07:34 CST 2016
     */
    int countByExample(TidMapperExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INTER.T_ID_MAPPER
     *
     * @mbggenerated Thu Oct 20 18:07:34 CST 2016
     */
    int deleteByExample(TidMapperExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INTER.T_ID_MAPPER
     *
     * @mbggenerated Thu Oct 20 18:07:34 CST 2016
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INTER.T_ID_MAPPER
     *
     * @mbggenerated Thu Oct 20 18:07:34 CST 2016
     */
    int insert(TidMapper record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INTER.T_ID_MAPPER
     *
     * @mbggenerated Thu Oct 20 18:07:34 CST 2016
     */
    int insertSelective(TidMapper record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INTER.T_ID_MAPPER
     *
     * @mbggenerated Thu Oct 20 18:07:34 CST 2016
     */
    List<TidMapper> selectByExample(TidMapperExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INTER.T_ID_MAPPER
     *
     * @mbggenerated Thu Oct 20 18:07:34 CST 2016
     */
    TidMapper selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INTER.T_ID_MAPPER
     *
     * @mbggenerated Thu Oct 20 18:07:34 CST 2016
     */
    int updateByExampleSelective(@Param("record") TidMapper record, @Param("example") TidMapperExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INTER.T_ID_MAPPER
     *
     * @mbggenerated Thu Oct 20 18:07:34 CST 2016
     */
    int updateByExample(@Param("record") TidMapper record, @Param("example") TidMapperExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INTER.T_ID_MAPPER
     *
     * @mbggenerated Thu Oct 20 18:07:34 CST 2016
     */
    int updateByPrimaryKeySelective(TidMapper record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INTER.T_ID_MAPPER
     *
     * @mbggenerated Thu Oct 20 18:07:34 CST 2016
     */
    int updateByPrimaryKey(TidMapper record);
}