package cn.koolyun.dao.inter;

import cn.koolyun.model.TmerInfo;
import cn.koolyun.model.TmerInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TmerInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INTER.T_MER_INFO
     *
     * @mbggenerated Tue Oct 25 14:03:35 CST 2016
     */
    int countByExample(TmerInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INTER.T_MER_INFO
     *
     * @mbggenerated Tue Oct 25 14:03:35 CST 2016
     */
    int deleteByExample(TmerInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INTER.T_MER_INFO
     *
     * @mbggenerated Tue Oct 25 14:03:35 CST 2016
     */
    int deleteByPrimaryKey(String merId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INTER.T_MER_INFO
     *
     * @mbggenerated Tue Oct 25 14:03:35 CST 2016
     */
    int insert(TmerInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INTER.T_MER_INFO
     *
     * @mbggenerated Tue Oct 25 14:03:35 CST 2016
     */
    int insertSelective(TmerInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INTER.T_MER_INFO
     *
     * @mbggenerated Tue Oct 25 14:03:35 CST 2016
     */
    List<TmerInfo> selectByExample(TmerInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INTER.T_MER_INFO
     *
     * @mbggenerated Tue Oct 25 14:03:35 CST 2016
     */
    TmerInfo selectByPrimaryKey(String merId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INTER.T_MER_INFO
     *
     * @mbggenerated Tue Oct 25 14:03:35 CST 2016
     */
    int updateByExampleSelective(@Param("record") TmerInfo record, @Param("example") TmerInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INTER.T_MER_INFO
     *
     * @mbggenerated Tue Oct 25 14:03:35 CST 2016
     */
    int updateByExample(@Param("record") TmerInfo record, @Param("example") TmerInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INTER.T_MER_INFO
     *
     * @mbggenerated Tue Oct 25 14:03:35 CST 2016
     */
    int updateByPrimaryKeySelective(TmerInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INTER.T_MER_INFO
     *
     * @mbggenerated Tue Oct 25 14:03:35 CST 2016
     */
    int updateByPrimaryKey(TmerInfo record);
}