package cn.koolyun.dao.inter;

import cn.koolyun.model.Tpayment;
import cn.koolyun.model.TpaymentExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TpaymentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INTER.T_PAYMENT
     *
     * @mbggenerated Mon Oct 24 16:36:56 CST 2016
     */
    int countByExample(TpaymentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INTER.T_PAYMENT
     *
     * @mbggenerated Mon Oct 24 16:36:56 CST 2016
     */
    int deleteByExample(TpaymentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INTER.T_PAYMENT
     *
     * @mbggenerated Mon Oct 24 16:36:56 CST 2016
     */
    int deleteByPrimaryKey(String payId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INTER.T_PAYMENT
     *
     * @mbggenerated Mon Oct 24 16:36:56 CST 2016
     */
    int insert(Tpayment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INTER.T_PAYMENT
     *
     * @mbggenerated Mon Oct 24 16:36:56 CST 2016
     */
    int insertSelective(Tpayment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INTER.T_PAYMENT
     *
     * @mbggenerated Mon Oct 24 16:36:56 CST 2016
     */
    List<Tpayment> selectByExample(TpaymentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INTER.T_PAYMENT
     *
     * @mbggenerated Mon Oct 24 16:36:56 CST 2016
     */
    Tpayment selectByPrimaryKey(String payId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INTER.T_PAYMENT
     *
     * @mbggenerated Mon Oct 24 16:36:56 CST 2016
     */
    int updateByExampleSelective(@Param("record") Tpayment record, @Param("example") TpaymentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INTER.T_PAYMENT
     *
     * @mbggenerated Mon Oct 24 16:36:56 CST 2016
     */
    int updateByExample(@Param("record") Tpayment record, @Param("example") TpaymentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INTER.T_PAYMENT
     *
     * @mbggenerated Mon Oct 24 16:36:56 CST 2016
     */
    int updateByPrimaryKeySelective(Tpayment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INTER.T_PAYMENT
     *
     * @mbggenerated Mon Oct 24 16:36:56 CST 2016
     */
    int updateByPrimaryKey(Tpayment record);
}