package cn.koolyun.dao.chps;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import cn.koolyun.model.AgFile;
import cn.koolyun.model.AgFileExample;

public interface AgFileMapper{
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHPS.AG_FILE
     *
     * @mbggenerated Wed Oct 19 16:02:52 CST 2016
     */
    int countByExample(AgFileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHPS.AG_FILE
     *
     * @mbggenerated Wed Oct 19 16:02:52 CST 2016
     */
    int deleteByExample(AgFileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHPS.AG_FILE
     *
     * @mbggenerated Wed Oct 19 16:02:52 CST 2016
     */
    int insert(AgFile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHPS.AG_FILE
     *
     * @mbggenerated Wed Oct 19 16:02:52 CST 2016
     */
    int insertSelective(AgFile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHPS.AG_FILE
     *
     * @mbggenerated Wed Oct 19 16:02:52 CST 2016
     */
    List<AgFile> selectByExample(AgFileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHPS.AG_FILE
     *
     * @mbggenerated Wed Oct 19 16:02:52 CST 2016
     */
    int updateByExampleSelective(@Param("record") AgFile record, @Param("example") AgFileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CHPS.AG_FILE
     *
     * @mbggenerated Wed Oct 19 16:02:52 CST 2016
     */
    int updateByExample(@Param("record") AgFile record, @Param("example") AgFileExample example);
}